using System;
using System.Collections.Generic;

namespace StackMerge
{
    // French (Français) translation table. Keys are the exact English source strings; sprite tags are
    // preserved verbatim. Game-specific proper nouns (solver names, PPO) are kept as-is.
    internal static class StackMergeLocalizationFr
    {
        public static readonly Dictionary<string, string> Table = new(StringComparer.Ordinal)
        {
            ["Play"] = "Jeu",
            ["Algos"] = "Algos",
            ["Algorithms"] = "Algorithmes",
            ["Upgrades"] = "Améliorations",
            ["Agents"] = "Agents",
            ["Mods"] = "Mods",
            ["Modifiers"] = "Modificateurs",
            ["Research"] = "Recherche",
            ["DC"] = "CD",
            ["Next"] = "Suivant",
            ["History"] = "Historique",
            ["Achievements"] = "Succès",
            ["Settings"] = "Paramètres",
            ["Locked"] = "Verrouillé",
            ["Unlocked"] = "Débloqué",
            ["Select"] = "Choisir",
            ["Deselect"] = "Désélect.",
            ["Tune"] = "Ajuster",
            ["Change mode"] = "Changer de mode",
            ["Buy"] = "Acheter",
            ["Equip"] = "Équiper",
            ["Unequip"] = "Retirer",
            ["Maxed"] = "Au max",
            ["Done"] = "Terminé",
            ["New run"] = "Nouveau run",
            ["Manual"] = "Manuel",
            ["Manual mode"] = "Mode manuel",
            ["Auto solving"] = "Résolution auto",
            ["Run ended"] = "Run terminé",
            ["Run time"] = "Durée du run",
            ["Config info"] = "Infos config",
            ["Import save"] = "Importer une sauvegarde",
            ["Automatization"] = "Automatisation",
            ["Income Bonus"] = "Bonus de revenu",
            ["Passive Production"] = "Production passive",
            ["Solver Speed"] = "Vitesse du solver",
            ["Stack Capacity"] = "Capacité de pile",
            ["Number of next blocks visible"] = "Nombre de blocs suivants visibles",
            ["Higher blocks spawn"] = "Apparition de blocs plus élevés",
            ["Lab Unlocks"] = "Déblocages du labo",
            ["Passive PPO frame reduction"] = "Réduction passive de frames PPO",
            ["All Agents"] = "Tous les agents",
            ["Base <sprite name=\"chips\" tint=1> income"] = "Revenu de base en <sprite name=\"chips\" tint=1>",
            ["Ending profit"] = "Profit de fin",
            ["Merge streak"] = "Série de fusions",
            ["Score salvage"] = "Récupération de score",
            ["Passive <sprite name=\"chips\" tint=1> / tick"] = "<sprite name=\"chips\" tint=1> passifs / tick",
            ["Passive tick rate"] = "Fréquence de tick passive",
            ["Active multiplier"] = "Multiplicateur actif",
            ["Faster solver"] = "Solver plus rapide",
            ["Solver delay"] = "Délai du solver",
            ["Stack rows"] = "Rangées de pile",
            ["Visible blocks"] = "Blocs visibles",
            ["Higher chance"] = "Meilleure chance",
            ["Higher frequency"] = "Fréquence accrue",
            ["Stage Progression"] = "Progression des phases",
            ["Prestige Console"] = "Console de prestige",
            ["Collection"] = "Collection",
            ["PPO Training complete — prestige reset unlocked."] = "Entraînement PPO terminé — réinitialisation prestige débloquée.",
            ["Auto restart needs token"] = "Le redémarrage auto nécessite un jeton",
            ["The run hasn't started yet."] = "Le run n'a pas encore commencé.",
            ["No moves left — run over"] = "Plus de coups — run terminé",
            ["Not enough <sprite name=\"chips\" tint=1>"] = "Pas assez de <sprite name=\"chips\" tint=1>",
            ["Buy an algorithm first"] = "Achète d'abord un algorithme",
            ["Speed upgrade unavailable"] = "Amélioration de vitesse indisponible",
            ["Stack upgrade unavailable"] = "Amélioration de pile indisponible",
            ["Next preview upgrade unavailable"] = "Amélioration d'aperçu indisponible",
            ["Income upgrade unavailable"] = "Amélioration de revenu indisponible",
            ["Solver tuning unlocked"] = "Réglage du solver débloqué",
            ["Auto solve updated"] = "Résolution auto mise à jour",
            ["Auto restart updated"] = "Redémarrage auto mis à jour",
            ["Modifier Lab unlocked"] = "Labo de modificateurs débloqué",
            ["Unlock Agents in Upgrades first"] = "Débloque d'abord les agents dans les améliorations",
            ["Unlock Modifier Lab in Upgrades first"] = "Débloque d'abord le labo de modificateurs dans les améliorations",
            ["Finish PPO Training first"] = "Termine d'abord l'entraînement PPO",
            ["Unlock PPO to open Research"] = "Débloque PPO pour ouvrir la recherche",
            ["Normal mode is still locked."] = "Le mode normal est encore verrouillé.",
            ["PPO: Training mode"] = "PPO : mode entraînement",
            ["PPO: Normal mode"] = "PPO : mode normal",
            ["Training Mode"] = "Mode entraînement",
            ["Normal Mode"] = "Mode normal",
            ["Normal Mode\nLocked"] = "Mode normal\nVerrouillé",
            ["PPO Mode Overlay is not assigned."] = "PPO Mode Overlay n'est pas assigné.",
            ["Training: keeps learning, earns no chips.\nNormal: plays for chips like other solvers."] = "Entraînement : continue d'apprendre, ne gagne pas de chips.\nNormal : joue pour des chips comme les autres solvers.",
            ["Music"] = "Musique",
            ["Sound"] = "Son",
            ["Enable haptic feedback"] = "Activer le retour haptique",
            ["Show FPS"] = "Afficher les FPS",
            ["Hide FPS"] = "Masquer les FPS",
            ["Achievement Pop-ups"] = "Pop-ups de succès",
            ["Hide achievement pop-ups"] = "Masquer les pop-ups de succès",
            ["Export / Import game"] = "Exporter / importer la partie",
            ["Language"] = "Langue",
            ["Manual controls"] = "Commandes manuelles",
            ["Tap a stack to place the current next block."] = "Touche une pile pour placer le bloc suivant actuel.",
            ["Equip Miner's Pickaxe, then tap a stack block to remove it."] = "Équipe la Miner's Pickaxe, puis touche un bloc d'une pile pour le retirer.",
            ["Equip Queue Scrubber, then tap the first next block to remove it."] = "Équipe le Queue Scrubber, puis touche le premier bloc suivant pour le retirer.",
            ["Tap a block to remove it with Miner's Pickaxe"] = "Touche un bloc pour le retirer avec la Miner's Pickaxe",
            ["Tap the first next block to scrub it"] = "Touche le premier bloc suivant pour le supprimer",
            ["Miner's Pickaxe equipped"] = "Miner's Pickaxe équipée",
            ["Miner's Pickaxe unequipped"] = "Miner's Pickaxe retirée",
            ["Queue Scrubber equipped"] = "Queue Scrubber équipé",
            ["Queue Scrubber unequipped"] = "Queue Scrubber retiré",
            ["Miner's Pickaxe is locked"] = "La Miner's Pickaxe est verrouillée",
            ["Queue Scrubber is locked"] = "Le Queue Scrubber est verrouillé",
            ["Miner's Pickaxe has no uses left"] = "Plus d'utilisations de Miner's Pickaxe",
            ["Queue Scrubber has no uses left"] = "Plus d'utilisations de Queue Scrubber",
            ["No block available for Miner's Pickaxe"] = "Aucun bloc disponible pour la Miner's Pickaxe",
            ["No next block available for Queue Scrubber"] = "Aucun bloc suivant disponible pour le Queue Scrubber",
            ["Modifier unavailable"] = "Modificateur indisponible",
            ["Unlocks rule-changing modules that apply to new runs."] = "Débloque des modules changeant les règles, appliqués aux nouveaux runs.",
            ["The solver places blocks faster with each level."] = "Le solver place les blocs plus vite à chaque niveau.",
            ["Solver is automatically playing the game."] = "Le solver joue automatiquement.",
            ["When the run ends, a new one starts automatically."] = "Quand le run se termine, un nouveau démarre automatiquement.",
            ["The currency for Auto restart."] = "La monnaie pour le redémarrage auto.",
            ["Allows you to modify the solver parameters."] = "Permet de modifier les paramètres du solver.",
            ["Another slot so you can use 3 Agents at once."] = "Un slot supplémentaire pour utiliser 3 agents à la fois.",
            ["They give you extra bonuses when you unlock them."] = "Ils donnent des bonus supplémentaires une fois débloqués.",
            ["Increases the capacity of each stack by 1 per level."] = "Augmente la capacité de chaque pile de 1 par niveau.",
            ["Shows 1 more upcoming block per level."] = "Affiche 1 bloc à venir de plus par niveau.",
            ["Increases the chance of spawning higher blocks."] = "Augmente la chance de faire apparaître des blocs plus élevés.",
            ["Slightly increases how often higher blocks appear."] = "Augmente légèrement la fréquence des blocs plus élevés.",
            ["Boosts base <sprite name=\"chips\" tint=1> income. Early levels give larger gains."] = "Augmente le revenu de base en <sprite name=\"chips\" tint=1>. Les premiers niveaux rapportent davantage.",
            ["Boosts the <sprite name=\"chips\" tint=1> bonus at the end of the runs."] = "Augmente le bonus de <sprite name=\"chips\" tint=1> à la fin des runs.",
            ["Boosts the <sprite name=\"chips\" tint=1> earned during merges and runs."] = "Augmente les <sprite name=\"chips\" tint=1> gagnés lors des fusions et des runs.",
            ["Shrinks the delay of MOCA and PLAN solvers."] = "Réduit le délai des solvers MOCA et PLAN.",
            ["Chips trickle in on a timer, on top of your normal play."] = "Les chips arrivent au compte-gouttes via un minuteur, en plus du jeu normal.",
            ["Passive Production ticks more often."] = "La production passive tick plus souvent.",
            ["Lowers the frame needed in Training Mode."] = "Réduit les frames nécessaires en mode entraînement.",
            ["Lowers the frames needed for PPO Normal Mode."] = "Réduit les frames nécessaires pour le mode normal PPO.",
            ["Each level shortens how often Curriculum lowers the PPO requirement."] = "Chaque niveau raccourcit la fréquence à laquelle le Curriculum réduit l'exigence PPO.",
            ["Needs Difficulty L1"] = "Nécessite Difficulté N1",
            ["Needs PPO or Bootcamp L5"] = "Nécessite PPO ou Bootcamp N5",
            ["Needs Curriculum"] = "Nécessite Curriculum",
            ["Boosts Passive Production while you're actively playing."] = "Augmente la production passive pendant que tu joues activement.",
            ["Passive yield upgrade unavailable"] = "Amélioration de rendement passif indisponible",
            ["Passive tick rate upgrade unavailable"] = "Amélioration de fréquence passive indisponible",
            ["Active multiplier upgrade unavailable"] = "Amélioration de multiplicateur actif indisponible",
            ["Compute speed upgrade unavailable"] = "Amélioration de vitesse de calcul indisponible",
            ["Stage locked"] = "Phase verrouillée",
            ["Needs algorithm"] = "Nécessite un algorithme",
            ["Needs Agents"] = "Nécessite des agents",
            ["Stage 1 - Core automation"] = "Phase 1 - Automatisation de base",
            ["Stage 2 - Agent acceleration"] = "Phase 2 - Accélération par agents",
            ["Stage 3 - Modifier Lab"] = "Phase 3 - Labo de modificateurs",
            ["Stage 4 - Machine Learning"] = "Phase 4 - Apprentissage automatique",
            ["Endgame - PPO training"] = "Fin de partie - entraînement PPO",
            ["Train PPO, then prestige from the Research menu."] = "Entraîne PPO, puis fais prestige depuis le menu Recherche.",
            ["PPO is ready to unlock in Algorithms."] = "PPO est prêt à être débloqué dans les Algorithmes.",
            ["Max every Modifier to open the Machine Learning layer."] = "Maximise chaque modificateur pour ouvrir la couche Apprentissage automatique.",
            ["Open Agents to start the next stage."] = "Ouvre les agents pour démarrer la phase suivante.",
            ["Unlock COMBO or LOOK solver to open Agents."] = "Débloque le solver COMBO ou LOOK pour ouvrir les agents.",
            ["Unlock COMBO or LOOK solver first."] = "Débloque d'abord le solver COMBO ou LOOK.",
            ["Modifiers Lab"] = "Labo de modificateurs",
            ["Agents Lab"] = "Labo d'agents",
            ["Stack capacity"] = "Capacité de pile",
            ["Difficulty"] = "Difficulté",
            ["Speed"] = "Vitesse",
            ["Auto solve"] = "Résolution auto",
            ["Auto restart"] = "Redémarrage auto",
            ["Mode"] = "Mode",
            ["Run score"] = "Score du run",
            ["Score"] = "Score",
            ["Median"] = "Médiane",
            ["Best"] = "Meilleur",
            ["Moves"] = "Coups",
            ["Merges"] = "Fusions",
            ["Current next"] = "Suivant actuel",
            ["Available actions"] = "Actions disponibles",
            ["Solver"] = "Solver",
            ["Run modifiers"] = "Modificateurs de run",
            ["Special blocks"] = "Blocs spéciaux",
            ["Solver tuning"] = "Réglage du solver",
            ["+50 tokens"] = "+50 jetons",
            ["Locked in Upgrades."] = "Déblocable dans les améliorations.",
            ["No tuning available for this solver."] = "Aucun réglage disponible pour ce solver.",
            ["Default"] = "Défaut",
            ["RAND has no tuning. Its identity is pure randomness."] = "RAND n'a aucun réglage. Son identité est le pur hasard.",
            ["MERG stays greedy, but these sliders decide how hard it chases immediate value."] = "MERG reste vorace, mais ces curseurs décident à quel point il poursuit la valeur immédiate.",
            ["BAL remains a board stabilizer. Tune how defensive or merge-friendly it should be."] = "BAL reste un stabilisateur de plateau. Ajuste s'il doit être plus défensif ou plus favorable aux fusions.",
            ["HEUR is a weighted score formula. These are the clearest direct knobs."] = "HEUR est une formule de score pondérée. Voici ses réglages directs les plus clairs.",
            ["LOOK uses HEUR plus a follow-up estimate. Tune its greed and its second-step trust."] = "LOOK utilise HEUR plus une estimation du coup suivant. Ajuste sa voracité et sa confiance au second coup.",
            ["MOCA samples futures. Its tuning can spend a little more thinking on rollout depth or sample count."] = "MOCA échantillonne des futurs. Son réglage peut consacrer un peu plus de réflexion à la profondeur de rollout ou au nombre d'échantillons.",
            ["PLAN searches the visible queue. Tune how much it trusts short plans over current safety."] = "PLAN explore la file visible. Ajuste combien il fait confiance aux plans courts face à la sécurité actuelle.",
            ["PLAN-5 searches deeper queue lines. Tuning lets you decide whether it should be patient or practical."] = "PLAN-5 explore des lignes de file plus profondes. Le réglage décide s'il doit être patient ou pragmatique.",
            ["MOCA+ uses smarter rollouts. Tuning affects both how much it samples and how it values rollout boards."] = "MOCA+ utilise des rollouts plus intelligents. Le réglage affecte le nombre d'échantillons et la valeur des plateaux de rollout.",
            ["MCTS builds a tree. These sliders tune search behavior without replacing the tree search identity."] = "MCTS construit un arbre. Ces curseurs ajustent le comportement de recherche sans remplacer l'identité de la recherche arborescente.",
            ["STALL is defensive. Tune how much it sacrifices score to keep the board alive."] = "STALL est défensif. Ajuste combien de score il sacrifie pour garder le plateau en vie.",
            ["COMBO looks for chain setups. Tune how patient it should be while preparing cascades."] = "COMBO cherche à préparer des chaînes. Ajuste sa patience lors de la préparation des cascades.",
            ["PPO trains its own actor-critic network. These nudge the learning hyperparameters within safe bounds."] = "PPO entraîne son propre réseau acteur-critique. Ceux-ci ajustent les hyperparamètres d'apprentissage dans des limites sûres.",
            ["Merge reward"] = "Récompense de fusion",
            ["Score delta"] = "Delta de score",
            ["High block"] = "Bloc élevé",
            ["Height penalty"] = "Pénalité de hauteur",
            ["Empty cells"] = "Cellules vides",
            ["Smoothness"] = "Régularité",
            ["Danger penalty"] = "Pénalité de danger",
            ["Queue fit"] = "Adéquation file",
            ["Follow-up trust"] = "Confiance au coup suivant",
            ["Simulation rounds"] = "Tours de simulation",
            ["Rollout moves"] = "Coups de rollout",
            ["Planning depth"] = "Profondeur de plan",
            ["Future weight"] = "Poids du futur",
            ["Rollout planning"] = "Planification rollout",
            ["Board eval"] = "Éval. plateau",
            ["Anti-stall"] = "Anti-blocage",
            ["Tree visits"] = "Visites d'arbre",
            ["Exploration"] = "Exploration",
            ["Prior bias"] = "Biais a priori",
            ["Safety cushion"] = "Coussin de sécurité",
            ["Combo setup"] = "Préparation combo",
            ["Legal moves"] = "Coups légaux",
            ["Height spread"] = "Écart de hauteur",
            ["Future depth"] = "Profondeur future",
            ["Gamma (discount)"] = "Gamma (remise)",
            ["Lambda (GAE)"] = "Lambda (GAE)",
            ["Clip epsilon"] = "Epsilon de clip",
            ["Raises or lowers the reward for immediate merges and cascade size."] = "Augmente ou diminue la récompense des fusions immédiates et de la taille des cascades.",
            ["Changes how much raw score gained by the move matters."] = "Modifie l'importance du score brut gagné par le coup.",
            ["Pushes the solver toward producing larger top blocks."] = "Pousse le solver à produire de plus grands blocs de tête.",
            ["Positive values avoid tall uneven stacks more strongly."] = "Les valeurs positives évitent plus fortement les piles hautes et irrégulières.",
            ["Rewards boards with more open cells after the move."] = "Récompense les plateaux avec plus de cellules libres après le coup.",
            ["Rewards similar stack heights and penalizes lopsided boards."] = "Récompense des hauteurs de pile similaires et pénalise les plateaux déséquilibrés.",
            ["Penalizes stacks near capacity more strongly."] = "Pénalise plus fortement les piles proches de la capacité.",
            ["Lets BAL accept more merge value before spreading out."] = "Permet à BAL d'accepter plus de valeur de fusion avant de se disperser.",
            ["Changes how strongly immediate score gain affects the move score."] = "Modifie l'influence du gain de score immédiat sur le score du coup.",
            ["Rewards free stack cells after the move."] = "Récompense les cellules de pile libres après le coup.",
            ["Rewards smoother stack heights and fewer awkward bottlenecks."] = "Récompense des hauteurs de pile plus régulières et moins de goulots gênants.",
            ["Rewards top blocks that match upcoming queue values."] = "Récompense les blocs de tête qui correspondent aux valeurs à venir de la file.",
            ["Raises or lowers the value of immediate merge chains."] = "Augmente ou diminue la valeur des chaînes de fusion immédiates.",
            ["Makes near-full stacks scarier to the heuristic."] = "Rend les piles presque pleines plus effrayantes pour l'heuristique.",
            ["Changes how much the first move's score gain matters."] = "Modifie l'importance du gain de score du premier coup.",
            ["Rewards keeping more room open after the first move."] = "Récompense le fait de garder plus d'espace libre après le premier coup.",
            ["Changes how much the simulated next move influences the choice."] = "Modifie l'influence du coup suivant simulé sur le choix.",
            ["Rewards stack tops that line up with visible upcoming blocks."] = "Récompense les sommets de pile alignés sur les blocs à venir visibles.",
            ["Punishes positions that are close to stalling."] = "Punit les positions proches du blocage.",
            ["Adjusts how many futures are sampled for each legal move."] = "Ajuste le nombre de futurs échantillonnés pour chaque coup légal.",
            ["Adjusts how many moves each future is played forward."] = "Ajuste sur combien de coups chaque futur est joué.",
            ["Changes the immediate score bias inside rollout evaluation."] = "Modifie le biais de score immédiat dans l'évaluation des rollouts.",
            ["Rewards futures that leave more cells open."] = "Récompense les futurs qui laissent plus de cellules libres.",
            ["Makes dangerous simulated boards less attractive."] = "Rend les plateaux simulés dangereux moins attractifs.",
            ["Rewards rollouts that keep useful top blocks for the visible queue."] = "Récompense les rollouts qui gardent des blocs de tête utiles pour la file visible.",
            ["Shifts how many visible queued blocks the search tries to use."] = "Modifie combien de blocs visibles en file la recherche tente d'utiliser.",
            ["Changes how strongly future planned moves affect the first move."] = "Modifie l'influence des coups planifiés futurs sur le premier coup.",
            ["Rewards stack tops that match upcoming values."] = "Récompense les sommets de pile qui correspondent aux valeurs à venir.",
            ["Rewards planned lines that keep space available."] = "Récompense les lignes planifiées qui gardent de l'espace disponible.",
            ["Penalizes plans that leave near-full stacks."] = "Pénalise les plans laissant des piles presque pleines.",
            ["Shifts how many queued blocks the search tries to use."] = "Modifie combien de blocs en file la recherche tente d'utiliser.",
            ["Changes how strongly deeper planned scores affect the first move."] = "Modifie l'influence des scores planifiés plus profonds sur le premier coup.",
            ["Rewards preserving useful stack tops for upcoming blocks."] = "Récompense la préservation de sommets de pile utiles pour les blocs à venir.",
            ["Rewards plans that leave more board room."] = "Récompense les plans qui laissent plus d'espace sur le plateau.",
            ["Penalizes risky deep plans more strongly."] = "Pénalise plus fortement les plans profonds risqués.",
            ["Adjusts how many smart futures are sampled for each move."] = "Ajuste le nombre de futurs intelligents échantillonnés par coup.",
            ["Adjusts how far smart futures are played forward."] = "Ajuste jusqu'où les futurs intelligents sont joués.",
            ["Adjusts how much queue planning each rollout uses."] = "Ajuste la quantité de planification de file utilisée par chaque rollout.",
            ["Changes how much the final simulated board shape matters."] = "Modifie l'importance de la forme finale du plateau simulé.",
            ["Rewards futures that preserve legal moves and escape routes."] = "Récompense les futurs qui préservent les coups légaux et les issues de secours.",
            ["Adjusts how many tree iterations are spent per decision."] = "Ajuste le nombre d'itérations d'arbre par décision.",
            ["Higher values try less-proven branches more often."] = "Des valeurs plus élevées essaient plus souvent des branches moins éprouvées.",
            ["Changes how strongly heuristic prior scores guide the tree."] = "Modifie la force avec laquelle les scores a priori heuristiques guident l'arbre.",
            ["Adjusts how far rollouts play from a tree node."] = "Ajuste jusqu'où les rollouts jouent depuis un nœud de l'arbre.",
            ["Rewards tree lines that leave room and legal moves."] = "Récompense les lignes d'arbre qui laissent de l'espace et des coups légaux.",
            ["Rewards lines that create potential chain merges."] = "Récompense les lignes créant de potentielles fusions en chaîne.",
            ["Rewards positions with multiple available stacks."] = "Récompense les positions avec plusieurs piles disponibles.",
            ["Rewards spare capacity after each move."] = "Récompense la capacité libre après chaque coup.",
            ["Punishes near-full stacks more strongly."] = "Punit plus fortement les piles presque pleines.",
            ["Penalizes uneven stack heights."] = "Pénalise les hauteurs de pile inégales.",
            ["Lets STALL take more immediate merge value."] = "Permet à STALL de prendre plus de valeur de fusion immédiate.",
            ["Rewards adjacent equal values and future cascade potential."] = "Récompense les valeurs égales adjacentes et le potentiel de cascade futur.",
            ["Changes how much immediate merging competes with setup."] = "Modifie à quel point la fusion immédiate concurrence la préparation.",
            ["Adjusts how many setup moves the combo estimate looks through."] = "Ajuste combien de coups de préparation l'estimation de combo examine.",
            ["Keeps some space open while building combos."] = "Garde de l'espace libre pendant la construction de combos.",
            ["How far ahead future reward is valued. Higher plans longer-term, lower is greedier."] = "Jusqu'où la récompense future est valorisée. Plus haut planifie à plus long terme, plus bas est plus vorace.",
            ["Advantage estimation bias/variance trade-off. Higher = lower bias, more variance."] = "Compromis biais/variance de l'estimation d'avantage. Plus haut = moins de biais, plus de variance.",
            ["How big a policy update each step may make. Smaller is more conservative and stable."] = "L'ampleur de la mise à jour de politique par étape. Plus petit est plus conservateur et stable.",
            ["Completed"] = "Terminé",
            ["Secrets"] = "Secrets",
            ["Statistics"] = "Statistiques",
            ["PPO Progress"] = "Progression PPO",
            ["No completed runs yet. Let a run end to start collecting solver stats."] = "Aucun run terminé pour l'instant. Laisse un run se terminer pour collecter les stats des solvers.",
            ["Tip: use the editor benchmark window for large balance samples without touching player progression."] = "Astuce : utilise la fenêtre de benchmark de l'éditeur pour de grands échantillons d'équilibrage sans toucher à la progression du joueur.",
            ["Earn 10000 <sprite name=\"chips\" tint=1> in total"] = "Gagne 10000 <sprite name=\"chips\" tint=1> au total",
            ["Earn 1M <sprite name=\"chips\" tint=1> in total"] = "Gagne 1M <sprite name=\"chips\" tint=1> au total",
            ["Earn 1B <sprite name=\"chips\" tint=1> in total"] = "Gagne 1B <sprite name=\"chips\" tint=1> au total",
            ["Spend 10000 <sprite name=\"chips\" tint=1> in total"] = "Dépense 10000 <sprite name=\"chips\" tint=1> au total",
            ["Spend 100K <sprite name=\"chips\" tint=1> in total"] = "Dépense 100K <sprite name=\"chips\" tint=1> au total",
            ["Spend 100M <sprite name=\"chips\" tint=1> in total"] = "Dépense 100M <sprite name=\"chips\" tint=1> au total",
            ["Complete 10 runs while Auto Solver is turned off"] = "Termine 10 runs avec l'Auto-Solver désactivé",
            ["Complete 1000 runs with a solver"] = "Termine 1000 runs avec un solver",
            ["Move a total of 10000 times"] = "Joue 10000 coups au total",
            ["Move a total of 100K times"] = "Joue 100K coups au total",
            ["Move a total of 1M times"] = "Joue 1M coups au total",
            ["Merge a total of 10000 times"] = "Fusionne 10000 fois au total",
            ["Merge a total of 100K times"] = "Fusionne 100K fois au total",
            ["Merge a total of 1M times"] = "Fusionne 1M fois au total",
            ["Reach high 1024"] = "Atteins le bloc 1024",
            ["Reach high 8192"] = "Atteins le bloc 8192",
            ["Reach high 65536"] = "Atteins le bloc 65536",
            ["Unlock Agents"] = "Débloque les agents",
            ["Equip 3 Agents at once"] = "Équipe 3 agents à la fois",
            ["Unlock Modifiers"] = "Débloque les modificateurs",
            ["Use all solvers at least once"] = "Utilise chaque solver au moins une fois",
            ["Use all Agents at least once"] = "Utilise chaque agent au moins une fois",
            ["Let Unstable Stack save your run a total of 100 times"] = "Laisse Unstable Stack sauver ton run 100 fois au total",
            ["Merge with a Joker for a total of 100 times"] = "Fusionne avec un Joker 100 fois au total",
            ["Consume a total of 5000 <sprite name=\"token\" tint=1>"] = "Consomme 5000 <sprite name=\"token\" tint=1> au total",
            ["Hold at least 10000 <sprite name=\"token\" tint=1> at once"] = "Détiens au moins 10000 <sprite name=\"token\" tint=1> à la fois",
            ["Prestige reset for the first time"] = "Fais un reset prestige pour la première fois",
            ["Prestige reset for a total of 5 times"] = "Fais un reset prestige 5 fois au total",
            ["Prestige reset for a total of 15 times"] = "Fais un reset prestige 15 fois au total",
            ["Run PPO once in Normal Mode"] = "Lance PPO une fois en mode normal",
            ["Reach 100K PPO frames"] = "Atteins 100K frames PPO",
            ["Earn 1000 <sprite name=\"insight\" tint=1> in total"] = "Gagne 1000 <sprite name=\"insight\" tint=1> au total",
            ["Earn 10K <sprite name=\"insight\" tint=1> in total"] = "Gagne 10K <sprite name=\"insight\" tint=1> au total",
            ["Earn 100K <sprite name=\"insight\" tint=1> in total"] = "Gagne 100K <sprite name=\"insight\" tint=1> au total",
            ["Buy all the researches"] = "Achète toutes les recherches",
            ["Have at least 1 unit in each Server Rack"] = "Possède au moins 1 unité dans chaque Server Rack",
            ["Go above 1000 GF/s total compute"] = "Dépasse 1000 GF/s de calcul total",
            ["Reach 1M PPO Training frames"] = "Atteins 1M frames d'entraînement PPO",
            ["Let It Cook"] = "Laisse mijoter",
            ["Budget Intelligence"] = "Intelligence économique",
            ["Surgical Move"] = "Coup chirurgical",
            ["Perfectly Reasonable"] = "Parfaitement raisonnable",
            ["Full Autopilot"] = "Pilote automatique complet",
            ["Bad Financial Advice"] = "Mauvais conseil financier",
            ["Still Here"] = "Toujours là",
            ["One More Run"] = "Encore un run",
            ["See You Again"] = "À bientôt",
            ["Perfectly Balanced"] = "Parfaitement équilibré",
            ["Second Thoughts"] = "Doutes",
            ["No Defaults Given"] = "Plus aucune valeur par défaut",
            ["Let it cook"] = "Laisse mijoter",
            ["Old intelligence"] = "Vieille intelligence",
            ["Remove something big"] = "Retire quelque chose de gros",
            ["A very specific reserve"] = "Une réserve très précise",
            ["Everything buys itself"] = "Tout s'achète tout seul",
            ["Questionable first purchase"] = "Premier achat douteux",
            ["Stay a while"] = "Reste un moment",
            ["Just one more run"] = "Juste encore un run",
            ["Come back often"] = "Reviens souvent",
            ["Almost perfectly split"] = "Presque parfaitement réparti",
            ["Second thoughts"] = "Doute soudain",
            ["No defaults left"] = "Plus de valeurs par défaut",
            ["Earn offline rewards after being away for 8+ hours."] = "Obtiens des récompenses hors-ligne après 8 h ou plus d'absence.",
            ["Complete a run with RAND after unlocking PPO."] = "Termine un run avec RAND après avoir débloqué PPO.",
            ["Use Miner's Pickaxe on a block worth 1024 or higher."] = "Utilise la Miner's Pickaxe sur un bloc de 1024 ou plus.",
            ["Hold exactly 2048 <sprite name=\"token\" tint=1> after a run ends."] = "Détiens exactement 2048 <sprite name=\"token\" tint=1> à la fin d'un run.",
            ["Have all Auto Buy buttons enabled simultaneously."] = "Active tous les boutons Auto-Achat en même temps.",
            ["Buy the Joker as your first Modifier in a prestige."] = "Achète le Joker comme premier modificateur d'un prestige.",
            ["Have 24 hours of lifetime playtime."] = "Atteins 24 heures de temps de jeu total.",
            ["Leave the game open for 2 hours straight."] = "Laisse le jeu ouvert pendant 2 heures d'affilée.",
            ["Exit the game 10 times."] = "Quitte le jeu 10 fois.",
            ["Split Compute Allocation exactly 33-33-33-1."] = "Répartis l'allocation de calcul exactement 33-33-33-1.",
            ["Deselect a solver immediately after selecting it."] = "Désélectionne un solver juste après l'avoir choisi.",
            ["Modify all parameters of PPO in Tuning."] = "Modifie tous les paramètres de PPO dans le réglage.",
            ["Unlocks Auto Buy for Algos, Upgrades, Agents and Mods"] = "Débloque l'Auto-Achat pour les Algos, améliorations, agents et mods",
            ["Unlocks Datacenter"] = "Débloque le centre de données",
            ["Merge streak upgrade at max level is 5% stronger"] = "L'amélioration Série de fusions au niveau max est 5% plus forte",
            ["PPO learns from your Manual runs"] = "PPO apprend de tes runs manuels",
            ["Higher frequency upgrade at max level is 2% stronger"] = "L'amélioration Fréquence accrue au niveau max est 2% plus forte",
            ["Unlocks Byte numeral for blocks"] = "Débloque la notation Octet pour les blocs",
            ["Unlocks Power numeral for blocks"] = "Débloque la notation Puissance pour les blocs",
            ["Unlocks Roman numeral for blocks"] = "Débloque la notation romaine pour les blocs",
            ["Unlocks Hexadecimal numeral for blocks"] = "Débloque la notation hexadécimale pour les blocs",
            ["Unlocks Scientific numeral for blocks"] = "Débloque la notation scientifique pour les blocs",
            ["Complete its goal to unlock this numeral"] = "Accomplis son objectif pour débloquer cette notation",
            ["Consecutive merges multiply move income."] = "Les fusions consécutives multiplient le revenu par coup.",
            ["Converts part of the run's score into <sprite name=\"chips\" tint=1>."] = "Convertit une partie du score du run en <sprite name=\"chips\" tint=1>.",
            ["Held <sprite name=\"token\" tint=1> pay <sprite name=\"chips\" tint=1> times the √ of the hoard."] = "Les <sprite name=\"token\" tint=1> détenus versent des <sprite name=\"chips\" tint=1>, multipliés par la √ de la réserve.",
            ["The currency for Auto restart. Price rises the more <sprite name=\"token\" tint=1> you hold."] = "La monnaie pour le redémarrage auto. Le prix augmente avec le nombre de <sprite name=\"token\" tint=1> détenus.",
            ["Standard"] = "Standard",
            ["Byte"] = "Octet",
            ["Hexadecimal"] = "Hexadécimal",
            ["Power"] = "Puissance",
            ["Roman"] = "Romain",
            ["Scientific"] = "Scientifique",
            ["Audio"] = "Audio",
            ["Accessibility"] = "Accessibilité",
            ["Application"] = "Application",
            ["Display"] = "Affichage",
            ["Manage save files"] = "Gérer les sauvegardes",
            ["Block numerals visual"] = "Style des chiffres des blocs",
            ["How to play"] = "Comment jouer",
            ["Highest"] = "Plus haut",
            ["Highest median"] = "Médiane la plus haute",
            ["Runs"] = "Runs",
            ["Earned"] = "Gagné",
            ["Resets"] = "Resets",
            ["Playtime"] = "Temps de jeu",
            ["Solvers"] = "Solvers",
            ["Recent Score Trend"] = "Tendance récente des scores",
            ["Recent Runs"] = "Runs récents",
            ["Lifetime Stats"] = "Statistiques globales",
            ["Goals"] = "Objectifs",
            ["Prestige Summary"] = "Résumé du prestige",
            ["Average time in runs"] = "Durée moyenne des runs",
            ["Total frame"] = "Frames au total",
            ["Average frame / Prestige"] = "Frames moy. / prestige",
            ["Total runs"] = "Total des runs",
            ["Total moves"] = "Total des coups",
            ["Total merges"] = "Total des fusions",
            ["PPO knowledge"] = "Savoir de PPO",
            ["Total playtime"] = "Temps de jeu total",
            ["Merge Broker"] = "Courtier en fusions",
            ["Highwater Analyst"] = "Analyste des records",
            ["Score Auditor"] = "Auditeur de score",
            ["Overclocker"] = "Overclockeur",
            ["Quartermaster"] = "Intendant",
            ["Restart Sponsor"] = "Sponsor de redémarrage",
            ["Token Prospector"] = "Prospecteur de jetons",
            ["Move Dividend"] = "Dividende de coups",
            ["Velocity Trader"] = "Trader de vitesse",
            ["Unstable Stack"] = "Pile instable",
            ["Catalyst Stack"] = "Pile catalyseur",
            ["Mirror Stack"] = "Pile miroir",
            ["Joker"] = "Joker",
            ["Miner's Pickaxe"] = "Pioche du mineur",
            ["Queue Scrubber"] = "Nettoyeur de file",
            ["Neural Accelerator"] = "Accélérateur neuronal",
            ["Boosts merge income."] = "Augmente le revenu des fusions.",
            ["Rewards new highs."] = "Récompense les nouveaux records.",
            ["Turns score into <sprite name=\"chips\" tint=1>."] = "Transforme le score en <sprite name=\"chips\" tint=1>.",
            ["Runs the solver faster."] = "Fait tourner le solver plus vite.",
            ["Improves baseline income."] = "Améliore le revenu de base.",
            ["Keeps restarts funded."] = "Finance les redémarrages.",
            ["Turns merge volume into restart fuel."] = "Transforme le volume de fusions en carburant de redémarrage.",
            ["Rewards long, stable runs."] = "Récompense les runs longs et stables.",
            ["Rewards fast solvers."] = "Récompense les solvers rapides.",
            ["Deletes bottom blocks when a full stack would fail."] = "Supprime les blocs du bas quand une pile pleine échouerait.",
            ["Converts merges into more <sprite name=\"chips\" tint=1>."] = "Convertit les fusions en davantage de <sprite name=\"chips\" tint=1>.",
            ["Lets stack ends interact."] = "Permet aux extrémités d'une pile d'interagir.",
            ["Adds wild blocks to the queue."] = "Ajoute des blocs joker à la file.",
            ["Lets solvers remove blocks from the board."] = "Permet aux solvers de retirer des blocs du plateau.",
            ["Lets solvers delete bad upcoming blocks."] = "Permet aux solvers de supprimer les mauvais blocs à venir.",
            ["Speeds up expensive solvers."] = "Accélère les solvers coûteux.",
            ["Select an algorithm to inspect it. Locked algorithms hide detailed behavior until unlocked."] = "Choisis un algorithme pour l'inspecter. Les algorithmes verrouillés cachent leur comportement détaillé jusqu'au déblocage.",
            ["Buy automation, unlock new layers, then push into riskier systems when the run history proves you are ready."] = "Achète de l'automatisation, débloque de nouvelles couches, puis lance-toi dans des systèmes plus risqués quand l'historique prouve que tu es prêt.",
            ["Equipped Agents give various bonuses to progress faster."] = "Les agents équipés donnent divers bonus pour progresser plus vite.",
            ["Late-game rule modules. They raise the ceiling, create rescue tools, and make solver choice matter more than raw price."] = "Modules de règles de fin de partie. Ils relèvent le plafond, créent des outils de secours et rendent le choix du solver plus important que le simple prix.",
            ["They expand the game rules, allowing for further production. Each solver is effective in different ways."] = "Ils étendent les règles du jeu, permettant plus de production. Chaque solver est efficace à sa manière.",
            ["Rule-changing modules that apply to new runs and amplify the differences between solvers."] = "Modules changeant les règles, appliqués aux nouveaux runs et amplifiant les différences entre solvers.",
            ["Modifiers apply to new runs and amplify solver differences."] = "Les modificateurs s'appliquent aux nouveaux runs et amplifient les différences entre solvers.",
            ["You can track how many tasks you've completed. As you progress, you'll automatically unlock them."] = "Tu peux suivre le nombre de tâches accomplies. En progressant, tu les débloques automatiquement.",
            ["Permanent late-game research. Prestige turns PPO Normal-mode performance into Insight, then the tree makes every future reset faster and deeper."] = "Recherche permanente de fin de partie. Le prestige transforme la performance du mode normal de PPO en Insight, puis l'arbre rend chaque reset futur plus rapide et plus profond.",
            ["Permanent late-game research. The tree makes every future reset faster and deeper."] = "Recherche permanente de fin de partie. L'arbre rend chaque reset futur plus rapide et plus profond.",
            ["Research locked. Finish PPO Training, then run PPO in Normal mode."] = "Recherche verrouillée. Termine l'entraînement PPO, puis lance PPO en mode normal.",
            ["Track your recent runs and the performance of your used solvers."] = "Suis tes runs récents et la performance des solvers utilisés.",
            ["Description"] = "Description",
            ["<b>Manual controls</b>"] = "<b>Commandes manuelles</b>",
            ["Free baseline solver."] = "Solver de base gratuit.",
            ["Randomly chooses any valid stack. Weak, chaotic, but fast."] = "Choisit au hasard une pile valide. Faible, chaotique, mais rapide.",
            ["Looks for direct merges."] = "Cherche des fusions directes.",
            ["Prioritizes immediate merges and cascades before anything else."] = "Priorise les fusions immédiates et les cascades avant tout.",
            ["Keeps stacks even."] = "Garde les piles équilibrées.",
            ["Avoids tall dangerous stacks and spreads risk across the board."] = "Évite les piles hautes et dangereuses et répartit le risque sur le plateau.",
            ["Scores every legal move."] = "Note chaque coup légal.",
            ["Uses handcrafted heuristics: merge value, danger, future queue fit, and free space."] = "Utilise des heuristiques faites main : valeur de fusion, danger, adéquation future de la file et espace libre.",
            ["Plans one move deeper."] = "Planifie un coup plus loin.",
            ["Tests each move, then estimates the best follow-up move before deciding."] = "Teste chaque coup, puis estime le meilleur coup suivant avant de décider.",
            ["Runs simulations."] = "Lance des simulations.",
            ["Rolls out multiple futures, judging each by the surviving board and the peak tier it reaches."] = "Déroule plusieurs futurs, jugeant chacun par le plateau survivant et le palier maximal atteint.",
            ["Reads the visible queue."] = "Lit la file visible.",
            ["Queue planner. Searches lines through up to 3 visible next blocks before choosing."] = "Planificateur de file. Explore des lignes à travers jusqu'à 3 blocs suivants visibles avant de choisir.",
            ["Queue planner. Searches lines through the visible next blocks. Planning depth (3–5) can be tuned for patience vs practicality."] = "Planificateur de file. Explore des lignes à travers les blocs suivants visibles. La profondeur de plan (3–5) s'ajuste entre patience et pragmatisme.",
            ["Uses the extended queue."] = "Utilise la file étendue.",
            ["Deep queue planner. Searches lines through up to 5 visible next blocks. Stronger once next preview upgrades are unlocked."] = "Planificateur de file profond. Explore des lignes à travers jusqu'à 5 blocs suivants visibles. Plus fort une fois les améliorations d'aperçu débloquées.",
            ["Smarter Monte Carlo rollouts."] = "Rollouts Monte Carlo plus intelligents.",
            ["Enhanced Monte Carlo. Each rollout uses short queue planning and an anti-stall board score."] = "Monte Carlo amélioré. Chaque rollout utilise une courte planification de file et un score de plateau anti-blocage.",
            ["Builds a search tree."] = "Construit un arbre de recherche.",
            ["Monte Carlo Tree Search. Balances exploring new lines with exploiting lines that already score well."] = "Monte Carlo Tree Search. Équilibre l'exploration de nouvelles lignes et l'exploitation des lignes déjà bien notées.",
            ["Avoids dead boards."] = "Évite les plateaux morts.",
            ["Anti-stall solver. Heavily protects legal moves, semi-empty stacks, and escape routes over greedy merges."] = "Solver anti-blocage. Protège fortement les coups légaux, les piles à moitié vides et les issues face aux fusions voraces.",
            ["Sets up chain merges."] = "Prépare des fusions en chaîne.",
            ["Combo-focused solver. Reads the queue and rewards positions that can cascade over the next 2-3 turns."] = "Solver axé combo. Lit la file et récompense les positions capables de cascader sur les 2-3 tours suivants.",
            ["Endgame learner. Requires every Modifier to be fully purchased."] = "Apprenant de fin de partie. Nécessite que chaque modificateur soit entièrement acheté.",
            ["Proximal Policy Optimization is a lightweight actor-critic neural network that learns its policy from run trajectories, clipped policy updates, value estimates, and entropy-driven exploration."] = "Proximal Policy Optimization est un réseau acteur-critique léger qui apprend sa politique à partir de trajectoires de runs, de mises à jour de politique clippées, d'estimations de valeur et d'exploration guidée par l'entropie.",
            ["+75% <sprite name=\"chips\" tint=1> from merge rewards."] = "+75% de <sprite name=\"chips\" tint=1> sur les récompenses de fusion.",
            ["+200% <sprite name=\"chips\" tint=1> from new highest-block rewards."] = "+200% de <sprite name=\"chips\" tint=1> sur les récompenses de nouveau bloc record.",
            ["+200% <sprite name=\"chips\" tint=1> from end-of-run score bonus."] = "+200% de <sprite name=\"chips\" tint=1> sur le bonus de score de fin de run.",
            ["Solver move interval is 25% shorter."] = "L'intervalle de coups du solver est 25% plus court.",
            ["+10 <sprite name=\"chips\" tint=1> on every successful placement."] = "+10 <sprite name=\"chips\" tint=1> à chaque placement réussi.",
            ["Auto Restart consumes no tokens while this agent is active."] = "Le redémarrage auto ne consomme aucun jeton tant que cet agent est actif.",
            ["+1 token for every 8 merges while active."] = "+1 jeton toutes les 8 fusions tant qu'il est actif.",
            ["End-of-run <sprite name=\"chips\" tint=1> gain a bonus from total moves completed."] = "Les <sprite name=\"chips\" tint=1> de fin de run gagnent un bonus selon le total de coups joués.",
            ["End-of-run <sprite name=\"chips\" tint=1> gain a throughput bonus from moves per second."] = "Les <sprite name=\"chips\" tint=1> de fin de run gagnent un bonus de débit selon les coups par seconde.",
            ["Each level gives one rescue per run. If a full stack receives a non-merge block, its bottom block is removed without reducing score."] = "Chaque niveau donne un sauvetage par run. Si une pile pleine reçoit un bloc sans fusion, son bloc du bas est retiré sans réduire le score.",
            ["Merge rewards are permanently doubled on every run after purchase."] = "Les récompenses de fusion sont doublées en permanence à chaque run après l'achat.",
            ["Unlocks a special merge. If the top and bottom block of a stack match, they merge through the stack."] = "Débloque une fusion spéciale. Si le bloc du haut et du bas d'une pile correspondent, ils fusionnent à travers la pile.",
            ["Unlocks occasional Joker blocks. A Joker placed onto any block merges with it."] = "Débloque des blocs Joker occasionnels. Un Joker placé sur n'importe quel bloc fusionne avec lui.",
            ["Each level gives one pickaxe use per run. The solver may delete any block in any stack."] = "Chaque niveau donne une utilisation de pioche par run. Le solver peut supprimer n'importe quel bloc de n'importe quelle pile.",
            ["Each level gives one queue skip per run. The current next block is removed and the following block moves forward."] = "Chaque niveau donne un saut de file par run. Le bloc suivant actuel est retiré et le bloc d'après avance.",
            ["MOCA, MOCA+, and MCTS run permanently about twice as fast. Negative speed tuning on those solvers is also twice as effective."] = "MOCA, MOCA+ et MCTS tournent en permanence environ deux fois plus vite. Le réglage de vitesse négatif est aussi deux fois plus efficace sur ces solvers.",
            ["MOCA runs permanently about twice as fast. Negative speed tuning on it is also twice as effective."] = "MOCA tourne en permanence environ deux fois plus vite. Le réglage de vitesse négatif est aussi deux fois plus efficace.",
            ["+35% <sprite name=\"insight\" tint=1> from every future prestige per level."] = "+35% de <sprite name=\"insight\" tint=1> de chaque futur prestige par niveau.",
            ["Start after each prestige reset with <sprite name=\"chips\" tint=1> already banked. This allows making purchases right at the beginning of the game."] = "Commence après chaque reset prestige avec des <sprite name=\"chips\" tint=1> déjà en réserve. Cela permet d'acheter dès le début de la partie.",
            ["Permanently remembers automation unlocks per level after prestige: Auto Solve, Auto Restart <sprite name=\"token\" tint=1>, then Solver Tuning."] = "Mémorise en permanence un déblocage d'automatisation par niveau après le prestige : Résolution auto, Redémarrage auto <sprite name=\"token\" tint=1>, puis Réglage du solver.",
            ["Start future prestiges with early algorithms already known: BAL, HEUR, COMBO, then LOOK."] = "Commence les futurs prestiges avec des algorithmes précoces déjà connus : BAL, HEUR, COMBO, puis LOOK.",
            ["+18% <sprite name=\"chips\" tint=1> from every reward per level. It stacks with Chip Yield and stage multipliers."] = "+18% de <sprite name=\"chips\" tint=1> sur chaque récompense par niveau. Se cumule avec le rendement en chips et les multiplicateurs de phase.",
            ["+50% <sprite name=\"chips\" tint=1> from every reward per level. It stacks with Chip Yield and stage multipliers, making every future playthrough visibly faster."] = "+50% de <sprite name=\"chips\" tint=1> sur chaque récompense par niveau. Se cumule avec le rendement en chips et les multiplicateurs de phase, rendant chaque partie future nettement plus rapide.",
            ["PPO still resets every prestige, but each level lowers the trained frame requirement for Normal Mode by 8%."] = "PPO se réinitialise toujours à chaque prestige, mais chaque niveau réduit de 8% l'exigence de frames entraînés pour le mode normal.",
            ["Prestige banks 50000 PPO training frames per level. The next playthrough's PPO Training starts from that saved progress, with the knowledge already learned (instead of zero)."] = "Le prestige met en réserve 50000 frames d'entraînement PPO par niveau. L'entraînement PPO de la partie suivante repart de cette progression sauvegardée, avec le savoir déjà appris (au lieu de zéro).",
            ["Each level lowers the cycle frame requirement for PPO Normal Mode by 8%. At level 5, PPO Curriculum upgrades can be bought before PPO is unlocked and can fully automate the remaining cycle requirement."] = "Chaque niveau réduit de 8% l'exigence de frames de cycle pour le mode normal PPO. Au niveau 5, les améliorations PPO Curriculum peuvent être achetées avant le déblocage de PPO et automatiser entièrement l'exigence de cycle restante.",
            ["Prestige banks 50000 PPO cycle frames per level. The next playthrough's PPO Training starts from that saved cycle progress, while Datacenter training remains as permanent PPO knowledge."] = "Le prestige met en réserve 50000 frames de cycle PPO par niveau. L'entraînement PPO de la partie suivante repart de cette progression de cycle sauvegardée, tandis que l'entraînement du centre de données reste un savoir PPO permanent.",
            ["Prestige banks 40000 PPO cycle frames per level. The next playthrough's PPO Training starts from that saved cycle progress, while Datacenter training remains as permanent PPO knowledge."] = "Le prestige met en réserve 40000 frames de cycle PPO par niveau. L'entraînement PPO de la partie suivante repart de cette progression de cycle sauvegardée, tandis que l'entraînement du centre de données reste un savoir PPO permanent.",
            ["Raises PPO's reward signal for creating new highest blocks. This pushes the learner toward bigger blocks instead of only safer runs."] = "Augmente le signal de récompense de PPO pour la création de nouveaux blocs record. Cela pousse l'apprenant vers de plus gros blocs plutôt que vers des runs seulement plus sûrs.",
            ["Improves PPO's survival shaping and danger penalties, making high-focus policies less likely to crash early."] = "Améliore le façonnage de survie et les pénalités de danger de PPO, rendant les politiques axées record moins susceptibles de s'effondrer tôt.",
            ["+50% <sprite name=\"insight\" tint=1> from PPO Normal Mode performance per level. This is the late neural payoff node."] = "+50% de <sprite name=\"insight\" tint=1> sur la performance du mode normal PPO par niveau. C'est le nœud de gain neuronal tardif.",
            ["Boosts <sprite name=\"insight\" tint=1> earned directly from PPO Normal Mode runs. Training mode never feeds this, and long cycles softcap so prestige stays valuable."] = "Augmente l'<sprite name=\"insight\" tint=1> gagné directement des runs en mode normal PPO. Le mode entraînement ne l'alimente jamais, et les longs cycles ont un plafond souple pour que le prestige reste utile.",
            ["Offline Engine\", \"While the game is closed, <sprite name=\"chips\" tint=1> and <sprite name=\"insight\" tint=1> continue at a reduced rate based on your current prestige strength."] = "Pendant que le jeu est fermé, les <sprite name=\"chips\" tint=1> et l'<sprite name=\"insight\" tint=1> continuent à un rythme réduit selon ta force de prestige actuelle.",
            ["Extends how many closed-game hours can be converted into offline <sprite name=\"chips\" tint=1> and <sprite name=\"insight\" tint=1>."] = "Augmente le nombre d'heures hors-ligne convertibles en <sprite name=\"chips\" tint=1> et <sprite name=\"insight\" tint=1> hors-ligne.",
            ["Every hired Agent's bonus effect is 40% stronger per level. Agents become a core engine of faster replays."] = "L'effet bonus de chaque agent embauché est 40% plus fort par niveau. Les agents deviennent un moteur central de parties plus rapides.",
            ["Upgrades, Agents and Modifiers cost 5% less per level, and the Modifiers requirement needs 15% fewer runs & merges per level. At level 5, Datacenter costs are 20% cheaper."] = "Les améliorations, agents et modificateurs coûtent 5% moins cher par niveau, et l'exigence des modificateurs demande 15% de runs et fusions en moins par niveau. Au niveau 5, les coûts du centre de données sont 20% moins chers.",
            ["Shortens the result-evaluation pause after every PPO Training run by 15% per level, so Training mode gets through its runs much faster."] = "Raccourcit la pause d'évaluation des résultats après chaque run d'entraînement PPO de 15% par niveau, si bien que le mode entraînement enchaîne ses runs bien plus vite.",
            ["Unlock PPO to begin the prestige layer."] = "Débloque PPO pour commencer la couche de prestige.",
            ["Prestige for"] = "Récompense de prestige :",
            ["You can keep playing PPO in Playing Mode to increase <sprite name=\"insight\" tint=1>."] = "Tu peux continuer à jouer PPO en mode Jeu pour augmenter l'<sprite name=\"insight\" tint=1>.",
            ["Current effect"] = "Effet actuel",
            ["Game"] = "Jeu",
            ["Gameplay"] = "Gameplay",
            ["Selected"] = "Sélectionné",
            ["Deselected"] = "Désélectionné",
            ["Needs modifiers"] = "Nécessite des modificateurs",
            ["Needs all\nModifiers"] = "Nécessite tous\nles modificateurs",
            ["Unlock\nUpgrades"] = "Débloquer dans\nles améliorations",
            ["Unlock this algorithm to reveal details."] = "Débloque cet algorithme pour révéler les détails.",
            ["Agents\nLocked"] = "Agents\nVerrouillés",
            ["Unlock in\nUpgrades"] = "Débloquer dans\nles améliorations",
            ["Bonus slot\nNeeds upgrade"] = "Slot bonus\nNécessite une amélioration",
            ["Agents Locked"] = "Agents verrouillés",
            ["Unlock the Agents menu in Upgrades."] = "Débloque le menu Agents dans les améliorations.",
            ["Equipped"] = "Équipé",
            ["No free slot"] = "Aucun slot libre",
            ["Unequip someone first"] = "Retire d'abord quelqu'un",
            ["Needs upgrade"] = "Nécessite une amélioration",
            ["Empty"] = "Vide",
            ["Modifier Lab Locked"] = "Labo de modificateurs verrouillé",
            ["Reach the stage goal in Upgrades to unlock board modifiers. They make runs richer, riskier, and much harder to play optimally by hand."] = "Atteins l'objectif de phase dans les améliorations pour débloquer les modificateurs de plateau. Ils rendent les runs plus riches, plus risqués et bien plus durs à jouer parfaitement à la main.",
            ["Not active"] = "Non actif",
            ["Activate"] = "Activer",
            ["Upgrade"] = "Améliorer",
            ["Ready: every Modifier is fully purchased."] = "Prêt : chaque modificateur est entièrement acheté.",
            ["PPO model is not initialized yet."] = "Le modèle PPO n'est pas encore initialisé.",
            ["Prestige once to open Research."] = "Fais un prestige pour ouvrir la recherche.",
            ["Research maxed."] = "Recherche au maximum.",
            ["Not enough Insight."] = "Pas assez d'Insight.",
            ["Not enough <sprite name=\"insight\" tint=1>."] = "Pas assez d'<sprite name=\"insight\" tint=1>.",
            ["Requires Seed Capital L1."] = "Nécessite Capital de départ N1.",
            ["Requires Automation Memory L1."] = "Nécessite Mémoire d'automatisation N1.",
            ["Requires Algorithm Archive L1."] = "Nécessite Archive d'algorithmes N1.",
            ["Requires Agent Synergy L1."] = "Nécessite Synergie d'agents N1.",
            ["Requires Bulk Discount L1."] = "Nécessite Remise en gros N1.",
            ["Requires PPO Bootcamp L1."] = "Nécessite PPO Bootcamp N1.",
            ["Requires Evaluation Efficiency L1."] = "Nécessite Efficacité d'évaluation N1.",
            ["Requires PPO Memory L1."] = "Nécessite Mémoire PPO N1.",
            ["Requires High Focus L1."] = "Nécessite Haute concentration N1.",
            ["Requires Stability Model L1."] = "Nécessite Modèle de stabilité N1.",
            ["Requires Insight Amplifier L1."] = "Nécessite Amplificateur d'Insight N1.",
            ["Requires Passive Insight L1."] = "Nécessite Insight passif N1.",
            ["Requires Offline Engine L1."] = "Nécessite Moteur hors-ligne N1.",
            ["Ready to buy."] = "Prêt à l'achat.",
            ["Not enough chips"] = "Pas assez de chips",
            ["PPO requires every Modifier maxed"] = "PPO nécessite chaque modificateur au maximum",
            ["Unlock Agents first"] = "Débloque d'abord les agents",
            ["Modifier Lab requirements not met"] = "Conditions du labo de modificateurs non remplies",
            ["Run PPO in Normal mode first"] = "Lance d'abord PPO en mode normal",
            ["Agents menu unlocked"] = "Menu Agents débloqué",
            ["Agent unavailable"] = "Agent indisponible",
            ["No free agent slot"] = "Aucun slot d'agent libre",
            ["Speed level"] = "Niveau de vitesse",
            ["Risk level"] = "Niveau de risque",
            ["Chip yield level"] = "Niveau de rendement en chips",
            ["Next preview"] = "Aperçu suivant",
            ["Scaling frequency upgrade unavailable"] = "Amélioration de fréquence de montée indisponible",
            ["Profitable ending upgrade unavailable"] = "Amélioration de fin rentable indisponible",
            ["Modifier upgrade unavailable"] = "Amélioration de modificateur indisponible",
            ["<b>Auto Buy</b>"] = "<b>Auto-Achat</b>",
            ["Auto Buy"] = "Auto-Achat",
            ["Enabled"] = "Activé",
            ["Disabled"] = "Désactivé",
            ["FPS --"] = "FPS --",
            ["Policy loss"] = "Perte de politique",
            ["Policy loss:"] = "Perte de politique :",
            ["Value loss"] = "Perte de valeur",
            ["Value loss:"] = "Perte de valeur :",
            ["Entropy"] = "Entropie",
            ["Entropy:"] = "Entropie :",
            ["Updates"] = "Mises à jour",
            ["Updates:"] = "Mises à jour :",
            ["PPO is trained, prestige reset unlocked."] = "PPO est entraîné, reset prestige débloqué.",
            ["Gain:"] = "Gain :",
            ["You made"] = "Tu as gagné",
            ["while you were offline."] = "pendant que tu étais hors-ligne.",
            ["Offline reward time:"] = "Durée de récompense hors-ligne :",
            ["You have to finish PPO Training to unlock prestige."] = "Tu dois terminer l'entraînement PPO pour débloquer le prestige.",
            ["In case of a Prestige reset, the game will restart. All <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, upgrades, Agents, and Modifiers will be lost.\n\n" +
                "However, existing <sprite name=\"insight\" tint=1> and purchased research will remain, which will make further resets progressively more valuable.\n\n" +
                "<b>It is recommended to use PPO in Normal Mode before resetting to gain <sprite name=\"insight\" tint=1> multiplier.</b>"] =
            "En cas de reset prestige, la partie redémarre. Tous les <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, améliorations, agents et modificateurs seront perdus.\n\n" +
            "Cependant, l'<sprite name=\"insight\" tint=1> existant et les recherches achetées seront conservés, rendant les resets suivants progressivement plus précieux.\n\n" +
            "<b>Il est recommandé d'utiliser PPO en mode normal avant de reset pour augmenter le multiplicateur d'<sprite name=\"insight\" tint=1>.</b>",
            ["Reset for"] = "Récompense de reset :",
            ["Datacenter"] = "Centre de données",
            ["Compute Allocation"] = "Allocation de calcul",
            ["Server Racks"] = "Racks de serveurs",
            ["Facility Upgrades"] = "Améliorations d'installation",
            ["CPU Rack"] = "Rack CPU",
            ["GPU Rack"] = "Rack GPU",
            ["TPU Pod"] = "Pod TPU",
            ["Neural Fabric"] = "Neural Fabric",
            ["Power Grid"] = "Réseau électrique",
            ["Cooling Loop"] = "Circuit de refroidissement",
            ["Fabric Interconnect"] = "Interconnexion Fabric",
            ["Commodity silicon. Cheap, dependable, slow."] = "Silicium standard. Bon marché, fiable, lent.",
            ["Parallel throughput for tensor math."] = "Débit parallèle pour le calcul tensoriel.",
            ["Tensor pods. Systolic arrays with obscene throughput."] = "Pods tensoriels. Réseaux systoliques au débit obscène.",
            ["Experimental wafer-scale mesh. Draws its own weather."] = "Maillage expérimental à l'échelle du wafer. Génère sa propre météo.",
            ["Dedicated feeders and battery buffer."] = "Alimentations dédiées et tampon batterie.",
            ["Immersion + rear-door heat exchangers."] = "Immersion et échangeurs de chaleur en porte arrière.",
            ["Low-latency mesh between pods."] = "Maillage à faible latence entre les pods.",
            ["Total compute"] = "Calcul total",
            ["allocated"] = "alloué",
            ["units"] = "unités",
            ["unit"] = "unité",
            ["total"] = "total",
            ["Training Cluster"] = "Cluster d'entraînement",
            ["Analysis Node"] = "Nœud d'analyse",
            ["Market Bots"] = "Bots de marché",
            ["Passive PPO frame. Shortens the prestige cycle."] = "Frames PPO passives. Raccourcit le cycle de prestige.",
            ["Passively generates <sprite name=\"insight\" tint=1> (softcapped)."] = "Génère passivement de l'<sprite name=\"insight\" tint=1> (plafond souple).",
            ["Producing <sprite name=\"chips\" tint=1> gets an income multiplier."] = "La production de <sprite name=\"chips\" tint=1> reçoit un multiplicateur de revenu.",
            ["Requires every Modifier maxed"] = "Nécessite chaque modificateur au maximum",
            ["Agent bonuses"] = "Bonus d'agents",
            ["Shop prices"] = "Prix de la boutique",
            ["Training eval pause"] = "Pause d'évaluation d'entraînement",
            ["Prestige Insight"] = "Insight de prestige",
            ["Start chips"] = "Chips de départ",
            ["Chip rewards"] = "Récompenses en chips",
            ["No automation is remembered yet."] = "Aucune automatisation mémorisée pour l'instant.",
            ["Auto Solve unlock remembered."] = "Déblocage de Résolution auto mémorisé.",
            ["Auto Restart unlock and 50 tokens remembered."] = "Déblocage de Redémarrage auto et 50 jetons mémorisés.",
            ["Auto Solve, Auto Restart, tokens, and Solver Tuning remembered."] = "Résolution auto, Redémarrage auto, jetons et Réglage du solver mémorisés.",
            ["No algorithms remembered yet."] = "Aucun algorithme mémorisé pour l'instant.",
            ["Start with RAND."] = "Commence avec RAND.",
            ["Start with RAND and MERG."] = "Commence avec RAND et MERG.",
            ["Start with RAND, MERG, and BAL."] = "Commence avec RAND, MERG et BAL.",
            ["Start with RAND, MERG, BAL, and HEUR."] = "Commence avec RAND, MERG, BAL et HEUR.",
            ["Insight Amplifier"] = "Amplificateur d'Insight",
            ["Seed Capital"] = "Capital de départ",
            ["Automation Memory"] = "Mémoire d'automatisation",
            ["Algorithm Archive"] = "Archive d'algorithmes",
            ["Yield Theory"] = "Théorie du rendement",
            ["PPO Bootcamp"] = "PPO Bootcamp",
            ["PPO Memory"] = "Mémoire PPO",
            ["High Focus"] = "Haute concentration",
            ["Stability Model"] = "Modèle de stabilité",
            ["Insight Extractor"] = "Extracteur d'Insight",
            ["Passive Insight"] = "Insight passif",
            ["Offline Engine"] = "Moteur hors-ligne",
            ["Offline Buffer"] = "Tampon hors-ligne",
            ["Agent Synergy"] = "Synergie d'agents",
            ["Bulk Discount"] = "Remise en gros",
            ["Evaluation Efficiency"] = "Efficacité d'évaluation",
            ["Insight"] = "Insight",
            ["RAND selected"] = "RAND sélectionné",
            ["RAND deselected"] = "RAND désélectionné",
            ["BAL selected"] = "BAL sélectionné",
            ["BAL deselected"] = "BAL désélectionné",
            ["BAL tuning updated"] = "Réglage de BAL mis à jour",
            ["BAL tuning reset"] = "Réglage de BAL réinitialisé",
            ["HEUR selected"] = "HEUR sélectionné",
            ["HEUR deselected"] = "HEUR désélectionné",
            ["HEUR tuning updated"] = "Réglage de HEUR mis à jour",
            ["HEUR tuning reset"] = "Réglage de HEUR réinitialisé",
            ["COMBO selected"] = "COMBO sélectionné",
            ["COMBO deselected"] = "COMBO désélectionné",
            ["COMBO tuning updated"] = "Réglage de COMBO mis à jour",
            ["COMBO tuning reset"] = "Réglage de COMBO réinitialisé",
            ["LOOK selected"] = "LOOK sélectionné",
            ["LOOK deselected"] = "LOOK désélectionné",
            ["LOOK tuning updated"] = "Réglage de LOOK mis à jour",
            ["LOOK tuning reset"] = "Réglage de LOOK réinitialisé",
            ["MOCA selected"] = "MOCA sélectionné",
            ["MOCA deselected"] = "MOCA désélectionné",
            ["MOCA tuning updated"] = "Réglage de MOCA mis à jour",
            ["MOCA tuning reset"] = "Réglage de MOCA réinitialisé",
            ["PLAN selected"] = "PLAN sélectionné",
            ["PLAN deselected"] = "PLAN désélectionné",
            ["PLAN tuning updated"] = "Réglage de PLAN mis à jour",
            ["PLAN tuning reset"] = "Réglage de PLAN réinitialisé",
            ["Export"] = "Exporter",
            ["Import"] = "Importer",
            ["To import your game data, paste in your export text.\n\n" +
                "Importing will overwrite all progress in all of your saves, and it will not be possible to recover old progress."] =
            "Pour importer tes données de jeu, colle ton texte d'export.\n\n" +
            "L'import écrasera toute la progression de toutes tes sauvegardes, et il sera impossible de récupérer l'ancienne progression.",

            // ---- How To Play + menu help ---------------------------------------------------------
            ["This part of the game is still locked. Keep progressing to reveal this help section."] = "Cette partie du jeu est encore verrouillée. Continue de progresser pour révéler cette section d'aide.",
            ["Welcome!"] = "Bienvenue !",
            ["Basics"] = "Bases",
            ["Purpose"] = "But",
            ["Priorities"] = "Priorités",
            ["Tip"] = "Astuce",
            ["Usage"] = "Utilisation",
            ["Reward rules"] = "Règles de récompense",
            ["Income formula"] = "Formule de revenu",
            ["Speed formula"] = "Formule de vitesse",
            ["Synergy formula"] = "Formule de synergie",
            ["Main formula"] = "Formule principale",
            ["Allocations"] = "Allocations",
            ["Allocation formulas"] = "Formules d'allocation",
            ["Main multipliers"] = "Multiplicateurs principaux",
            ["Layer progression"] = "Progression des couches",
            ["Prestige Reset"] = "Reset prestige",
            ["PPO"] = "PPO",
            ["<sprite name=\"insight\" tint=1> reward formula"] = "Formule de récompense d'<sprite name=\"insight\" tint=1>",
            ["General:\n" +
                    "<b>moveInterval = max(minInterval, speedInterval x solverPacing x computePacing x agentPacing x trainingPacing)</b>\n\n" +
                    "For heavy search solvers:\n" +
                    "<b>computePacing = max(0.35, 1 - 0.11 x ComputeSpeedLevel)</b>"] =
                "Général :\n" +
                "<b>moveInterval = max(minInterval, speedInterval x solverPacing x computePacing x agentPacing x trainingPacing)</b>\n\n" +
                "Pour les solvers à recherche lourde :\n" +
                "<b>computePacing = max(0.35, 1 - 0.11 x ComputeSpeedLevel)</b>",
            ["Catalyst Stack doubles merge rewards.\n\n" +
                    "<b>salvage = ceil(score x salvageShare x 0.25) x stage x globalIncome</b>\n\n" +
                    "Because runs become longer and more flexible, planning solvers and PPO also become more valuable."] =
                "Catalyst Stack double les récompenses de fusion.\n\n" +
                "<b>salvage = ceil(score x salvageShare x 0.25) x stage x globalIncome</b>\n\n" +
                "Comme les runs deviennent plus longs et plus flexibles, les solvers planificateurs et PPO gagnent aussi en valeur.",
            ["<b><sprite name=\"insight\" tint=1> ~= round((1 + performance x 1.25 + cycleCarry) x usage x insightMultiplier)</b>\n\n" +
                    "Performance is based on PPO score and highest block. Usage comes from Normal Mode runs and frames."] =
                "<b><sprite name=\"insight\" tint=1> ~= round((1 + performance x 1.25 + cycleCarry) x usage x insightMultiplier)</b>\n\n" +
                "La performance dépend du score PPO et du bloc le plus élevé. L'usage vient des runs et des frames en mode normal.",

            ["The core gameplay is very simple. Place blocks into one of the four stacks.\n\n" +
                    "You can merge two blocks of the same value by placing one on top of the other, earning more score and a larger in-game currency reward <sprite name=\"chips\" tint=1>.\n\n" +
                    "Always make sure there is at least one free space available, and try to keep your runs going for as long as possible. A run ends when the next block can no longer be placed anywhere."] =
                "Le cœur du jeu est très simple. Place des blocs dans l'une des quatre piles.\n\n" +
                "Tu peux fusionner deux blocs de même valeur en posant l'un sur l'autre, gagnant plus de score et une plus grande récompense en monnaie du jeu <sprite name=\"chips\" tint=1>.\n\n" +
                "Veille à toujours garder au moins un espace libre, et essaie de faire durer tes runs le plus longtemps possible. Un run se termine quand le bloc suivant ne peut plus être placé nulle part.",
            ["The gameplay changes early on, when algorithms begin playing instead of you. From that point forward, your job is to spend your income on upgrades that make future runs faster, longer, and more valuable."] =
                "Le jeu change tôt, quand les algorithmes commencent à jouer à ta place. Dès lors, ton rôle est de dépenser ton revenu en améliorations qui rendent les runs futurs plus rapides, plus longs et plus précieux.",
            ["The stage multiplier starts at 1x, increases to 5x after unlocking Agents, and reaches 24x after unlocking Modifiers. Because of this, unlocking a new layer is usually more valuable than buying another standard income upgrade."] =
                "Le multiplicateur de phase commence à 1x, passe à 5x après le déblocage des agents, et atteint 24x après le déblocage des modificateurs. C'est pourquoi débloquer une nouvelle couche vaut souvent mieux qu'une amélioration de revenu standard supplémentaire.",
            ["Algorithms (solvers) automatically play the game for you.\n\n" +
                    "When Auto Solve is enabled, the selected solver places the blocks. If no solver is selected, the run remains Manual."] =
                "Les algorithmes (solvers) jouent automatiquement à ta place.\n\n" +
                "Quand la Résolution auto est activée, le solver choisi place les blocs. Si aucun solver n'est choisi, le run reste manuel.",
            ["Each solver prioritizes different values when making decisions, so comparing them is worthwhile.\n\n" +
                    "Their behavior can be adjusted after unlocking Tuning. Tuning parameters can be modified using sliders, but their effects may also negatively impact gameplay.\n\n" +
                    "Besides search depth, the biggest difference between solvers is their speed. Solver speed can be upgraded in several places throughout the game."] =
                "Chaque solver priorise des valeurs différentes dans ses décisions, il vaut donc la peine de les comparer.\n\n" +
                "Leur comportement s'ajuste après le déblocage du réglage. Les paramètres se modifient avec des curseurs, mais leurs effets peuvent aussi nuire au jeu.\n\n" +
                "Outre la profondeur de recherche, la plus grande différence entre solvers est leur vitesse. La vitesse du solver s'améliore à plusieurs endroits du jeu.",
            ["The ultimate goal is to unlock PPO, which is a learning algorithm. It starts out weak because it doesn't understand the game's rules, so it must first be trained in Training Mode.\n\n" +
                    "Later, it becomes the gateway to Prestige and permanent progression.\n\n" +
                    "<b>The requirements to unlock it only become achievable later in the game.</b>"] =
                "Le but ultime est de débloquer PPO, un algorithme d'apprentissage. Il commence faible car il ne comprend pas les règles du jeu, il doit donc d'abord être entraîné en mode entraînement.\n\n" +
                "Plus tard, il devient la porte vers le prestige et la progression permanente.\n\n" +
                "<b>Les conditions pour le débloquer ne deviennent atteignables que plus tard dans le jeu.</b>",
            ["This is the primary place to spend <sprite name=\"chips\" tint=1> during the early game.\n\n" +
                    "Here you unlock automation, speed up and expand gameplay, and increase your income generation.\n\n" +
                    "<b>Some upgrades have little impact on their own but become much stronger when combined with others.</b>"] =
                "C'est le principal endroit où dépenser tes <sprite name=\"chips\" tint=1> en début de partie.\n\n" +
                "Ici tu débloques l'automatisation, accélères et étends le jeu, et augmentes ta génération de revenu.\n\n" +
                "<b>Certaines améliorations ont peu d'impact seules mais deviennent bien plus fortes combinées à d'autres.</b>",
            ["It's recommended to purchase automation upgrades first so you can start focusing on management as soon as possible."] =
                "Il est recommandé d'acheter d'abord les améliorations d'automatisation pour te concentrer sur la gestion au plus tôt.",
            ["<b>Keep in mind that Auto Restart consumes <sprite name=\"token\" tint=1>, and cannot function without it.</b>"] =
                "<b>N'oublie pas que le redémarrage auto consomme des <sprite name=\"token\" tint=1> et ne peut pas fonctionner sans eux.</b>",
            ["<b>Unlocking Agents increases the game to a 5x stage multiplier.</b>"] =
                "<b>Débloquer les agents fait passer le multiplicateur de phase à 5x.</b>",
            ["Agents provide active loadout bonuses.\n\n" +
                    "Simply purchasing an Agent isn't enough to make it available, it must also be selected. By default, you can equip two Agents at once, and this limit can be increased through upgrades."] =
                "Les agents fournissent des bonus de loadout actifs.\n\n" +
                "Acheter un agent ne suffit pas à le rendre disponible, il faut aussi le sélectionner. Par défaut, tu peux équiper deux agents à la fois, et cette limite s'augmente via des améliorations.",
            ["<b>The combination of equipped Agents determines which aspect of a run becomes more efficient, since most Agents improve a specific reward source instead of multiplying the entire economy.</b>"] =
                "<b>La combinaison d'agents équipés détermine quel aspect d'un run devient plus efficace, car la plupart des agents améliorent une source de récompense précise au lieu de multiplier toute l'économie.</b>",
            ["Some Agents have little effect on their own, but become significantly stronger when combined with other Agents and upgrades."] =
                "Certains agents ont peu d'effet seuls, mais deviennent bien plus forts combinés à d'autres agents et améliorations.",
            ["Choose Agents based on what's currently limiting your progress. If runs end too quickly, prioritize stability. Once your runs are long enough, score, high-block, or merge rewards become more valuable."] =
                "Choisis tes agents selon ce qui limite ta progression. Si les runs finissent trop vite, privilégie la stabilité. Quand tes runs sont assez longs, les récompenses de score, de bloc élevé ou de fusion gagnent en valeur.",
            ["<b>Unlocking Modifiers increases the game to a 24x stage multiplier.</b>"] =
                "<b>Débloquer les modificateurs fait passer le multiplicateur de phase à 24x.</b>",
            ["Modifiers change the rules of future runs. They provide a higher ceiling, a more flexible board, and more tools for advanced solvers to take advantage of."] =
                "Les modificateurs changent les règles des runs futurs. Ils offrent un plafond plus haut, un plateau plus flexible et plus d'outils que les solvers avancés peuvent exploiter.",
            ["Some Modifiers grant actions that can be freely used during gameplay. Every Modifier can also be used in Manual Mode."] =
                "Certains modificateurs accordent des actions librement utilisables en jeu. Chaque modificateur peut aussi être utilisé en mode manuel.",
            ["Research is responsible for speeding up and deepening future playthroughs, and it is also where Prestige Reset becomes available.\n\n" +
                    "Here you can purchase permanent upgrades that make gameplay easier, but they require <sprite name=\"insight\" tint=1>.\n\n"] =
                "La recherche sert à accélérer et approfondir les parties futures, et c'est aussi là que le reset prestige devient disponible.\n\n" +
                "Ici tu peux acheter des améliorations permanentes qui facilitent le jeu, mais elles nécessitent de l'<sprite name=\"insight\" tint=1>.\n\n",
            ["<sprite name=\"insight\" tint=1> is generated by letting PPO play in Normal Mode.\n\n" +
                    "<b>You must perform a Prestige Reset to claim your <sprite name=\"insight\" tint=1>.</b>"] =
                "L'<sprite name=\"insight\" tint=1> est généré en laissant PPO jouer en mode normal.\n\n" +
                "<b>Tu dois effectuer un reset prestige pour récupérer ton <sprite name=\"insight\" tint=1>.</b>",
            ["A Prestige Reset removes all accumulated <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, Upgrades, Agents, and Modifiers.\n\n" +
                    "However, your <sprite name=\"insight\" tint=1>, purchased Research, permanent PPO knowledge, and Datacenter progress are preserved."] =
                "Un reset prestige supprime tous les <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, améliorations, agents et modificateurs accumulés.\n\n" +
                "En revanche, ton <sprite name=\"insight\" tint=1>, la recherche achetée, le savoir PPO permanent et la progression du centre de données sont conservés.",
            ["Datacenter is a permanent compute layer that unlocks after your 5th Prestige Reset.\n\n" +
                    "Every upgrade here accelerates different stages of gameplay.\n\n" +
                    "This layer uses <sprite name=\"chips\" tint=1> as its currency again, meaning the production accumulated by PPO in Normal Mode is no longer lost after Prestige Reset."] =
                "Le centre de données est une couche de calcul permanente débloquée après ton 5e reset prestige.\n\n" +
                "Chaque amélioration ici accélère différentes phases du jeu.\n\n" +
                "Cette couche utilise à nouveau les <sprite name=\"chips\" tint=1> comme monnaie, si bien que la production accumulée par PPO en mode normal n'est plus perdue après un reset prestige.",
            ["<b>Be sure to spend your accumulated <sprite name=\"chips\" tint=1> before performing a Prestige Reset, otherwise they will be lost.</b>"] =
                "<b>Pense à dépenser tes <sprite name=\"chips\" tint=1> accumulés avant un reset prestige, sinon ils seront perdus.</b>",
            ["You can purchase Server Racks and Facility Upgrades, then allocate the resulting compute capacity however you like between passive PPO training, passive <sprite name=\"insight\" tint=1> generation, or a <sprite name=\"chips\" tint=1> income multiplier."] =
                "Tu peux acheter des racks de serveurs et des améliorations d'installation, puis répartir la capacité de calcul obtenue comme tu veux entre entraînement PPO passif, génération passive d'<sprite name=\"insight\" tint=1> ou multiplicateur de revenu en <sprite name=\"chips\" tint=1>.",

            ["Place the blocks into one of the four stacks.\n\n" +
                "By placing two blocks with the same value on top of each other, you can merge them, earning more score and receiving a larger in-game currency <sprite name=\"chips\" tint=1> reward.\n\n" +
                "Make sure to always keep at least one free space available, and try to make your runs last as long as possible.\n\n" +
                "The gameplay changes early on, when algorithms start playing instead of you. From that point onward, your role is to purchase various upgrades and manage them.\n\n" +
                "<b>You can find details about every important game feature in Settings > How to Play menu.</b>"] =
                "Place les blocs dans l'une des quatre piles.\n\n" +
                "En posant deux blocs de même valeur l'un sur l'autre, tu les fusionnes, gagnant plus de score et une plus grande récompense en monnaie du jeu <sprite name=\"chips\" tint=1>.\n\n" +
                "Garde toujours au moins un espace libre, et essaie de faire durer tes runs le plus longtemps possible.\n\n" +
                "Le jeu change tôt, quand les algorithmes commencent à jouer à ta place. Dès lors, ton rôle est d'acheter diverses améliorations et de les gérer.\n\n" +
                "<b>Tu trouveras des détails sur chaque fonction importante dans Paramètres > Comment jouer.</b>",
            ["Algorithms are responsible for playing the game automatically for you.\n\n" +
                "Each solver prioritizes different values when making decisions, so it's worth comparing them. Their behavior can be tuned once Tuning is unlocked.\n\n" +
                "The ultimate goal is to unlock PPO, which is a learning algorithm. The requirements for unlocking it can only be met later in the game."] =
                "Les algorithmes jouent au jeu automatiquement à ta place.\n\n" +
                "Chaque solver priorise des valeurs différentes dans ses décisions, il vaut donc la peine de les comparer. Leur comportement se règle une fois le réglage débloqué.\n\n" +
                "Le but ultime est de débloquer PPO, un algorithme d'apprentissage. Ses conditions de déblocage ne peuvent être remplies que plus tard dans le jeu.",
            ["Upgrades are the early-game progression layer based on <sprite name=\"chips\" tint=1>.\n\n" +
                "This is where you unlock automation, speed up and expand gameplay, and increase your income generation.\n\n" +
                "It's generally best to prioritize automation upgrades so you can focus on managing your run as early as possible.\n\n" +
                "<b>Keep in mind that Auto Restart consumes <sprite name=\"token\" tint=1>.</b>"] =
                "Les améliorations sont la couche de progression du début de partie basée sur les <sprite name=\"chips\" tint=1>.\n\n" +
                "C'est ici que tu débloques l'automatisation, accélères et étends le jeu, et augmentes ta génération de revenu.\n\n" +
                "Il vaut généralement mieux privilégier les améliorations d'automatisation pour te concentrer sur la gestion de ton run au plus tôt.\n\n" +
                "<b>N'oublie pas que le redémarrage auto consomme des <sprite name=\"token\" tint=1>.</b>",
            ["Agents provide active loadout bonuses.\n\n" +
                "Not every owned Agent is active: the combination equipped in your slots determines which aspects of your run become more effective."] =
                "Les agents fournissent des bonus de loadout actifs.\n\n" +
                "Tous les agents possédés ne sont pas actifs : la combinaison équipée dans tes slots détermine quels aspects de ton run deviennent plus efficaces.",
            ["Modifiers change the rules of future runs. They unlock new possibilities and increase your income, but they also make the board more complex.\n\n" +
                "Some Modifiers can be upgraded multiple times.\n\n" +
                "<b>Purchasing every Modifier unlocks the PPO algorithm, marking the gateway to the endgame.</b>"] =
                "Les modificateurs changent les règles des runs futurs. Ils ouvrent de nouvelles possibilités et augmentent ton revenu, mais rendent aussi le plateau plus complexe.\n\n" +
                "Certains modificateurs peuvent être améliorés plusieurs fois.\n\n" +
                "<b>Acheter chaque modificateur débloque l'algorithme PPO, la porte vers la fin de partie.</b>",
            ["Research is the progression layer that unlocks the ability to Prestige Reset.\n\n" +
                "Here, you can purchase permanent upgrades that make gameplay easier and faster, but they require <sprite name=\"insight\" tint=1>.\n\n" +
                "<sprite name=\"insight\" tint=1> is generated by running the PPO algorithm in Normal Mode.\n\n" +
                "To claim your <sprite name=\"insight\" tint=1>, you must perform a Prestige Reset. You can find details in the Console."] =
                "La recherche est la couche de progression qui débloque le reset prestige.\n\n" +
                "Ici, tu peux acheter des améliorations permanentes qui rendent le jeu plus facile et plus rapide, mais elles nécessitent de l'<sprite name=\"insight\" tint=1>.\n\n" +
                "L'<sprite name=\"insight\" tint=1> est généré en faisant tourner l'algorithme PPO en mode normal.\n\n" +
                "Pour récupérer ton <sprite name=\"insight\" tint=1>, tu dois effectuer un reset prestige. Tu trouveras des détails dans la Console.",
            ["Datacenter is a persistent compute layer that speeds up your Prestiges.\n\n" +
                "Here, <sprite name=\"chips\" tint=1> becomes the currency again, meaning the production accumulated in PPO Normal Mode is no longer wasted when you perform a Prestige Reset.\n\n" +
                "<b>Be sure to spend your accumulated <sprite name=\"chips\" tint=1> before resetting, as any unspent amount will be lost.</b>\n\n" +
                "You can purchase Server Racks and Facility Upgrades, then allocate the resulting compute capacity however you like: to passive PPO training, passive <sprite name=\"insight\" tint=1> generation, or a <sprite name=\"chips\" tint=1> production multiplier."] =
                "Le centre de données est une couche de calcul persistante qui accélère tes prestiges.\n\n" +
                "Ici, les <sprite name=\"chips\" tint=1> redeviennent la monnaie, si bien que la production accumulée en mode normal PPO n'est plus gaspillée lors d'un reset prestige.\n\n" +
                "<b>Pense à dépenser tes <sprite name=\"chips\" tint=1> accumulés avant de reset, car tout montant non dépensé sera perdu.</b>\n\n" +
                "Tu peux acheter des racks de serveurs et des améliorations d'installation, puis répartir la capacité de calcul obtenue comme tu veux : entraînement PPO passif, génération passive d'<sprite name=\"insight\" tint=1> ou multiplicateur de production de <sprite name=\"chips\" tint=1>.",
            ["Here you can see detailed data on how your runs perform during the current Prestige cycle.\n\n" +
                "You can view your highest score, best median performance, average run duration, and results for each solver.\n\n" +
                "<b>Measure how a new algorithm, Tuning, or any other modification affects your performance.</b>"] =
                "Ici tu vois des données détaillées sur les performances de tes runs pendant le cycle de prestige actuel.\n\n" +
                "Tu peux voir ton meilleur score, la meilleure performance médiane, la durée moyenne des runs et les résultats de chaque solver.\n\n" +
                "<b>Mesure comment un nouvel algorithme, un réglage ou toute autre modification affecte tes performances.</b>",
            ["Here you can track your best results achieved throughout your playtime, along with a summary of your overall progress. You can also see which goals you have already completed.\n\n" +
                "<b>Some milestones grant permanent rewards or cosmetic unlocks.</b>"] =
                "Ici tu peux suivre tes meilleurs résultats obtenus au fil de ton temps de jeu, avec un résumé de ta progression globale. Tu vois aussi quels objectifs tu as déjà accomplis.\n\n" +
                "<b>Certains jalons accordent des récompenses permanentes ou des déblocages cosmétiques.</b>",

            // ---- Dynamically-composed labels + datacenter allocation bodies ----------------------
            ["reach Prestige"] = "atteins Prestige",
            ["rack FLOPS"] = "FLOPS de rack",
            ["TPU / Fabric"] = "TPU / Fabric",
            ["Effect"] = "Effet",
            ["Level"] = "Niveau",
            ["Completed goals"] = "Objectifs accomplis",
            ["Best run"] = "Meilleur run",
            ["moves"] = "coups",
            ["manual"] = "manuel",
            ["Restart in"] = "Redémarrage dans",
            ["Equipped Agents"] = "Agents équipés",
            ["Active Modifiers"] = "Modificateurs actifs",
            ["Buy all Facility Upgrades"] = "Achète toutes les améliorations d'installation",
            ["Offline cap"] = "Plafond hors-ligne",
            ["Offline efficiency"] = "Efficacité hors-ligne",
            ["New-high learning"] = "Apprentissage record",
            ["Survival shaping"] = "Façonnage de survie",
            ["PPO Normal mode at"] = "Mode normal PPO à",
            ["Start with"] = "Commence avec",
            ["cycle frames"] = "frames de cycle",
            ["frames retained"] = "frames conservés",
            ["training: +0 chips"] = "entraînement : +0 chips",
            ["Pickaxe"] = "Pioche",
            ["Scrubbed"] = "Supprimé",
            ["Merge"] = "Fusion",
            ["Combo"] = "Combo",
            ["Spent"] = "Dépensé",
            ["Passively trains PPO, which counts as Training Mode frames. <b>PPO learns permanently even when not in use.</b>"] =
                "Entraîne PPO passivement, ce qui compte comme des frames de mode entraînement. <b>PPO apprend en permanence, même inutilisé.</b>",
            ["Passively generates <sprite name=\"insight\" tint=1> at any stage of the game, so using PPO in Normal Mode is no longer required for that."] =
                "Génère passivement de l'<sprite name=\"insight\" tint=1> à n'importe quel stade du jeu, si bien qu'utiliser PPO en mode normal n'est plus nécessaire pour cela.",
            ["It gives an income multiplier to everything that produces <sprite name=\"chips\" tint=1> in any form."] =
                "Il donne un multiplicateur de revenu à tout ce qui produit des <sprite name=\"chips\" tint=1> sous quelque forme que ce soit.",
        };
    }
}
