using System;
using System.Collections.Generic;

namespace StackMerge
{
    // Russian (Русский) translation table. Keys are the exact English source strings; sprite tags are
    // preserved verbatim. Game-specific proper nouns (solver names, PPO) are kept in Latin.
    internal static class StackMergeLocalizationRu
    {
        public static readonly Dictionary<string, string> Table = new(StringComparer.Ordinal)
        {
            ["Play"] = "Игра",
            ["Algos"] = "Алго",
            ["Algorithms"] = "Алгоритмы",
            ["Upgrades"] = "Улучшения",
            ["Agents"] = "Агенты",
            ["Mods"] = "Моды",
            ["Modifiers"] = "Модификаторы",
            ["Research"] = "Исследования",
            ["DC"] = "ЦОД",
            ["Next"] = "Далее",
            ["History"] = "История",
            ["Achievements"] = "Достижения",
            ["Settings"] = "Настройки",
            ["Locked"] = "Заблокировано",
            ["Unlocked"] = "Открыто",
            ["Select"] = "Выбрать",
            ["Deselect"] = "Отменить",
            ["Tune"] = "Настроить",
            ["Change mode"] = "Сменить режим",
            ["Buy"] = "Купить",
            ["Equip"] = "Экипировать",
            ["Unequip"] = "Снять",
            ["Maxed"] = "Максимум",
            ["Done"] = "Готово",
            ["New run"] = "Новый ран",
            ["Manual"] = "Вручную",
            ["Manual mode"] = "Ручной режим",
            ["Auto solving"] = "Автоигра",
            ["Run ended"] = "Ран окончен",
            ["Run time"] = "Время рана",
            ["Config info"] = "Инфо конфиг.",
            ["Import save"] = "Импорт сохранения",
            ["Automatization"] = "Автоматизация",
            ["Income Bonus"] = "Бонус дохода",
            ["Passive Production"] = "Пассивное производство",
            ["Solver Speed"] = "Скорость солвера",
            ["Stack Capacity"] = "Ёмкость стека",
            ["Number of next blocks visible"] = "Число видимых следующих блоков",
            ["Higher blocks spawn"] = "Появление более крупных блоков",
            ["Lab Unlocks"] = "Открытия лаборатории",
            ["Passive PPO frame reduction"] = "Пассивное снижение кадров PPO",
            ["All Agents"] = "Все агенты",
            ["Base <sprite name=\"chips\" tint=1> income"] = "Базовый доход <sprite name=\"chips\" tint=1>",
            ["Ending profit"] = "Прибыль в конце",
            ["Merge streak"] = "Серия слияний",
            ["Score salvage"] = "Спасение очков",
            ["Passive <sprite name=\"chips\" tint=1> / tick"] = "Пассивные <sprite name=\"chips\" tint=1> / тик",
            ["Passive tick rate"] = "Частота пассивных тиков",
            ["Active multiplier"] = "Активный множитель",
            ["Faster solver"] = "Быстрее солвер",
            ["Solver delay"] = "Задержка солвера",
            ["Stack rows"] = "Ряды стека",
            ["Visible blocks"] = "Видимые блоки",
            ["Higher chance"] = "Выше шанс",
            ["Higher frequency"] = "Выше частота",
            ["Stage Progression"] = "Прогресс этапов",
            ["Prestige Console"] = "Консоль престижа",
            ["Collection"] = "Коллекция",
            ["PPO Training complete — prestige reset unlocked."] = "Обучение PPO завершено — сброс престижа открыт.",
            ["Auto restart needs token"] = "Для автоперезапуска нужен токен",
            ["The run hasn't started yet."] = "Ран ещё не начался.",
            ["No moves left — run over"] = "Ходов не осталось — ран окончен",
            ["Not enough <sprite name=\"chips\" tint=1>"] = "Недостаточно <sprite name=\"chips\" tint=1>",
            ["Buy an algorithm first"] = "Сначала купите алгоритм",
            ["Speed upgrade unavailable"] = "Улучшение скорости недоступно",
            ["Stack upgrade unavailable"] = "Улучшение стека недоступно",
            ["Next preview upgrade unavailable"] = "Улучшение предпросмотра недоступно",
            ["Income upgrade unavailable"] = "Улучшение дохода недоступно",
            ["Solver tuning unlocked"] = "Настройка солвера открыта",
            ["Auto solve updated"] = "Автоигра обновлена",
            ["Auto restart updated"] = "Автоперезапуск обновлён",
            ["Modifier Lab unlocked"] = "Лаборатория модификаторов открыта",
            ["Unlock Agents in Upgrades first"] = "Сначала откройте агентов в Улучшениях",
            ["Unlock Modifier Lab in Upgrades first"] = "Сначала откройте лабораторию модификаторов в Улучшениях",
            ["Finish PPO Training first"] = "Сначала завершите обучение PPO",
            ["Unlock PPO to open Research"] = "Откройте PPO, чтобы открыть Исследования",
            ["Normal mode is still locked."] = "Обычный режим ещё заблокирован.",
            ["PPO: Training mode"] = "PPO: режим обучения",
            ["PPO: Normal mode"] = "PPO: обычный режим",
            ["Training Mode"] = "Режим обучения",
            ["Normal Mode"] = "Обычный режим",
            ["Normal Mode\nLocked"] = "Обычный режим\nЗаблокирован",
            ["PPO Mode Overlay is not assigned."] = "PPO Mode Overlay не назначен.",
            ["Training: keeps learning, earns no chips.\nNormal: plays for chips like other solvers."] = "Обучение: продолжает учиться, не приносит фишек.\nОбычный: играет ради фишек, как другие солверы.",
            ["Music"] = "Музыка",
            ["Sound"] = "Звук",
            ["Enable haptic feedback"] = "Включить тактильную отдачу",
            ["Show FPS"] = "Показать FPS",
            ["Hide FPS"] = "Скрыть FPS",
            ["Achievement Pop-ups"] = "Всплывающие достижения",
            ["Hide achievement pop-ups"] = "Скрыть всплывающие достижения",
            ["Export / Import game"] = "Экспорт / импорт игры",
            ["Language"] = "Язык",
            ["Manual controls"] = "Ручное управление",
            ["Tap a stack to place the current next block."] = "Коснитесь стека, чтобы поставить текущий следующий блок.",
            ["Equip Miner's Pickaxe, then tap a stack block to remove it."] = "Экипируйте Miner's Pickaxe, затем коснитесь блока в стеке, чтобы удалить его.",
            ["Equip Queue Scrubber, then tap the first next block to remove it."] = "Экипируйте Queue Scrubber, затем коснитесь первого следующего блока, чтобы удалить его.",
            ["Tap a block to remove it with Miner's Pickaxe"] = "Коснитесь блока, чтобы удалить его с помощью Miner's Pickaxe",
            ["Tap the first next block to scrub it"] = "Коснитесь первого следующего блока, чтобы удалить его",
            ["Miner's Pickaxe equipped"] = "Miner's Pickaxe экипирован",
            ["Miner's Pickaxe unequipped"] = "Miner's Pickaxe снят",
            ["Queue Scrubber equipped"] = "Queue Scrubber экипирован",
            ["Queue Scrubber unequipped"] = "Queue Scrubber снят",
            ["Miner's Pickaxe is locked"] = "Miner's Pickaxe заблокирован",
            ["Queue Scrubber is locked"] = "Queue Scrubber заблокирован",
            ["Miner's Pickaxe has no uses left"] = "У Miner's Pickaxe не осталось использований",
            ["Queue Scrubber has no uses left"] = "У Queue Scrubber не осталось использований",
            ["No block available for Miner's Pickaxe"] = "Нет блока для Miner's Pickaxe",
            ["No next block available for Queue Scrubber"] = "Нет следующего блока для Queue Scrubber",
            ["Modifier unavailable"] = "Модификатор недоступен",
            ["Unlocks rule-changing modules that apply to new runs."] = "Открывает меняющие правила модули, действующие в новых ранах.",
            ["The solver places blocks faster with each level."] = "С каждым уровнем солвер ставит блоки быстрее.",
            ["Solver is automatically playing the game."] = "Солвер играет автоматически.",
            ["When the run ends, a new one starts automatically."] = "Когда ран заканчивается, автоматически начинается новый.",
            ["The currency for Auto restart."] = "Валюта для автоперезапуска.",
            ["Allows you to modify the solver parameters."] = "Позволяет изменять параметры солвера.",
            ["Another slot so you can use 3 Agents at once."] = "Ещё один слот, чтобы использовать 3 агентов сразу.",
            ["They give you extra bonuses when you unlock them."] = "Открытые, они дают дополнительные бонусы.",
            ["Increases the capacity of each stack by 1 per level."] = "Увеличивает ёмкость каждого стека на 1 за уровень.",
            ["Shows 1 more upcoming block per level."] = "Показывает на 1 предстоящий блок больше за уровень.",
            ["Increases the chance of spawning higher blocks."] = "Повышает шанс появления более крупных блоков.",
            ["Slightly increases how often higher blocks appear."] = "Немного повышает частоту появления более крупных блоков.",
            ["Boosts base <sprite name=\"chips\" tint=1> income. Early levels give larger gains."] = "Увеличивает базовый доход <sprite name=\"chips\" tint=1>. Ранние уровни дают больше.",
            ["Boosts the <sprite name=\"chips\" tint=1> bonus at the end of the runs."] = "Увеличивает бонус <sprite name=\"chips\" tint=1> в конце ранов.",
            ["Boosts the <sprite name=\"chips\" tint=1> earned during merges and runs."] = "Увеличивает <sprite name=\"chips\" tint=1>, полученные при слияниях и ранах.",
            ["Shrinks the delay of MOCA and PLAN solvers."] = "Сокращает задержку солверов MOCA и PLAN.",
            ["Chips trickle in on a timer, on top of your normal play."] = "Фишки поступают по таймеру, помимо обычной игры.",
            ["Passive Production ticks more often."] = "Пассивное производство тикает чаще.",
            ["Lowers the frame needed in Training Mode."] = "Снижает число кадров, нужных в режиме обучения.",
            ["Lowers the frames needed for PPO Normal Mode."] = "Снижает число кадров для обычного режима PPO.",
            ["Each level shortens how often Curriculum lowers the PPO requirement."] = "Каждый уровень сокращает интервал, с которым Curriculum снижает требование PPO.",
            ["Needs Difficulty L1"] = "Нужна Сложность У1",
            ["Needs PPO or Bootcamp L5"] = "Нужен PPO или Bootcamp У5",
            ["Needs Curriculum"] = "Нужен Curriculum",
            ["Boosts Passive Production while you're actively playing."] = "Усиливает пассивное производство, пока вы активно играете.",
            ["Passive yield upgrade unavailable"] = "Улучшение пассивной отдачи недоступно",
            ["Passive tick rate upgrade unavailable"] = "Улучшение частоты пассивных тиков недоступно",
            ["Active multiplier upgrade unavailable"] = "Улучшение активного множителя недоступно",
            ["Compute speed upgrade unavailable"] = "Улучшение скорости вычислений недоступно",
            ["Stage locked"] = "Этап заблокирован",
            ["Needs algorithm"] = "Нужен алгоритм",
            ["Needs Agents"] = "Нужны агенты",
            ["Stage 1 - Core automation"] = "Этап 1 — Базовая автоматизация",
            ["Stage 2 - Agent acceleration"] = "Этап 2 — Ускорение агентами",
            ["Stage 3 - Modifier Lab"] = "Этап 3 — Лаборатория модификаторов",
            ["Stage 4 - Machine Learning"] = "Этап 4 — Машинное обучение",
            ["Endgame - PPO training"] = "Финал — обучение PPO",
            ["Train PPO, then prestige from the Research menu."] = "Обучите PPO, затем сделайте престиж в меню Исследований.",
            ["PPO is ready to unlock in Algorithms."] = "PPO готов к открытию в Алгоритмах.",
            ["Max every Modifier to open the Machine Learning layer."] = "Прокачайте каждый модификатор до максимума, чтобы открыть слой Машинного обучения.",
            ["Open Agents to start the next stage."] = "Откройте агентов, чтобы начать следующий этап.",
            ["Unlock COMBO or LOOK solver to open Agents."] = "Откройте солвер COMBO или LOOK, чтобы открыть агентов.",
            ["Unlock COMBO or LOOK solver first."] = "Сначала откройте солвер COMBO или LOOK.",
            ["Modifiers Lab"] = "Лаборатория модификаторов",
            ["Agents Lab"] = "Лаборатория агентов",
            ["Stack capacity"] = "Ёмкость стека",
            ["Difficulty"] = "Сложность",
            ["Speed"] = "Скорость",
            ["Auto solve"] = "Автоигра",
            ["Auto restart"] = "Автоперезапуск",
            ["Mode"] = "Режим",
            ["Run score"] = "Очки рана",
            ["Score"] = "Очки",
            ["Median"] = "Медиана",
            ["Best"] = "Лучший",
            ["Moves"] = "Ходы",
            ["Merges"] = "Слияния",
            ["Current next"] = "Текущий следующий",
            ["Available actions"] = "Доступные действия",
            ["Solver"] = "Солвер",
            ["Run modifiers"] = "Модификаторы рана",
            ["Special blocks"] = "Особые блоки",
            ["Solver tuning"] = "Настройка солвера",
            ["+50 tokens"] = "+50 токенов",
            ["Locked in Upgrades."] = "Открывается в Улучшениях.",
            ["No tuning available for this solver."] = "Для этого солвера нет настроек.",
            ["Default"] = "По умолчанию",
            ["RAND has no tuning. Its identity is pure randomness."] = "У RAND нет настроек. Его суть — чистая случайность.",
            ["MERG stays greedy, but these sliders decide how hard it chases immediate value."] = "MERG остаётся жадным, но эти ползунки решают, насколько упорно он гонится за мгновенной выгодой.",
            ["BAL remains a board stabilizer. Tune how defensive or merge-friendly it should be."] = "BAL остаётся стабилизатором поля. Настройте, насколько он должен быть оборонительным или склонным к слияниям.",
            ["HEUR is a weighted score formula. These are the clearest direct knobs."] = "HEUR — это взвешенная формула очков. Это его самые понятные прямые настройки.",
            ["LOOK uses HEUR plus a follow-up estimate. Tune its greed and its second-step trust."] = "LOOK использует HEUR плюс оценку следующего хода. Настройте его жадность и доверие ко второму шагу.",
            ["MOCA samples futures. Its tuning can spend a little more thinking on rollout depth or sample count."] = "MOCA сэмплирует варианты будущего. Его настройка может тратить чуть больше вычислений на глубину роллаута или число выборок.",
            ["PLAN searches the visible queue. Tune how much it trusts short plans over current safety."] = "PLAN просматривает видимую очередь. Настройте, насколько он доверяет коротким планам в ущерб текущей безопасности.",
            ["PLAN-5 searches deeper queue lines. Tuning lets you decide whether it should be patient or practical."] = "PLAN-5 просматривает более глубокие линии очереди. Настройка решает, быть ли ему терпеливым или практичным.",
            ["MOCA+ uses smarter rollouts. Tuning affects both how much it samples and how it values rollout boards."] = "MOCA+ использует более умные роллауты. Настройка влияет и на число выборок, и на оценку полей роллаута.",
            ["MCTS builds a tree. These sliders tune search behavior without replacing the tree search identity."] = "MCTS строит дерево. Эти ползунки настраивают поведение поиска, не заменяя суть древовидного поиска.",
            ["STALL is defensive. Tune how much it sacrifices score to keep the board alive."] = "STALL оборонителен. Настройте, сколько очков он жертвует, чтобы удержать поле в игре.",
            ["COMBO looks for chain setups. Tune how patient it should be while preparing cascades."] = "COMBO ищет заготовки цепочек. Настройте, насколько он терпелив при подготовке каскадов.",
            ["PPO trains its own actor-critic network. These nudge the learning hyperparameters within safe bounds."] = "PPO обучает собственную сеть актор-критик. Эти настройки сдвигают гиперпараметры обучения в безопасных пределах.",
            ["Merge reward"] = "Награда за слияние",
            ["Score delta"] = "Дельта очков",
            ["High block"] = "Высокий блок",
            ["Height penalty"] = "Штраф за высоту",
            ["Empty cells"] = "Пустые клетки",
            ["Smoothness"] = "Плавность",
            ["Danger penalty"] = "Штраф за опасность",
            ["Queue fit"] = "Соответствие очереди",
            ["Follow-up trust"] = "Доверие к следующему ходу",
            ["Simulation rounds"] = "Раунды симуляции",
            ["Rollout moves"] = "Ходы роллаута",
            ["Planning depth"] = "Глубина планирования",
            ["Future weight"] = "Вес будущего",
            ["Rollout planning"] = "Планирование роллаута",
            ["Board eval"] = "Оценка поля",
            ["Anti-stall"] = "Анти-затор",
            ["Tree visits"] = "Посещения дерева",
            ["Exploration"] = "Исследование",
            ["Prior bias"] = "Априорный вес",
            ["Safety cushion"] = "Запас безопасности",
            ["Combo setup"] = "Подготовка комбо",
            ["Legal moves"] = "Легальные ходы",
            ["Height spread"] = "Разброс высоты",
            ["Future depth"] = "Глубина будущего",
            ["Gamma (discount)"] = "Гамма (дисконт)",
            ["Lambda (GAE)"] = "Лямбда (GAE)",
            ["Clip epsilon"] = "Эпсилон клипа",
            ["Raises or lowers the reward for immediate merges and cascade size."] = "Повышает или понижает награду за мгновенные слияния и размер каскада.",
            ["Changes how much raw score gained by the move matters."] = "Меняет, насколько важны чистые очки, полученные за ход.",
            ["Pushes the solver toward producing larger top blocks."] = "Подталкивает солвер создавать более крупные верхние блоки.",
            ["Positive values avoid tall uneven stacks more strongly."] = "Положительные значения сильнее избегают высоких неровных стеков.",
            ["Rewards boards with more open cells after the move."] = "Награждает поля с большим числом свободных клеток после хода.",
            ["Rewards similar stack heights and penalizes lopsided boards."] = "Награждает похожие высоты стеков и штрафует перекошенные поля.",
            ["Penalizes stacks near capacity more strongly."] = "Сильнее штрафует стеки, близкие к ёмкости.",
            ["Lets BAL accept more merge value before spreading out."] = "Позволяет BAL принять больше ценности слияния прежде чем распределяться.",
            ["Changes how strongly immediate score gain affects the move score."] = "Меняет, насколько сильно мгновенный прирост очков влияет на оценку хода.",
            ["Rewards free stack cells after the move."] = "Награждает свободные клетки стека после хода.",
            ["Rewards smoother stack heights and fewer awkward bottlenecks."] = "Награждает более плавные высоты стеков и меньше неудобных заторов.",
            ["Rewards top blocks that match upcoming queue values."] = "Награждает верхние блоки, совпадающие с предстоящими значениями очереди.",
            ["Raises or lowers the value of immediate merge chains."] = "Повышает или понижает ценность мгновенных цепочек слияний.",
            ["Makes near-full stacks scarier to the heuristic."] = "Делает почти полные стеки страшнее для эвристики.",
            ["Changes how much the first move's score gain matters."] = "Меняет, насколько важен прирост очков за первый ход.",
            ["Rewards keeping more room open after the first move."] = "Награждает за сохранение большего свободного места после первого хода.",
            ["Changes how much the simulated next move influences the choice."] = "Меняет, насколько симулированный следующий ход влияет на выбор.",
            ["Rewards stack tops that line up with visible upcoming blocks."] = "Награждает вершины стеков, совпадающие с видимыми предстоящими блоками.",
            ["Punishes positions that are close to stalling."] = "Наказывает позиции, близкие к затору.",
            ["Adjusts how many futures are sampled for each legal move."] = "Регулирует, сколько вариантов будущего сэмплируется на каждый легальный ход.",
            ["Adjusts how many moves each future is played forward."] = "Регулирует, на сколько ходов вперёд проигрывается каждый вариант будущего.",
            ["Changes the immediate score bias inside rollout evaluation."] = "Меняет смещение мгновенных очков внутри оценки роллаута.",
            ["Rewards futures that leave more cells open."] = "Награждает варианты будущего, оставляющие больше свободных клеток.",
            ["Makes dangerous simulated boards less attractive."] = "Делает опасные симулированные поля менее привлекательными.",
            ["Rewards rollouts that keep useful top blocks for the visible queue."] = "Награждает роллауты, сохраняющие полезные верхние блоки под видимую очередь.",
            ["Shifts how many visible queued blocks the search tries to use."] = "Меняет, сколько видимых блоков очереди поиск пытается использовать.",
            ["Changes how strongly future planned moves affect the first move."] = "Меняет, насколько сильно будущие запланированные ходы влияют на первый ход.",
            ["Rewards stack tops that match upcoming values."] = "Награждает вершины стеков, совпадающие с предстоящими значениями.",
            ["Rewards planned lines that keep space available."] = "Награждает запланированные линии, сохраняющие свободное место.",
            ["Penalizes plans that leave near-full stacks."] = "Штрафует планы, оставляющие почти полные стеки.",
            ["Shifts how many queued blocks the search tries to use."] = "Меняет, сколько блоков очереди поиск пытается использовать.",
            ["Changes how strongly deeper planned scores affect the first move."] = "Меняет, насколько сильно более глубокие плановые очки влияют на первый ход.",
            ["Rewards preserving useful stack tops for upcoming blocks."] = "Награждает сохранение полезных вершин стеков для предстоящих блоков.",
            ["Rewards plans that leave more board room."] = "Награждает планы, оставляющие больше места на поле.",
            ["Penalizes risky deep plans more strongly."] = "Сильнее штрафует рискованные глубокие планы.",
            ["Adjusts how many smart futures are sampled for each move."] = "Регулирует, сколько умных вариантов будущего сэмплируется на каждый ход.",
            ["Adjusts how far smart futures are played forward."] = "Регулирует, насколько далеко проигрываются умные варианты будущего.",
            ["Adjusts how much queue planning each rollout uses."] = "Регулирует, сколько планирования очереди использует каждый роллаут.",
            ["Changes how much the final simulated board shape matters."] = "Меняет, насколько важна итоговая форма симулированного поля.",
            ["Rewards futures that preserve legal moves and escape routes."] = "Награждает варианты будущего, сохраняющие легальные ходы и пути отступления.",
            ["Adjusts how many tree iterations are spent per decision."] = "Регулирует, сколько итераций дерева тратится на одно решение.",
            ["Higher values try less-proven branches more often."] = "Более высокие значения чаще пробуют менее проверенные ветви.",
            ["Changes how strongly heuristic prior scores guide the tree."] = "Меняет, насколько сильно эвристические априорные очки направляют дерево.",
            ["Adjusts how far rollouts play from a tree node."] = "Регулирует, насколько далеко роллауты играют от узла дерева.",
            ["Rewards tree lines that leave room and legal moves."] = "Награждает линии дерева, оставляющие место и легальные ходы.",
            ["Rewards lines that create potential chain merges."] = "Награждает линии, создающие потенциальные цепочки слияний.",
            ["Rewards positions with multiple available stacks."] = "Награждает позиции с несколькими доступными стеками.",
            ["Rewards spare capacity after each move."] = "Награждает свободную ёмкость после каждого хода.",
            ["Punishes near-full stacks more strongly."] = "Сильнее наказывает почти полные стеки.",
            ["Penalizes uneven stack heights."] = "Штрафует неровные высоты стеков.",
            ["Lets STALL take more immediate merge value."] = "Позволяет STALL брать больше мгновенной ценности слияния.",
            ["Rewards adjacent equal values and future cascade potential."] = "Награждает соседние равные значения и потенциал будущего каскада.",
            ["Changes how much immediate merging competes with setup."] = "Меняет, насколько мгновенное слияние конкурирует с подготовкой.",
            ["Adjusts how many setup moves the combo estimate looks through."] = "Регулирует, сколько подготовительных ходов просматривает оценка комбо.",
            ["Keeps some space open while building combos."] = "Сохраняет немного свободного места при построении комбо.",
            ["How far ahead future reward is valued. Higher plans longer-term, lower is greedier."] = "Насколько далеко ценится будущая награда. Выше — планирует на дольше, ниже — жаднее.",
            ["Advantage estimation bias/variance trade-off. Higher = lower bias, more variance."] = "Компромисс смещение/дисперсия оценки преимущества. Выше = меньше смещения, больше дисперсии.",
            ["How big a policy update each step may make. Smaller is more conservative and stable."] = "Насколько большим может быть обновление политики за шаг. Меньше — консервативнее и стабильнее.",
            ["Completed"] = "Выполнено",
            ["Secrets"] = "Секреты",
            ["Statistics"] = "Статистика",
            ["PPO Progress"] = "Прогресс PPO",
            ["No completed runs yet. Let a run end to start collecting solver stats."] = "Пока нет завершённых ранов. Дайте рану закончиться, чтобы начать собирать статистику солверов.",
            ["Tip: use the editor benchmark window for large balance samples without touching player progression."] = "Совет: используйте окно бенчмарка редактора для больших выборок баланса, не затрагивая прогресс игрока.",
            ["Earn 10000 <sprite name=\"chips\" tint=1> in total"] = "Заработайте суммарно 10000 <sprite name=\"chips\" tint=1>",
            ["Earn 1M <sprite name=\"chips\" tint=1> in total"] = "Заработайте суммарно 1M <sprite name=\"chips\" tint=1>",
            ["Earn 1B <sprite name=\"chips\" tint=1> in total"] = "Заработайте суммарно 1B <sprite name=\"chips\" tint=1>",
            ["Spend 10000 <sprite name=\"chips\" tint=1> in total"] = "Потратьте суммарно 10000 <sprite name=\"chips\" tint=1>",
            ["Spend 100K <sprite name=\"chips\" tint=1> in total"] = "Потратьте суммарно 100K <sprite name=\"chips\" tint=1>",
            ["Spend 100M <sprite name=\"chips\" tint=1> in total"] = "Потратьте суммарно 100M <sprite name=\"chips\" tint=1>",
            ["Complete 10 runs while Auto Solver is turned off"] = "Завершите 10 ранов с выключенным Авто-солвером",
            ["Complete 1000 runs with a solver"] = "Завершите 1000 ранов одним солвером",
            ["Move a total of 10000 times"] = "Сделайте суммарно 10000 ходов",
            ["Move a total of 100K times"] = "Сделайте суммарно 100K ходов",
            ["Move a total of 1M times"] = "Сделайте суммарно 1M ходов",
            ["Merge a total of 10000 times"] = "Совершите суммарно 10000 слияний",
            ["Merge a total of 100K times"] = "Совершите суммарно 100K слияний",
            ["Merge a total of 1M times"] = "Совершите суммарно 1M слияний",
            ["Reach high 1024"] = "Достигните блока 1024",
            ["Reach high 8192"] = "Достигните блока 8192",
            ["Reach high 65536"] = "Достигните блока 65536",
            ["Unlock Agents"] = "Откройте агентов",
            ["Equip 3 Agents at once"] = "Экипируйте 3 агентов одновременно",
            ["Unlock Modifiers"] = "Откройте модификаторы",
            ["Use all solvers at least once"] = "Используйте каждый солвер хотя бы раз",
            ["Use all Agents at least once"] = "Используйте каждого агента хотя бы раз",
            ["Let Unstable Stack save your run a total of 100 times"] = "Дайте Unstable Stack спасти ваш ран суммарно 100 раз",
            ["Merge with a Joker for a total of 100 times"] = "Совершите слияние с Джокером суммарно 100 раз",
            ["Consume a total of 5000 <sprite name=\"token\" tint=1>"] = "Израсходуйте суммарно 5000 <sprite name=\"token\" tint=1>",
            ["Hold at least 10000 <sprite name=\"token\" tint=1> at once"] = "Держите одновременно не менее 10000 <sprite name=\"token\" tint=1>",
            ["Prestige reset for the first time"] = "Сделайте сброс престижа впервые",
            ["Prestige reset for a total of 5 times"] = "Сделайте сброс престижа суммарно 5 раз",
            ["Prestige reset for a total of 15 times"] = "Сделайте сброс престижа суммарно 15 раз",
            ["Run PPO once in Normal Mode"] = "Запустите PPO один раз в обычном режиме",
            ["Reach 100K PPO frames"] = "Достигните 100K кадров PPO",
            ["Earn 1000 <sprite name=\"insight\" tint=1> in total"] = "Заработайте суммарно 1000 <sprite name=\"insight\" tint=1>",
            ["Earn 10K <sprite name=\"insight\" tint=1> in total"] = "Заработайте суммарно 10K <sprite name=\"insight\" tint=1>",
            ["Earn 100K <sprite name=\"insight\" tint=1> in total"] = "Заработайте суммарно 100K <sprite name=\"insight\" tint=1>",
            ["Buy all the researches"] = "Купите все исследования",
            ["Have at least 1 unit in each Server Rack"] = "Имейте не менее 1 единицы в каждой серверной стойке",
            ["Go above 1000 GF/s total compute"] = "Превысьте 1000 GF/s общей вычислительной мощности",
            ["Reach 1M PPO Training frames"] = "Достигните 1M кадров обучения PPO",
            ["Let It Cook"] = "Пусть готовится",
            ["Budget Intelligence"] = "Экономный интеллект",
            ["Surgical Move"] = "Хирургический ход",
            ["Perfectly Reasonable"] = "Совершенно разумно",
            ["Full Autopilot"] = "Полный автопилот",
            ["Bad Financial Advice"] = "Плохой финансовый совет",
            ["Still Here"] = "Всё ещё здесь",
            ["One More Run"] = "Ещё один ран",
            ["See You Again"] = "До новой встречи",
            ["Perfectly Balanced"] = "Идеально сбалансировано",
            ["Second Thoughts"] = "Сомнения",
            ["No Defaults Given"] = "Без значений по умолчанию",
            ["Let it cook"] = "Пусть готовится",
            ["Old intelligence"] = "Старый интеллект",
            ["Remove something big"] = "Удалите что-то крупное",
            ["A very specific reserve"] = "Очень точный запас",
            ["Everything buys itself"] = "Всё покупает себя само",
            ["Questionable first purchase"] = "Сомнительная первая покупка",
            ["Stay a while"] = "Останьтесь ненадолго",
            ["Just one more run"] = "Всего один ещё ран",
            ["Come back often"] = "Возвращайтесь чаще",
            ["Almost perfectly split"] = "Почти идеально поделено",
            ["Second thoughts"] = "Внезапное сомнение",
            ["No defaults left"] = "Значений по умолчанию не осталось",
            ["Earn offline rewards after being away for 8+ hours."] = "Получите офлайн-награды после 8+ часов отсутствия.",
            ["Complete a run with RAND after unlocking PPO."] = "Завершите ран с RAND после открытия PPO.",
            ["Use Miner's Pickaxe on a block worth 1024 or higher."] = "Используйте Miner's Pickaxe на блоке 1024 или выше.",
            ["Hold exactly 2048 <sprite name=\"token\" tint=1> after a run ends."] = "Имейте ровно 2048 <sprite name=\"token\" tint=1> в конце рана.",
            ["Have all Auto Buy buttons enabled simultaneously."] = "Включите все кнопки Автопокупки одновременно.",
            ["Buy the Joker as your first Modifier in a prestige."] = "Купите Джокера как первый модификатор в престиже.",
            ["Have 24 hours of lifetime playtime."] = "Наберите 24 часа общего игрового времени.",
            ["Leave the game open for 2 hours straight."] = "Оставьте игру открытой 2 часа подряд.",
            ["Exit the game 10 times."] = "Выйдите из игры 10 раз.",
            ["Split Compute Allocation exactly 33-33-33-1."] = "Разделите распределение вычислений ровно 33-33-33-1.",
            ["Deselect a solver immediately after selecting it."] = "Отмените выбор солвера сразу после его выбора.",
            ["Modify all parameters of PPO in Tuning."] = "Измените все параметры PPO в настройке.",
            ["Unlocks Auto Buy for Algos, Upgrades, Agents and Mods"] = "Открывает Автопокупку для Алго, улучшений, агентов и модов",
            ["Unlocks Datacenter"] = "Открывает центр обработки данных",
            ["Merge streak upgrade at max level is 5% stronger"] = "Улучшение Серия слияний на максимуме на 5% сильнее",
            ["PPO learns from your Manual runs"] = "PPO учится на ваших ручных ранах",
            ["Higher frequency upgrade at max level is 2% stronger"] = "Улучшение Выше частота на максимуме на 2% сильнее",
            ["Unlocks Byte numeral for blocks"] = "Открывает запись Байт для блоков",
            ["Unlocks Power numeral for blocks"] = "Открывает запись Степень для блоков",
            ["Unlocks Roman numeral for blocks"] = "Открывает римскую запись для блоков",
            ["Unlocks Hexadecimal numeral for blocks"] = "Открывает шестнадцатеричную запись для блоков",
            ["Unlocks Scientific numeral for blocks"] = "Открывает научную запись для блоков",
            ["Complete its goal to unlock this numeral"] = "Выполните её цель, чтобы открыть эту запись",
            ["Consecutive merges multiply move income."] = "Слияния подряд умножают доход за ход.",
            ["Converts part of the run's score into <sprite name=\"chips\" tint=1>."] = "Превращает часть очков рана в <sprite name=\"chips\" tint=1>.",
            ["Held <sprite name=\"token\" tint=1> pay <sprite name=\"chips\" tint=1> times the √ of the hoard."] = "Хранимые <sprite name=\"token\" tint=1> приносят <sprite name=\"chips\" tint=1>, умноженные на √ запаса.",
            ["The currency for Auto restart. Price rises the more <sprite name=\"token\" tint=1> you hold."] = "Валюта для автоперезапуска. Цена растёт с числом хранимых <sprite name=\"token\" tint=1>.",
            ["Standard"] = "Обычный",
            ["Byte"] = "Байт",
            ["Hexadecimal"] = "Шестнадцатеричный",
            ["Power"] = "Степень",
            ["Roman"] = "Римский",
            ["Scientific"] = "Научный",
            ["Audio"] = "Аудио",
            ["Accessibility"] = "Доступность",
            ["Application"] = "Приложение",
            ["Display"] = "Экран",
            ["Manage save files"] = "Управление сохранениями",
            ["Block numerals visual"] = "Стиль чисел на блоках",
            ["How to play"] = "Как играть",
            ["Highest"] = "Наивысший",
            ["Highest median"] = "Наивысшая медиана",
            ["Runs"] = "Раны",
            ["Earned"] = "Заработано",
            ["Resets"] = "Сбросы",
            ["Playtime"] = "Время игры",
            ["Solvers"] = "Солверы",
            ["Recent Score Trend"] = "Недавний тренд очков",
            ["Recent Runs"] = "Недавние раны",
            ["Lifetime Stats"] = "Общая статистика",
            ["Goals"] = "Цели",
            ["Prestige Summary"] = "Сводка престижа",
            ["Average time in runs"] = "Среднее время рана",
            ["Total frame"] = "Всего кадров",
            ["Average frame / Prestige"] = "Ср. кадров / престиж",
            ["Total runs"] = "Всего ранов",
            ["Total moves"] = "Всего ходов",
            ["Total merges"] = "Всего слияний",
            ["PPO knowledge"] = "Знания PPO",
            ["Total playtime"] = "Общее время игры",
            ["Merge Broker"] = "Брокер слияний",
            ["Highwater Analyst"] = "Аналитик рекордов",
            ["Score Auditor"] = "Аудитор очков",
            ["Overclocker"] = "Оверклокер",
            ["Quartermaster"] = "Квартирмейстер",
            ["Restart Sponsor"] = "Спонсор перезапусков",
            ["Token Prospector"] = "Старатель токенов",
            ["Move Dividend"] = "Дивиденд с ходов",
            ["Velocity Trader"] = "Трейдер скорости",
            ["Unstable Stack"] = "Нестабильный стек",
            ["Catalyst Stack"] = "Стек-катализатор",
            ["Mirror Stack"] = "Зеркальный стек",
            ["Joker"] = "Джокер",
            ["Miner's Pickaxe"] = "Кирка шахтёра",
            ["Queue Scrubber"] = "Очиститель очереди",
            ["Neural Accelerator"] = "Нейроускоритель",
            ["Boosts merge income."] = "Увеличивает доход со слияний.",
            ["Rewards new highs."] = "Награждает новые рекордные блоки.",
            ["Turns score into <sprite name=\"chips\" tint=1>."] = "Превращает очки в <sprite name=\"chips\" tint=1>.",
            ["Runs the solver faster."] = "Ускоряет работу солвера.",
            ["Improves baseline income."] = "Улучшает базовый доход.",
            ["Keeps restarts funded."] = "Финансирует перезапуски.",
            ["Turns merge volume into restart fuel."] = "Превращает объём слияний в топливо для перезапуска.",
            ["Rewards long, stable runs."] = "Награждает длинные стабильные раны.",
            ["Rewards fast solvers."] = "Награждает быстрые солверы.",
            ["Deletes bottom blocks when a full stack would fail."] = "Удаляет нижние блоки, когда полный стек привёл бы к проигрышу.",
            ["Converts merges into more <sprite name=\"chips\" tint=1>."] = "Превращает слияния в больше <sprite name=\"chips\" tint=1>.",
            ["Lets stack ends interact."] = "Позволяет концам стека взаимодействовать.",
            ["Adds wild blocks to the queue."] = "Добавляет в очередь дикие блоки.",
            ["Lets solvers remove blocks from the board."] = "Позволяет солверам убирать блоки с поля.",
            ["Lets solvers delete bad upcoming blocks."] = "Позволяет солверам удалять плохие предстоящие блоки.",
            ["Speeds up expensive solvers."] = "Ускоряет ресурсоёмкие солверы.",
            ["Select an algorithm to inspect it. Locked algorithms hide detailed behavior until unlocked."] = "Выберите алгоритм для просмотра. Заблокированные алгоритмы скрывают детали поведения до открытия.",
            ["Buy automation, unlock new layers, then push into riskier systems when the run history proves you are ready."] = "Покупайте автоматизацию, открывайте новые слои, затем переходите к более рискованным системам, когда история ранов покажет, что вы готовы.",
            ["Equipped Agents give various bonuses to progress faster."] = "Экипированные агенты дают различные бонусы для более быстрого прогресса.",
            ["Late-game rule modules. They raise the ceiling, create rescue tools, and make solver choice matter more than raw price."] = "Модули правил позднего этапа. Они поднимают потолок, создают инструменты спасения и делают выбор солвера важнее простой цены.",
            ["They expand the game rules, allowing for further production. Each solver is effective in different ways."] = "Они расширяют правила игры, позволяя больше производить. Каждый солвер эффективен по-своему.",
            ["Rule-changing modules that apply to new runs and amplify the differences between solvers."] = "Меняющие правила модули, действующие в новых ранах и усиливающие различия между солверами.",
            ["Modifiers apply to new runs and amplify solver differences."] = "Модификаторы действуют в новых ранах и усиливают различия между солверами.",
            ["You can track how many tasks you've completed. As you progress, you'll automatically unlock them."] = "Вы можете отслеживать, сколько задач выполнили. По мере прогресса они открываются автоматически.",
            ["Permanent late-game research. Prestige turns PPO Normal-mode performance into Insight, then the tree makes every future reset faster and deeper."] = "Постоянные исследования позднего этапа. Престиж превращает результаты обычного режима PPO в Insight, а дерево делает каждый будущий сброс быстрее и глубже.",
            ["Permanent late-game research. The tree makes every future reset faster and deeper."] = "Постоянные исследования позднего этапа. Дерево делает каждый будущий сброс быстрее и глубже.",
            ["Research locked. Finish PPO Training, then run PPO in Normal mode."] = "Исследования заблокированы. Завершите обучение PPO, затем запустите PPO в обычном режиме.",
            ["Track your recent runs and the performance of your used solvers."] = "Отслеживайте недавние раны и результаты использованных солверов.",
            ["Description"] = "Описание",
            ["<b>Manual controls</b>"] = "<b>Ручное управление</b>",
            ["Free baseline solver."] = "Бесплатный базовый солвер.",
            ["Randomly chooses any valid stack. Weak, chaotic, but fast."] = "Случайно выбирает любой допустимый стек. Слабый, хаотичный, но быстрый.",
            ["Looks for direct merges."] = "Ищет прямые слияния.",
            ["Prioritizes immediate merges and cascades before anything else."] = "Ставит мгновенные слияния и каскады превыше всего.",
            ["Keeps stacks even."] = "Держит стеки ровными.",
            ["Avoids tall dangerous stacks and spreads risk across the board."] = "Избегает высоких опасных стеков и распределяет риск по полю.",
            ["Scores every legal move."] = "Оценивает каждый легальный ход.",
            ["Uses handcrafted heuristics: merge value, danger, future queue fit, and free space."] = "Использует ручные эвристики: ценность слияния, опасность, соответствие будущей очереди и свободное место.",
            ["Plans one move deeper."] = "Планирует на один ход глубже.",
            ["Tests each move, then estimates the best follow-up move before deciding."] = "Пробует каждый ход, затем оценивает лучший следующий ход перед решением.",
            ["Runs simulations."] = "Запускает симуляции.",
            ["Rolls out multiple futures, judging each by the surviving board and the peak tier it reaches."] = "Проигрывает несколько вариантов будущего, оценивая каждый по выжившему полю и достигнутому пиковому уровню.",
            ["Reads the visible queue."] = "Читает видимую очередь.",
            ["Queue planner. Searches lines through up to 3 visible next blocks before choosing."] = "Планировщик очереди. Ищет линии через до 3 видимых следующих блоков перед выбором.",
            ["Queue planner. Searches lines through the visible next blocks. Planning depth (3–5) can be tuned for patience vs practicality."] = "Планировщик очереди. Ищет линии через видимые следующие блоки. Глубину планирования (3–5) можно настроить между терпением и практичностью.",
            ["Uses the extended queue."] = "Использует расширенную очередь.",
            ["Deep queue planner. Searches lines through up to 5 visible next blocks. Stronger once next preview upgrades are unlocked."] = "Глубокий планировщик очереди. Ищет линии через до 5 видимых следующих блоков. Сильнее с открытыми улучшениями предпросмотра.",
            ["Smarter Monte Carlo rollouts."] = "Более умные роллауты Монте-Карло.",
            ["Enhanced Monte Carlo. Each rollout uses short queue planning and an anti-stall board score."] = "Улучшенный Монте-Карло. Каждый роллаут использует короткое планирование очереди и антизаторную оценку поля.",
            ["Builds a search tree."] = "Строит дерево поиска.",
            ["Monte Carlo Tree Search. Balances exploring new lines with exploiting lines that already score well."] = "Monte Carlo Tree Search. Балансирует исследование новых линий и использование линий, уже дающих хорошие очки.",
            ["Avoids dead boards."] = "Избегает мёртвых полей.",
            ["Anti-stall solver. Heavily protects legal moves, semi-empty stacks, and escape routes over greedy merges."] = "Антизаторный солвер. Сильно защищает легальные ходы, полупустые стеки и пути отступления в ущерб жадным слияниям.",
            ["Sets up chain merges."] = "Готовит цепочки слияний.",
            ["Combo-focused solver. Reads the queue and rewards positions that can cascade over the next 2-3 turns."] = "Солвер, ориентированный на комбо. Читает очередь и награждает позиции, способные к каскаду в ближайшие 2-3 хода.",
            ["Endgame learner. Requires every Modifier to be fully purchased."] = "Ученик финального этапа. Требует полной покупки каждого модификатора.",
            ["Proximal Policy Optimization is a lightweight actor-critic neural network that learns its policy from run trajectories, clipped policy updates, value estimates, and entropy-driven exploration."] = "Proximal Policy Optimization — это лёгкая нейросеть актор-критик, которая обучает свою политику на траекториях ранов, обрезанных обновлениях политики, оценках ценности и исследовании, управляемом энтропией.",
            ["+75% <sprite name=\"chips\" tint=1> from merge rewards."] = "+75% <sprite name=\"chips\" tint=1> из наград за слияния.",
            ["+200% <sprite name=\"chips\" tint=1> from new highest-block rewards."] = "+200% <sprite name=\"chips\" tint=1> из наград за новый рекордный блок.",
            ["+200% <sprite name=\"chips\" tint=1> from end-of-run score bonus."] = "+200% <sprite name=\"chips\" tint=1> из бонуса очков в конце рана.",
            ["Solver move interval is 25% shorter."] = "Интервал хода солвера на 25% короче.",
            ["+10 <sprite name=\"chips\" tint=1> on every successful placement."] = "+10 <sprite name=\"chips\" tint=1> за каждую успешную установку.",
            ["Auto Restart consumes no tokens while this agent is active."] = "Автоперезапуск не тратит токены, пока этот агент активен.",
            ["+1 token for every 8 merges while active."] = "+1 токен за каждые 8 слияний, пока активен.",
            ["End-of-run <sprite name=\"chips\" tint=1> gain a bonus from total moves completed."] = "<sprite name=\"chips\" tint=1> в конце рана получают бонус от общего числа ходов.",
            ["End-of-run <sprite name=\"chips\" tint=1> gain a throughput bonus from moves per second."] = "<sprite name=\"chips\" tint=1> в конце рана получают бонус пропускной способности от числа ходов в секунду.",
            ["Each level gives one rescue per run. If a full stack receives a non-merge block, its bottom block is removed without reducing score."] = "Каждый уровень даёт одно спасение за ран. Если полный стек получает несливающийся блок, его нижний блок удаляется без потери очков.",
            ["Merge rewards are permanently doubled on every run after purchase."] = "После покупки награды за слияния навсегда удваиваются в каждом ране.",
            ["Unlocks a special merge. If the top and bottom block of a stack match, they merge through the stack."] = "Открывает особое слияние. Если верхний и нижний блок стека совпадают, они сливаются через стек.",
            ["Unlocks occasional Joker blocks. A Joker placed onto any block merges with it."] = "Открывает случайные блоки Джокера. Джокер, поставленный на любой блок, сливается с ним.",
            ["Each level gives one pickaxe use per run. The solver may delete any block in any stack."] = "Каждый уровень даёт одно использование кирки за ран. Солвер может удалить любой блок в любом стеке.",
            ["Each level gives one queue skip per run. The current next block is removed and the following block moves forward."] = "Каждый уровень даёт один пропуск очереди за ран. Текущий следующий блок удаляется, а следующий за ним сдвигается вперёд.",
            ["MOCA, MOCA+, and MCTS run permanently about twice as fast. Negative speed tuning on those solvers is also twice as effective."] = "MOCA, MOCA+ и MCTS постоянно работают примерно вдвое быстрее. Отрицательная настройка скорости на этих солверах также вдвое эффективнее.",
            ["MOCA runs permanently about twice as fast. Negative speed tuning on it is also twice as effective."] = "MOCA постоянно работает примерно вдвое быстрее. Отрицательная настройка скорости также вдвое эффективнее.",
            ["+35% <sprite name=\"insight\" tint=1> from every future prestige per level."] = "+35% <sprite name=\"insight\" tint=1> с каждого будущего престижа за уровень.",
            ["Start after each prestige reset with <sprite name=\"chips\" tint=1> already banked. This allows making purchases right at the beginning of the game."] = "Начинайте после каждого сброса престижа с уже отложенными <sprite name=\"chips\" tint=1>. Это позволяет делать покупки прямо в начале игры.",
            ["Permanently remembers automation unlocks per level after prestige: Auto Solve, Auto Restart <sprite name=\"token\" tint=1>, then Solver Tuning."] = "Навсегда запоминает открытие автоматизации за уровень после престижа: Автоигра, Автоперезапуск <sprite name=\"token\" tint=1>, затем Настройка солвера.",
            ["Start future prestiges with early algorithms already known: BAL, HEUR, COMBO, then LOOK."] = "Начинайте будущие престижи с уже известными ранними алгоритмами: BAL, HEUR, COMBO, затем LOOK.",
            ["+18% <sprite name=\"chips\" tint=1> from every reward per level. It stacks with Chip Yield and stage multipliers."] = "+18% <sprite name=\"chips\" tint=1> с каждой награды за уровень. Складывается с Доходностью фишек и множителями этапов.",
            ["+50% <sprite name=\"chips\" tint=1> from every reward per level. It stacks with Chip Yield and stage multipliers, making every future playthrough visibly faster."] = "+50% <sprite name=\"chips\" tint=1> с каждой награды за уровень. Складывается с Доходностью фишек и множителями этапов, делая каждое будущее прохождение заметно быстрее.",
            ["PPO still resets every prestige, but each level lowers the trained frame requirement for Normal Mode by 8%."] = "PPO по-прежнему сбрасывается при каждом престиже, но каждый уровень снижает требование обученных кадров для обычного режима на 8%.",
            ["Prestige banks 50000 PPO training frames per level. The next playthrough's PPO Training starts from that saved progress, with the knowledge already learned (instead of zero)."] = "Престиж сохраняет 50000 кадров обучения PPO за уровень. Обучение PPO в следующем прохождении начинается с этого сохранённого прогресса, с уже полученными знаниями (вместо нуля).",
            ["Each level lowers the cycle frame requirement for PPO Normal Mode by 8%. At level 5, PPO Curriculum upgrades can be bought before PPO is unlocked and can fully automate the remaining cycle requirement."] = "Каждый уровень снижает требование кадров цикла для обычного режима PPO на 8%. На 5 уровне улучшения PPO Curriculum можно купить до открытия PPO, и они полностью автоматизируют оставшееся требование цикла.",
            ["Prestige banks 50000 PPO cycle frames per level. The next playthrough's PPO Training starts from that saved cycle progress, while Datacenter training remains as permanent PPO knowledge."] = "Престиж сохраняет 50000 кадров цикла PPO за уровень. Обучение PPO в следующем прохождении начинается с этого сохранённого прогресса цикла, а обучение центра данных остаётся постоянным знанием PPO.",
            ["Prestige banks 40000 PPO cycle frames per level. The next playthrough's PPO Training starts from that saved cycle progress, while Datacenter training remains as permanent PPO knowledge."] = "Престиж сохраняет 40000 кадров цикла PPO за уровень. Обучение PPO в следующем прохождении начинается с этого сохранённого прогресса цикла, а обучение центра данных остаётся постоянным знанием PPO.",
            ["Raises PPO's reward signal for creating new highest blocks. This pushes the learner toward bigger blocks instead of only safer runs."] = "Повышает сигнал награды PPO за создание новых рекордных блоков. Это направляет ученика к более крупным блокам, а не только к более безопасным ранам.",
            ["Improves PPO's survival shaping and danger penalties, making high-focus policies less likely to crash early."] = "Улучшает формирование выживания и штрафы за опасность у PPO, снижая шанс раннего краха политик, нацеленных на рекорды.",
            ["+50% <sprite name=\"insight\" tint=1> from PPO Normal Mode performance per level. This is the late neural payoff node."] = "+50% <sprite name=\"insight\" tint=1> от результата обычного режима PPO за уровень. Это поздний нейронный узел отдачи.",
            ["Boosts <sprite name=\"insight\" tint=1> earned directly from PPO Normal Mode runs. Training mode never feeds this, and long cycles softcap so prestige stays valuable."] = "Увеличивает <sprite name=\"insight\" tint=1>, получаемый напрямую из ранов обычного режима PPO. Режим обучения его не питает, а длинные циклы имеют мягкий потолок, чтобы престиж оставался ценным.",
            ["Offline Engine\", \"While the game is closed, <sprite name=\"chips\" tint=1> and <sprite name=\"insight\" tint=1> continue at a reduced rate based on your current prestige strength."] = "Пока игра закрыта, <sprite name=\"chips\" tint=1> и <sprite name=\"insight\" tint=1> продолжают поступать с пониженной скоростью в зависимости от текущей силы престижа.",
            ["Extends how many closed-game hours can be converted into offline <sprite name=\"chips\" tint=1> and <sprite name=\"insight\" tint=1>."] = "Увеличивает, сколько часов с закрытой игрой можно превратить в офлайн-<sprite name=\"chips\" tint=1> и <sprite name=\"insight\" tint=1>.",
            ["Every hired Agent's bonus effect is 40% stronger per level. Agents become a core engine of faster replays."] = "Бонусный эффект каждого нанятого агента на 40% сильнее за уровень. Агенты становятся ключевым двигателем более быстрых прохождений.",
            ["Upgrades, Agents and Modifiers cost 5% less per level, and the Modifiers requirement needs 15% fewer runs & merges per level. At level 5, Datacenter costs are 20% cheaper."] = "Улучшения, агенты и модификаторы стоят на 5% дешевле за уровень, а требование модификаторов нужно на 15% меньше ранов и слияний за уровень. На 5 уровне расходы центра данных на 20% дешевле.",
            ["Shortens the result-evaluation pause after every PPO Training run by 15% per level, so Training mode gets through its runs much faster."] = "Сокращает паузу оценки результата после каждого рана обучения PPO на 15% за уровень, так что режим обучения проходит раны намного быстрее.",
            ["Unlock PPO to begin the prestige layer."] = "Откройте PPO, чтобы начать слой престижа.",
            ["Prestige for"] = "Награда за престиж:",
            ["You can keep playing PPO in Playing Mode to increase <sprite name=\"insight\" tint=1>."] = "Вы можете продолжать играть PPO в игровом режиме, чтобы увеличить <sprite name=\"insight\" tint=1>.",
            ["Current effect"] = "Текущий эффект",
            ["Game"] = "Игра",
            ["Gameplay"] = "Геймплей",
            ["Selected"] = "Выбрано",
            ["Deselected"] = "Отменено",
            ["Needs modifiers"] = "Нужны модификаторы",
            ["Needs all\nModifiers"] = "Нужны все\nмодификаторы",
            ["Unlock\nUpgrades"] = "Открыть в\nУлучшениях",
            ["Unlock this algorithm to reveal details."] = "Откройте этот алгоритм, чтобы увидеть детали.",
            ["Agents\nLocked"] = "Агенты\nЗаблокированы",
            ["Unlock in\nUpgrades"] = "Открыть в\nУлучшениях",
            ["Bonus slot\nNeeds upgrade"] = "Бонусный слот\nНужно улучшение",
            ["Agents Locked"] = "Агенты заблокированы",
            ["Unlock the Agents menu in Upgrades."] = "Откройте меню агентов в Улучшениях.",
            ["Equipped"] = "Экипирован",
            ["No free slot"] = "Нет свободного слота",
            ["Unequip someone first"] = "Сначала снимите кого-нибудь",
            ["Needs upgrade"] = "Нужно улучшение",
            ["Empty"] = "Пусто",
            ["Modifier Lab Locked"] = "Лаборатория модификаторов заблокирована",
            ["Reach the stage goal in Upgrades to unlock board modifiers. They make runs richer, riskier, and much harder to play optimally by hand."] = "Достигните цели этапа в Улучшениях, чтобы открыть модификаторы поля. Они делают раны богаче, рискованнее и намного сложнее для оптимальной ручной игры.",
            ["Not active"] = "Не активен",
            ["Activate"] = "Активировать",
            ["Upgrade"] = "Улучшить",
            ["Ready: every Modifier is fully purchased."] = "Готово: каждый модификатор полностью куплен.",
            ["PPO model is not initialized yet."] = "Модель PPO ещё не инициализирована.",
            ["Prestige once to open Research."] = "Сделайте престиж, чтобы открыть Исследования.",
            ["Research maxed."] = "Исследования на максимуме.",
            ["Not enough Insight."] = "Недостаточно Insight.",
            ["Not enough <sprite name=\"insight\" tint=1>."] = "Недостаточно <sprite name=\"insight\" tint=1>.",
            ["Requires Seed Capital L1."] = "Требует Стартовый капитал У1.",
            ["Requires Automation Memory L1."] = "Требует Память автоматизации У1.",
            ["Requires Algorithm Archive L1."] = "Требует Архив алгоритмов У1.",
            ["Requires Agent Synergy L1."] = "Требует Синергию агентов У1.",
            ["Requires Bulk Discount L1."] = "Требует Оптовую скидку У1.",
            ["Requires PPO Bootcamp L1."] = "Требует PPO Bootcamp У1.",
            ["Requires Evaluation Efficiency L1."] = "Требует Эффективность оценки У1.",
            ["Requires PPO Memory L1."] = "Требует Память PPO У1.",
            ["Requires High Focus L1."] = "Требует Высокий фокус У1.",
            ["Requires Stability Model L1."] = "Требует Модель стабильности У1.",
            ["Requires Insight Amplifier L1."] = "Требует Усилитель Insight У1.",
            ["Requires Passive Insight L1."] = "Требует Пассивный Insight У1.",
            ["Requires Offline Engine L1."] = "Требует Офлайн-движок У1.",
            ["Ready to buy."] = "Готово к покупке.",
            ["Not enough chips"] = "Недостаточно фишек",
            ["PPO requires every Modifier maxed"] = "PPO требует каждый модификатор на максимуме",
            ["Unlock Agents first"] = "Сначала откройте агентов",
            ["Modifier Lab requirements not met"] = "Требования лаборатории модификаторов не выполнены",
            ["Run PPO in Normal mode first"] = "Сначала запустите PPO в обычном режиме",
            ["Agents menu unlocked"] = "Меню агентов открыто",
            ["Agent unavailable"] = "Агент недоступен",
            ["No free agent slot"] = "Нет свободного слота агента",
            ["Speed level"] = "Уровень скорости",
            ["Risk level"] = "Уровень риска",
            ["Chip yield level"] = "Уровень доходности фишек",
            ["Next preview"] = "Предпросмотр",
            ["Scaling frequency upgrade unavailable"] = "Улучшение частоты масштабирования недоступно",
            ["Profitable ending upgrade unavailable"] = "Улучшение прибыльного финала недоступно",
            ["Modifier upgrade unavailable"] = "Улучшение модификатора недоступно",
            ["<b>Auto Buy</b>"] = "<b>Автопокупка</b>",
            ["Auto Buy"] = "Автопокупка",
            ["Enabled"] = "Включено",
            ["Disabled"] = "Выключено",
            ["FPS --"] = "FPS --",
            ["Policy loss"] = "Потеря политики",
            ["Policy loss:"] = "Потеря политики:",
            ["Value loss"] = "Потеря ценности",
            ["Value loss:"] = "Потеря ценности:",
            ["Entropy"] = "Энтропия",
            ["Entropy:"] = "Энтропия:",
            ["Updates"] = "Обновления",
            ["Updates:"] = "Обновления:",
            ["PPO is trained, prestige reset unlocked."] = "PPO обучен, сброс престижа открыт.",
            ["Gain:"] = "Прирост:",
            ["You made"] = "Вы заработали",
            ["while you were offline."] = "пока были офлайн.",
            ["Offline reward time:"] = "Время офлайн-награды:",
            ["You have to finish PPO Training to unlock prestige."] = "Чтобы открыть престиж, нужно завершить обучение PPO.",
            ["In case of a Prestige reset, the game will restart. All <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, upgrades, Agents, and Modifiers will be lost.\n\n" +
                "However, existing <sprite name=\"insight\" tint=1> and purchased research will remain, which will make further resets progressively more valuable.\n\n" +
                "<b>It is recommended to use PPO in Normal Mode before resetting to gain <sprite name=\"insight\" tint=1> multiplier.</b>"] =
            "При сбросе престижа игра начнётся заново. Все <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, улучшения, агенты и модификаторы будут потеряны.\n\n" +
            "Однако имеющийся <sprite name=\"insight\" tint=1> и купленные исследования сохранятся, делая последующие сбросы всё более ценными.\n\n" +
            "<b>Рекомендуется использовать PPO в обычном режиме перед сбросом, чтобы повысить множитель <sprite name=\"insight\" tint=1>.</b>",
            ["Reset for"] = "Награда за сброс:",
            ["Datacenter"] = "Центр обработки данных",
            ["Compute Allocation"] = "Распределение вычислений",
            ["Server Racks"] = "Серверные стойки",
            ["Facility Upgrades"] = "Улучшения объекта",
            ["CPU Rack"] = "Стойка CPU",
            ["GPU Rack"] = "Стойка GPU",
            ["TPU Pod"] = "TPU Pod",
            ["Neural Fabric"] = "Neural Fabric",
            ["Power Grid"] = "Энергосеть",
            ["Cooling Loop"] = "Контур охлаждения",
            ["Fabric Interconnect"] = "Fabric Interconnect",
            ["Commodity silicon. Cheap, dependable, slow."] = "Серийный кремний. Дёшево, надёжно, медленно.",
            ["Parallel throughput for tensor math."] = "Параллельная пропускная способность для тензорной математики.",
            ["Tensor pods. Systolic arrays with obscene throughput."] = "Тензорные поды. Систолические массивы с непристойной пропускной способностью.",
            ["Experimental wafer-scale mesh. Draws its own weather."] = "Экспериментальная сеть масштаба пластины. Создаёт собственную погоду.",
            ["Dedicated feeders and battery buffer."] = "Выделенные питатели и буфер аккумуляторов.",
            ["Immersion + rear-door heat exchangers."] = "Иммерсионное охлаждение и теплообменники в задней двери.",
            ["Low-latency mesh between pods."] = "Сеть с низкой задержкой между подами.",
            ["Total compute"] = "Всего вычислений",
            ["allocated"] = "выделено",
            ["units"] = "ед.",
            ["unit"] = "ед.",
            ["total"] = "всего",
            ["Training Cluster"] = "Кластер обучения",
            ["Analysis Node"] = "Узел анализа",
            ["Market Bots"] = "Рыночные боты",
            ["Passive PPO frame. Shortens the prestige cycle."] = "Пассивные кадры PPO. Сокращают цикл престижа.",
            ["Passively generates <sprite name=\"insight\" tint=1> (softcapped)."] = "Пассивно генерирует <sprite name=\"insight\" tint=1> (с мягким потолком).",
            ["Producing <sprite name=\"chips\" tint=1> gets an income multiplier."] = "Производство <sprite name=\"chips\" tint=1> получает множитель дохода.",
            ["Requires every Modifier maxed"] = "Требует каждый модификатор на максимуме",
            ["Agent bonuses"] = "Бонусы агентов",
            ["Shop prices"] = "Цены в магазине",
            ["Training eval pause"] = "Пауза оценки обучения",
            ["Prestige Insight"] = "Insight престижа",
            ["Start chips"] = "Стартовые фишки",
            ["Chip rewards"] = "Награды в фишках",
            ["No automation is remembered yet."] = "Автоматизация ещё не запомнена.",
            ["Auto Solve unlock remembered."] = "Открытие Автоигры запомнено.",
            ["Auto Restart unlock and 50 tokens remembered."] = "Открытие Автоперезапуска и 50 токенов запомнены.",
            ["Auto Solve, Auto Restart, tokens, and Solver Tuning remembered."] = "Автоигра, Автоперезапуск, токены и Настройка солвера запомнены.",
            ["No algorithms remembered yet."] = "Алгоритмы ещё не запомнены.",
            ["Start with RAND."] = "Начните с RAND.",
            ["Start with RAND and MERG."] = "Начните с RAND и MERG.",
            ["Start with RAND, MERG, and BAL."] = "Начните с RAND, MERG и BAL.",
            ["Start with RAND, MERG, BAL, and HEUR."] = "Начните с RAND, MERG, BAL и HEUR.",
            ["Insight Amplifier"] = "Усилитель Insight",
            ["Seed Capital"] = "Стартовый капитал",
            ["Automation Memory"] = "Память автоматизации",
            ["Algorithm Archive"] = "Архив алгоритмов",
            ["Yield Theory"] = "Теория доходности",
            ["PPO Bootcamp"] = "PPO Bootcamp",
            ["PPO Memory"] = "Память PPO",
            ["High Focus"] = "Высокий фокус",
            ["Stability Model"] = "Модель стабильности",
            ["Insight Extractor"] = "Экстрактор Insight",
            ["Passive Insight"] = "Пассивный Insight",
            ["Offline Engine"] = "Офлайн-движок",
            ["Offline Buffer"] = "Офлайн-буфер",
            ["Agent Synergy"] = "Синергия агентов",
            ["Bulk Discount"] = "Оптовая скидка",
            ["Evaluation Efficiency"] = "Эффективность оценки",
            ["Insight"] = "Insight",
            ["RAND selected"] = "RAND выбран",
            ["RAND deselected"] = "RAND отменён",
            ["BAL selected"] = "BAL выбран",
            ["BAL deselected"] = "BAL отменён",
            ["BAL tuning updated"] = "Настройка BAL обновлена",
            ["BAL tuning reset"] = "Настройка BAL сброшена",
            ["HEUR selected"] = "HEUR выбран",
            ["HEUR deselected"] = "HEUR отменён",
            ["HEUR tuning updated"] = "Настройка HEUR обновлена",
            ["HEUR tuning reset"] = "Настройка HEUR сброшена",
            ["COMBO selected"] = "COMBO выбран",
            ["COMBO deselected"] = "COMBO отменён",
            ["COMBO tuning updated"] = "Настройка COMBO обновлена",
            ["COMBO tuning reset"] = "Настройка COMBO сброшена",
            ["LOOK selected"] = "LOOK выбран",
            ["LOOK deselected"] = "LOOK отменён",
            ["LOOK tuning updated"] = "Настройка LOOK обновлена",
            ["LOOK tuning reset"] = "Настройка LOOK сброшена",
            ["MOCA selected"] = "MOCA выбран",
            ["MOCA deselected"] = "MOCA отменён",
            ["MOCA tuning updated"] = "Настройка MOCA обновлена",
            ["MOCA tuning reset"] = "Настройка MOCA сброшена",
            ["PLAN selected"] = "PLAN выбран",
            ["PLAN deselected"] = "PLAN отменён",
            ["PLAN tuning updated"] = "Настройка PLAN обновлена",
            ["PLAN tuning reset"] = "Настройка PLAN сброшена",
            ["Export"] = "Экспорт",
            ["Import"] = "Импорт",
            ["To import your game data, paste in your export text.\n\n" +
                "Importing will overwrite all progress in all of your saves, and it will not be possible to recover old progress."] =
            "Чтобы импортировать игровые данные, вставьте свой текст экспорта.\n\n" +
            "Импорт перезапишет весь прогресс во всех ваших сохранениях, и восстановить прежний прогресс будет невозможно.",

            // ---- How To Play + menu help ---------------------------------------------------------
            ["This part of the game is still locked. Keep progressing to reveal this help section."] = "Эта часть игры ещё заблокирована. Продолжайте прогресс, чтобы открыть этот раздел справки.",
            ["Welcome!"] = "Добро пожаловать!",
            ["Basics"] = "Основы",
            ["Purpose"] = "Назначение",
            ["Priorities"] = "Приоритеты",
            ["Tip"] = "Совет",
            ["Usage"] = "Использование",
            ["Reward rules"] = "Правила наград",
            ["Income formula"] = "Формула дохода",
            ["Speed formula"] = "Формула скорости",
            ["Synergy formula"] = "Формула синергии",
            ["Main formula"] = "Основная формула",
            ["Allocations"] = "Распределения",
            ["Allocation formulas"] = "Формулы распределения",
            ["Main multipliers"] = "Основные множители",
            ["Layer progression"] = "Прогрессия слоёв",
            ["Prestige Reset"] = "Сброс престижа",
            ["PPO"] = "PPO",
            ["<sprite name=\"insight\" tint=1> reward formula"] = "Формула награды <sprite name=\"insight\" tint=1>",
            ["General:\n" +
                    "<b>moveInterval = max(minInterval, speedInterval x solverPacing x computePacing x agentPacing x trainingPacing)</b>\n\n" +
                    "For heavy search solvers:\n" +
                    "<b>computePacing = max(0.35, 1 - 0.11 x ComputeSpeedLevel)</b>"] =
                "Общее:\n" +
                "<b>moveInterval = max(minInterval, speedInterval x solverPacing x computePacing x agentPacing x trainingPacing)</b>\n\n" +
                "Для ресурсоёмких поисковых солверов:\n" +
                "<b>computePacing = max(0.35, 1 - 0.11 x ComputeSpeedLevel)</b>",
            ["Catalyst Stack doubles merge rewards.\n\n" +
                    "<b>salvage = ceil(score x salvageShare x 0.25) x stage x globalIncome</b>\n\n" +
                    "Because runs become longer and more flexible, planning solvers and PPO also become more valuable."] =
                "Catalyst Stack удваивает награды за слияния.\n\n" +
                "<b>salvage = ceil(score x salvageShare x 0.25) x stage x globalIncome</b>\n\n" +
                "Поскольку раны становятся длиннее и гибче, планирующие солверы и PPO также становятся ценнее.",
            ["<b><sprite name=\"insight\" tint=1> ~= round((1 + performance x 1.25 + cycleCarry) x usage x insightMultiplier)</b>\n\n" +
                    "Performance is based on PPO score and highest block. Usage comes from Normal Mode runs and frames."] =
                "<b><sprite name=\"insight\" tint=1> ~= round((1 + performance x 1.25 + cycleCarry) x usage x insightMultiplier)</b>\n\n" +
                "Результат зависит от очков PPO и наивысшего блока. Использование складывается из ранов и кадров обычного режима.",

            ["The core gameplay is very simple. Place blocks into one of the four stacks.\n\n" +
                    "You can merge two blocks of the same value by placing one on top of the other, earning more score and a larger in-game currency reward <sprite name=\"chips\" tint=1>.\n\n" +
                    "Always make sure there is at least one free space available, and try to keep your runs going for as long as possible. A run ends when the next block can no longer be placed anywhere."] =
                "Основной геймплей очень прост. Ставьте блоки в один из четырёх стеков.\n\n" +
                "Два блока одинакового значения можно слить, поставив один на другой, получая больше очков и большую награду игровой валютой <sprite name=\"chips\" tint=1>.\n\n" +
                "Всегда следите, чтобы был хотя бы один свободный слот, и старайтесь тянуть раны как можно дольше. Ран заканчивается, когда следующий блок уже некуда поставить.",
            ["The gameplay changes early on, when algorithms begin playing instead of you. From that point forward, your job is to spend your income on upgrades that make future runs faster, longer, and more valuable."] =
                "Геймплей рано меняется, когда вместо вас начинают играть алгоритмы. С этого момента ваша задача — тратить доход на улучшения, которые делают будущие раны быстрее, длиннее и ценнее.",
            ["The stage multiplier starts at 1x, increases to 5x after unlocking Agents, and reaches 24x after unlocking Modifiers. Because of this, unlocking a new layer is usually more valuable than buying another standard income upgrade."] =
                "Множитель этапа начинается с 1x, растёт до 5x после открытия агентов и достигает 24x после открытия модификаторов. Поэтому открытие нового слоя обычно ценнее, чем покупка очередного обычного улучшения дохода.",
            ["Algorithms (solvers) automatically play the game for you.\n\n" +
                    "When Auto Solve is enabled, the selected solver places the blocks. If no solver is selected, the run remains Manual."] =
                "Алгоритмы (солверы) играют за вас автоматически.\n\n" +
                "Когда включена Автоигра, выбранный солвер ставит блоки. Если солвер не выбран, ран остаётся ручным.",
            ["Each solver prioritizes different values when making decisions, so comparing them is worthwhile.\n\n" +
                    "Their behavior can be adjusted after unlocking Tuning. Tuning parameters can be modified using sliders, but their effects may also negatively impact gameplay.\n\n" +
                    "Besides search depth, the biggest difference between solvers is their speed. Solver speed can be upgraded in several places throughout the game."] =
                "Каждый солвер при принятии решений отдаёт приоритет разным значениям, поэтому их стоит сравнивать.\n\n" +
                "Их поведение можно настроить после открытия Настройки. Параметры меняются ползунками, но их эффекты могут и ухудшить игру.\n\n" +
                "Помимо глубины поиска, главное различие между солверами — их скорость. Скорость солвера улучшается в нескольких местах игры.",
            ["The ultimate goal is to unlock PPO, which is a learning algorithm. It starts out weak because it doesn't understand the game's rules, so it must first be trained in Training Mode.\n\n" +
                    "Later, it becomes the gateway to Prestige and permanent progression.\n\n" +
                    "<b>The requirements to unlock it only become achievable later in the game.</b>"] =
                "Конечная цель — открыть PPO, обучающийся алгоритм. Он слаб в начале, потому что не понимает правил игры, поэтому сначала его нужно обучить в режиме обучения.\n\n" +
                "Позже он становится воротами к престижу и постоянному прогрессу.\n\n" +
                "<b>Условия его открытия становятся достижимы только позже в игре.</b>",
            ["This is the primary place to spend <sprite name=\"chips\" tint=1> during the early game.\n\n" +
                    "Here you unlock automation, speed up and expand gameplay, and increase your income generation.\n\n" +
                    "<b>Some upgrades have little impact on their own but become much stronger when combined with others.</b>"] =
                "Это главное место, где на раннем этапе тратятся <sprite name=\"chips\" tint=1>.\n\n" +
                "Здесь вы открываете автоматизацию, ускоряете и расширяете геймплей и повышаете генерацию дохода.\n\n" +
                "<b>Некоторые улучшения сами по себе слабы, но становятся гораздо сильнее в сочетании с другими.</b>",
            ["It's recommended to purchase automation upgrades first so you can start focusing on management as soon as possible."] =
                "Рекомендуется сначала купить улучшения автоматизации, чтобы как можно раньше сосредоточиться на управлении.",
            ["<b>Keep in mind that Auto Restart consumes <sprite name=\"token\" tint=1>, and cannot function without it.</b>"] =
                "<b>Помните, что автоперезапуск расходует <sprite name=\"token\" tint=1> и без них не работает.</b>",
            ["<b>Unlocking Agents increases the game to a 5x stage multiplier.</b>"] =
                "<b>Открытие агентов повышает множитель этапа до 5x.</b>",
            ["Agents provide active loadout bonuses.\n\n" +
                    "Simply purchasing an Agent isn't enough to make it available, it must also be selected. By default, you can equip two Agents at once, and this limit can be increased through upgrades."] =
                "Агенты дают активные бонусы экипировки.\n\n" +
                "Просто купить агента недостаточно — его нужно ещё и выбрать. По умолчанию можно экипировать двух агентов одновременно, и этот предел повышается улучшениями.",
            ["<b>The combination of equipped Agents determines which aspect of a run becomes more efficient, since most Agents improve a specific reward source instead of multiplying the entire economy.</b>"] =
                "<b>Комбинация экипированных агентов определяет, какой аспект рана станет эффективнее, ведь большинство агентов улучшают конкретный источник наград, а не умножают всю экономику.</b>",
            ["Some Agents have little effect on their own, but become significantly stronger when combined with other Agents and upgrades."] =
                "Некоторые агенты сами по себе почти не влияют, но становятся заметно сильнее в сочетании с другими агентами и улучшениями.",
            ["Choose Agents based on what's currently limiting your progress. If runs end too quickly, prioritize stability. Once your runs are long enough, score, high-block, or merge rewards become more valuable."] =
                "Выбирайте агентов по тому, что сейчас ограничивает ваш прогресс. Если раны заканчиваются слишком быстро, отдавайте приоритет стабильности. Когда раны достаточно длинные, ценнее становятся награды за очки, высокий блок или слияния.",
            ["<b>Unlocking Modifiers increases the game to a 24x stage multiplier.</b>"] =
                "<b>Открытие модификаторов повышает множитель этапа до 24x.</b>",
            ["Modifiers change the rules of future runs. They provide a higher ceiling, a more flexible board, and more tools for advanced solvers to take advantage of."] =
                "Модификаторы меняют правила будущих ранов. Они дают более высокий потолок, более гибкое поле и больше инструментов, которыми могут пользоваться продвинутые солверы.",
            ["Some Modifiers grant actions that can be freely used during gameplay. Every Modifier can also be used in Manual Mode."] =
                "Некоторые модификаторы дают действия, которые можно свободно использовать во время игры. Каждый модификатор также можно использовать в ручном режиме.",
            ["Research is responsible for speeding up and deepening future playthroughs, and it is also where Prestige Reset becomes available.\n\n" +
                    "Here you can purchase permanent upgrades that make gameplay easier, but they require <sprite name=\"insight\" tint=1>.\n\n"] =
                "Исследования отвечают за ускорение и углубление будущих прохождений, и именно здесь становится доступен сброс престижа.\n\n" +
                "Здесь можно покупать постоянные улучшения, облегчающие игру, но им нужен <sprite name=\"insight\" tint=1>.\n\n",
            ["<sprite name=\"insight\" tint=1> is generated by letting PPO play in Normal Mode.\n\n" +
                    "<b>You must perform a Prestige Reset to claim your <sprite name=\"insight\" tint=1>.</b>"] =
                "<sprite name=\"insight\" tint=1> вырабатывается, когда PPO играет в обычном режиме.\n\n" +
                "<b>Чтобы получить свой <sprite name=\"insight\" tint=1>, нужно выполнить сброс престижа.</b>",
            ["A Prestige Reset removes all accumulated <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, Upgrades, Agents, and Modifiers.\n\n" +
                    "However, your <sprite name=\"insight\" tint=1>, purchased Research, permanent PPO knowledge, and Datacenter progress are preserved."] =
                "Сброс престижа удаляет все накопленные <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, улучшения, агентов и модификаторы.\n\n" +
                "Однако ваш <sprite name=\"insight\" tint=1>, купленные исследования, постоянные знания PPO и прогресс центра данных сохраняются.",
            ["Datacenter is a permanent compute layer that unlocks after your 5th Prestige Reset.\n\n" +
                    "Every upgrade here accelerates different stages of gameplay.\n\n" +
                    "This layer uses <sprite name=\"chips\" tint=1> as its currency again, meaning the production accumulated by PPO in Normal Mode is no longer lost after Prestige Reset."] =
                "Центр обработки данных — это постоянный вычислительный слой, открывающийся после 5-го сброса престижа.\n\n" +
                "Каждое улучшение здесь ускоряет разные стадии игры.\n\n" +
                "Этот слой снова использует <sprite name=\"chips\" tint=1> как валюту, поэтому производство, накопленное PPO в обычном режиме, больше не теряется после сброса престижа.",
            ["<b>Be sure to spend your accumulated <sprite name=\"chips\" tint=1> before performing a Prestige Reset, otherwise they will be lost.</b>"] =
                "<b>Обязательно потратьте накопленные <sprite name=\"chips\" tint=1> перед сбросом престижа, иначе они пропадут.</b>",
            ["You can purchase Server Racks and Facility Upgrades, then allocate the resulting compute capacity however you like between passive PPO training, passive <sprite name=\"insight\" tint=1> generation, or a <sprite name=\"chips\" tint=1> income multiplier."] =
                "Можно покупать серверные стойки и улучшения объекта, а полученную вычислительную мощность распределять как угодно между пассивным обучением PPO, пассивной генерацией <sprite name=\"insight\" tint=1> или множителем дохода <sprite name=\"chips\" tint=1>.",

            ["Place the blocks into one of the four stacks.\n\n" +
                "By placing two blocks with the same value on top of each other, you can merge them, earning more score and receiving a larger in-game currency <sprite name=\"chips\" tint=1> reward.\n\n" +
                "Make sure to always keep at least one free space available, and try to make your runs last as long as possible.\n\n" +
                "The gameplay changes early on, when algorithms start playing instead of you. From that point onward, your role is to purchase various upgrades and manage them.\n\n" +
                "<b>You can find details about every important game feature in Settings > How to Play menu.</b>"] =
                "Ставьте блоки в один из четырёх стеков.\n\n" +
                "Поставив два блока одинакового значения друг на друга, вы сливаете их, получая больше очков и большую награду игровой валютой <sprite name=\"chips\" tint=1>.\n\n" +
                "Всегда держите хотя бы один свободный слот и старайтесь тянуть раны как можно дольше.\n\n" +
                "Геймплей рано меняется, когда вместо вас начинают играть алгоритмы. С этого момента ваша роль — покупать разные улучшения и управлять ими.\n\n" +
                "<b>Подробности о каждой важной функции игры — в меню Настройки > Как играть.</b>",
            ["Algorithms are responsible for playing the game automatically for you.\n\n" +
                "Each solver prioritizes different values when making decisions, so it's worth comparing them. Their behavior can be tuned once Tuning is unlocked.\n\n" +
                "The ultimate goal is to unlock PPO, which is a learning algorithm. The requirements for unlocking it can only be met later in the game."] =
                "Алгоритмы играют в игру за вас автоматически.\n\n" +
                "Каждый солвер при решениях отдаёт приоритет разным значениям, поэтому их стоит сравнивать. Их поведение можно настроить после открытия Настройки.\n\n" +
                "Конечная цель — открыть PPO, обучающийся алгоритм. Условия его открытия выполнимы только позже в игре.",
            ["Upgrades are the early-game progression layer based on <sprite name=\"chips\" tint=1>.\n\n" +
                "This is where you unlock automation, speed up and expand gameplay, and increase your income generation.\n\n" +
                "It's generally best to prioritize automation upgrades so you can focus on managing your run as early as possible.\n\n" +
                "<b>Keep in mind that Auto Restart consumes <sprite name=\"token\" tint=1>.</b>"] =
                "Улучшения — это слой прогресса раннего этапа на основе <sprite name=\"chips\" tint=1>.\n\n" +
                "Здесь вы открываете автоматизацию, ускоряете и расширяете геймплей и повышаете генерацию дохода.\n\n" +
                "Обычно лучше сначала брать улучшения автоматизации, чтобы как можно раньше сосредоточиться на управлении раном.\n\n" +
                "<b>Помните, что автоперезапуск расходует <sprite name=\"token\" tint=1>.</b>",
            ["Agents provide active loadout bonuses.\n\n" +
                "Not every owned Agent is active: the combination equipped in your slots determines which aspects of your run become more effective."] =
                "Агенты дают активные бонусы экипировки.\n\n" +
                "Не каждый имеющийся агент активен: комбинация, экипированная в ваших слотах, определяет, какие аспекты рана станут эффективнее.",
            ["Modifiers change the rules of future runs. They unlock new possibilities and increase your income, but they also make the board more complex.\n\n" +
                "Some Modifiers can be upgraded multiple times.\n\n" +
                "<b>Purchasing every Modifier unlocks the PPO algorithm, marking the gateway to the endgame.</b>"] =
                "Модификаторы меняют правила будущих ранов. Они открывают новые возможности и повышают доход, но делают поле сложнее.\n\n" +
                "Некоторые модификаторы можно улучшать несколько раз.\n\n" +
                "<b>Покупка каждого модификатора открывает алгоритм PPO — ворота в финал игры.</b>",
            ["Research is the progression layer that unlocks the ability to Prestige Reset.\n\n" +
                "Here, you can purchase permanent upgrades that make gameplay easier and faster, but they require <sprite name=\"insight\" tint=1>.\n\n" +
                "<sprite name=\"insight\" tint=1> is generated by running the PPO algorithm in Normal Mode.\n\n" +
                "To claim your <sprite name=\"insight\" tint=1>, you must perform a Prestige Reset. You can find details in the Console."] =
                "Исследования — это слой прогресса, открывающий возможность сброса престижа.\n\n" +
                "Здесь можно покупать постоянные улучшения, делающие игру легче и быстрее, но им нужен <sprite name=\"insight\" tint=1>.\n\n" +
                "<sprite name=\"insight\" tint=1> вырабатывается, когда алгоритм PPO работает в обычном режиме.\n\n" +
                "Чтобы получить свой <sprite name=\"insight\" tint=1>, нужно выполнить сброс престижа. Подробности — в Консоли.",
            ["Datacenter is a persistent compute layer that speeds up your Prestiges.\n\n" +
                "Here, <sprite name=\"chips\" tint=1> becomes the currency again, meaning the production accumulated in PPO Normal Mode is no longer wasted when you perform a Prestige Reset.\n\n" +
                "<b>Be sure to spend your accumulated <sprite name=\"chips\" tint=1> before resetting, as any unspent amount will be lost.</b>\n\n" +
                "You can purchase Server Racks and Facility Upgrades, then allocate the resulting compute capacity however you like: to passive PPO training, passive <sprite name=\"insight\" tint=1> generation, or a <sprite name=\"chips\" tint=1> production multiplier."] =
                "Центр обработки данных — это постоянный вычислительный слой, ускоряющий ваши престижи.\n\n" +
                "Здесь <sprite name=\"chips\" tint=1> снова становятся валютой, поэтому производство, накопленное в обычном режиме PPO, больше не пропадает при сбросе престижа.\n\n" +
                "<b>Обязательно потратьте накопленные <sprite name=\"chips\" tint=1> перед сбросом, так как всё непотраченное пропадёт.</b>\n\n" +
                "Можно покупать серверные стойки и улучшения объекта, а полученную вычислительную мощность распределять как угодно: на пассивное обучение PPO, пассивную генерацию <sprite name=\"insight\" tint=1> или множитель производства <sprite name=\"chips\" tint=1>.",
            ["Here you can see detailed data on how your runs perform during the current Prestige cycle.\n\n" +
                "You can view your highest score, best median performance, average run duration, and results for each solver.\n\n" +
                "<b>Measure how a new algorithm, Tuning, or any other modification affects your performance.</b>"] =
                "Здесь видны подробные данные о том, как ваши раны показывают себя в текущем цикле престижа.\n\n" +
                "Можно посмотреть наивысший счёт, лучшую медианную результативность, среднюю длительность рана и результаты по каждому солверу.\n\n" +
                "<b>Оцените, как новый алгоритм, настройка или любое другое изменение влияют на вашу результативность.</b>",
            ["Here you can track your best results achieved throughout your playtime, along with a summary of your overall progress. You can also see which goals you have already completed.\n\n" +
                "<b>Some milestones grant permanent rewards or cosmetic unlocks.</b>"] =
                "Здесь можно отслеживать лучшие результаты за всё время игры вместе со сводкой общего прогресса. Также видно, какие цели вы уже выполнили.\n\n" +
                "<b>Некоторые вехи дают постоянные награды или косметические открытия.</b>",

            // ---- Dynamically-composed labels + datacenter allocation bodies ----------------------
            ["reach Prestige"] = "достигните престижа",
            ["rack FLOPS"] = "FLOPS стойки",
            ["TPU / Fabric"] = "TPU / Fabric",
            ["Effect"] = "Эффект",
            ["Level"] = "Уровень",
            ["Completed goals"] = "Выполненные цели",
            ["Best run"] = "Лучший ран",
            ["moves"] = "ходов",
            ["manual"] = "вручную",
            ["Restart in"] = "Перезапуск через",
            ["Equipped Agents"] = "Экипированные агенты",
            ["Active Modifiers"] = "Активные модификаторы",
            ["Buy all Facility Upgrades"] = "Купите все улучшения объекта",
            ["Offline cap"] = "Офлайн-предел",
            ["Offline efficiency"] = "Офлайн-эффективность",
            ["New-high learning"] = "Обучение рекордам",
            ["Survival shaping"] = "Формирование выживания",
            ["PPO Normal mode at"] = "Обычный режим PPO при",
            ["Start with"] = "Начните с",
            ["cycle frames"] = "кадров цикла",
            ["frames retained"] = "кадров сохранено",
            ["training: +0 chips"] = "обучение: +0 фишек",
            ["Pickaxe"] = "Кирка",
            ["Scrubbed"] = "Удалено",
            ["Merge"] = "Слияние",
            ["Combo"] = "Комбо",
            ["Spent"] = "Потрачено",
            ["Passively trains PPO, which counts as Training Mode frames. <b>PPO learns permanently even when not in use.</b>"] =
                "Пассивно обучает PPO, что засчитывается как кадры режима обучения. <b>PPO учится постоянно, даже когда не используется.</b>",
            ["Passively generates <sprite name=\"insight\" tint=1> at any stage of the game, so using PPO in Normal Mode is no longer required for that."] =
                "Пассивно генерирует <sprite name=\"insight\" tint=1> на любом этапе игры, поэтому использовать PPO в обычном режиме для этого больше не нужно.",
            ["It gives an income multiplier to everything that produces <sprite name=\"chips\" tint=1> in any form."] =
                "Даёт множитель дохода всему, что в любом виде производит <sprite name=\"chips\" tint=1>.",
        };
    }
}
