using System;
using System.Collections.Generic;

namespace StackMerge
{
    // Spanish (Español) translation table. Keys are the exact English source strings; sprite tags are
    // preserved verbatim. Game-specific proper nouns (solver names, PPO) are kept as-is.
    internal static class StackMergeLocalizationEs
    {
        public static readonly Dictionary<string, string> Table = new(StringComparer.Ordinal)
        {
            ["Play"] = "Juego",
            ["Algos"] = "Algos",
            ["Algorithms"] = "Algoritmos",
            ["Upgrades"] = "Mejoras",
            ["Agents"] = "Agentes",
            ["Mods"] = "Mods",
            ["Modifiers"] = "Modificadores",
            ["Research"] = "Investigación",
            ["DC"] = "CD",
            ["Next"] = "Siguiente",
            ["History"] = "Historial",
            ["Achievements"] = "Logros",
            ["Settings"] = "Ajustes",
            ["Locked"] = "Bloqueado",
            ["Unlocked"] = "Desbloqueado",
            ["Select"] = "Elegir",
            ["Deselect"] = "Quitar",
            ["Tune"] = "Ajustar",
            ["Change mode"] = "Cambiar modo",
            ["Buy"] = "Comprar",
            ["Equip"] = "Equipar",
            ["Unequip"] = "Desequipar",
            ["Maxed"] = "Al máximo",
            ["Done"] = "Listo",
            ["New run"] = "Nueva run",
            ["Manual"] = "Manual",
            ["Manual mode"] = "Modo manual",
            ["Auto solving"] = "Resolución auto",
            ["Run ended"] = "Run terminada",
            ["Run time"] = "Duración de la run",
            ["Config info"] = "Info de config",
            ["Import save"] = "Importar partida",
            ["Automatization"] = "Automatización",
            ["Income Bonus"] = "Bono de ingresos",
            ["Passive Production"] = "Producción pasiva",
            ["Solver Speed"] = "Velocidad del solver",
            ["Stack Capacity"] = "Capacidad de pila",
            ["Number of next blocks visible"] = "Número de bloques siguientes visibles",
            ["Higher blocks spawn"] = "Aparición de bloques más altos",
            ["Lab Unlocks"] = "Desbloqueos del lab",
            ["Passive PPO frame reduction"] = "Reducción pasiva de frames PPO",
            ["All Agents"] = "Todos los agentes",
            ["Base <sprite name=\"chips\" tint=1> income"] = "Ingreso base de <sprite name=\"chips\" tint=1>",
            ["Ending profit"] = "Beneficio final",
            ["Merge streak"] = "Racha de fusiones",
            ["Score salvage"] = "Rescate de puntos",
            ["Passive <sprite name=\"chips\" tint=1> / tick"] = "<sprite name=\"chips\" tint=1> pasivos / tick",
            ["Passive tick rate"] = "Frecuencia de tick pasiva",
            ["Active multiplier"] = "Multiplicador activo",
            ["Faster solver"] = "Solver más rápido",
            ["Solver delay"] = "Retardo del solver",
            ["Stack rows"] = "Filas de pila",
            ["Visible blocks"] = "Bloques visibles",
            ["Higher chance"] = "Mayor probabilidad",
            ["Higher frequency"] = "Mayor frecuencia",
            ["Stage Progression"] = "Progreso de fases",
            ["Prestige Console"] = "Consola de prestigio",
            ["Collection"] = "Colección",
            ["PPO Training complete — prestige reset unlocked."] = "Entrenamiento PPO completado — reinicio de prestigio desbloqueado.",
            ["Auto restart needs token"] = "El reinicio auto necesita un token",
            ["The run hasn't started yet."] = "La run aún no ha empezado.",
            ["No moves left — run over"] = "No quedan movimientos — run terminada",
            ["Not enough <sprite name=\"chips\" tint=1>"] = "No hay suficientes <sprite name=\"chips\" tint=1>",
            ["Buy an algorithm first"] = "Compra primero un algoritmo",
            ["Speed upgrade unavailable"] = "Mejora de velocidad no disponible",
            ["Stack upgrade unavailable"] = "Mejora de pila no disponible",
            ["Next preview upgrade unavailable"] = "Mejora de vista previa no disponible",
            ["Income upgrade unavailable"] = "Mejora de ingresos no disponible",
            ["Solver tuning unlocked"] = "Ajuste del solver desbloqueado",
            ["Auto solve updated"] = "Resolución auto actualizada",
            ["Auto restart updated"] = "Reinicio auto actualizado",
            ["Modifier Lab unlocked"] = "Lab de modificadores desbloqueado",
            ["Unlock Agents in Upgrades first"] = "Desbloquea primero los agentes en Mejoras",
            ["Unlock Modifier Lab in Upgrades first"] = "Desbloquea primero el Lab de modificadores en Mejoras",
            ["Finish PPO Training first"] = "Termina primero el entrenamiento PPO",
            ["Unlock PPO to open Research"] = "Desbloquea PPO para abrir la investigación",
            ["Normal mode is still locked."] = "El modo normal sigue bloqueado.",
            ["PPO: Training mode"] = "PPO: modo entrenamiento",
            ["PPO: Normal mode"] = "PPO: modo normal",
            ["Training Mode"] = "Modo entrenamiento",
            ["Normal Mode"] = "Modo normal",
            ["Normal Mode\nLocked"] = "Modo normal\nBloqueado",
            ["PPO Mode Overlay is not assigned."] = "PPO Mode Overlay no está asignado.",
            ["Training: keeps learning, earns no chips.\nNormal: plays for chips like other solvers."] = "Entrenamiento: sigue aprendiendo, no gana chips.\nNormal: juega por chips como los demás solvers.",
            ["Music"] = "Música",
            ["Sound"] = "Sonido",
            ["Enable haptic feedback"] = "Activar respuesta háptica",
            ["Show FPS"] = "Mostrar FPS",
            ["Hide FPS"] = "Ocultar FPS",
            ["Achievement Pop-ups"] = "Avisos de logros",
            ["Hide achievement pop-ups"] = "Ocultar avisos de logros",
            ["Export / Import game"] = "Exportar / importar partida",
            ["Language"] = "Idioma",
            ["Manual controls"] = "Controles manuales",
            ["Tap a stack to place the current next block."] = "Toca una pila para colocar el bloque siguiente actual.",
            ["Equip Miner's Pickaxe, then tap a stack block to remove it."] = "Equipa la Miner's Pickaxe y luego toca un bloque de una pila para quitarlo.",
            ["Equip Queue Scrubber, then tap the first next block to remove it."] = "Equipa el Queue Scrubber y luego toca el primer bloque siguiente para quitarlo.",
            ["Tap a block to remove it with Miner's Pickaxe"] = "Toca un bloque para quitarlo con la Miner's Pickaxe",
            ["Tap the first next block to scrub it"] = "Toca el primer bloque siguiente para eliminarlo",
            ["Miner's Pickaxe equipped"] = "Miner's Pickaxe equipada",
            ["Miner's Pickaxe unequipped"] = "Miner's Pickaxe desequipada",
            ["Queue Scrubber equipped"] = "Queue Scrubber equipado",
            ["Queue Scrubber unequipped"] = "Queue Scrubber desequipado",
            ["Miner's Pickaxe is locked"] = "La Miner's Pickaxe está bloqueada",
            ["Queue Scrubber is locked"] = "El Queue Scrubber está bloqueado",
            ["Miner's Pickaxe has no uses left"] = "No quedan usos de la Miner's Pickaxe",
            ["Queue Scrubber has no uses left"] = "No quedan usos del Queue Scrubber",
            ["No block available for Miner's Pickaxe"] = "No hay bloque disponible para la Miner's Pickaxe",
            ["No next block available for Queue Scrubber"] = "No hay bloque siguiente disponible para el Queue Scrubber",
            ["Modifier unavailable"] = "Modificador no disponible",
            ["Unlocks rule-changing modules that apply to new runs."] = "Desbloquea módulos que cambian las reglas y se aplican a las nuevas runs.",
            ["The solver places blocks faster with each level."] = "El solver coloca bloques más rápido con cada nivel.",
            ["Solver is automatically playing the game."] = "El solver juega automáticamente.",
            ["When the run ends, a new one starts automatically."] = "Cuando la run termina, empieza otra automáticamente.",
            ["The currency for Auto restart."] = "La moneda para el reinicio auto.",
            ["Allows you to modify the solver parameters."] = "Permite modificar los parámetros del solver.",
            ["Another slot so you can use 3 Agents at once."] = "Otra ranura para usar 3 agentes a la vez.",
            ["They give you extra bonuses when you unlock them."] = "Dan bonos extra cuando los desbloqueas.",
            ["Increases the capacity of each stack by 1 per level."] = "Aumenta la capacidad de cada pila en 1 por nivel.",
            ["Shows 1 more upcoming block per level."] = "Muestra 1 bloque próximo más por nivel.",
            ["Increases the chance of spawning higher blocks."] = "Aumenta la probabilidad de generar bloques más altos.",
            ["Slightly increases how often higher blocks appear."] = "Aumenta ligeramente la frecuencia de los bloques más altos.",
            ["Boosts base <sprite name=\"chips\" tint=1> income. Early levels give larger gains."] = "Aumenta el ingreso base de <sprite name=\"chips\" tint=1>. Los primeros niveles dan más.",
            ["Boosts the <sprite name=\"chips\" tint=1> bonus at the end of the runs."] = "Aumenta el bono de <sprite name=\"chips\" tint=1> al final de las runs.",
            ["Boosts the <sprite name=\"chips\" tint=1> earned during merges and runs."] = "Aumenta los <sprite name=\"chips\" tint=1> ganados durante fusiones y runs.",
            ["Shrinks the delay of MOCA and PLAN solvers."] = "Reduce el retardo de los solvers MOCA y PLAN.",
            ["Chips trickle in on a timer, on top of your normal play."] = "Los chips llegan poco a poco por temporizador, además del juego normal.",
            ["Passive Production ticks more often."] = "La producción pasiva hace tick más a menudo.",
            ["Lowers the frame needed in Training Mode."] = "Reduce los frames necesarios en modo entrenamiento.",
            ["Lowers the frames needed for PPO Normal Mode."] = "Reduce los frames necesarios para el modo normal PPO.",
            ["Each level shortens how often Curriculum lowers the PPO requirement."] = "Cada nivel acorta la frecuencia con que el Curriculum reduce el requisito PPO.",
            ["Needs Difficulty L1"] = "Requiere Dificultad N1",
            ["Needs PPO or Bootcamp L5"] = "Requiere PPO o Bootcamp N5",
            ["Needs Curriculum"] = "Requiere Curriculum",
            ["Boosts Passive Production while you're actively playing."] = "Aumenta la producción pasiva mientras juegas activamente.",
            ["Passive yield upgrade unavailable"] = "Mejora de rendimiento pasivo no disponible",
            ["Passive tick rate upgrade unavailable"] = "Mejora de frecuencia pasiva no disponible",
            ["Active multiplier upgrade unavailable"] = "Mejora de multiplicador activo no disponible",
            ["Compute speed upgrade unavailable"] = "Mejora de velocidad de cómputo no disponible",
            ["Stage locked"] = "Fase bloqueada",
            ["Needs algorithm"] = "Requiere algoritmo",
            ["Needs Agents"] = "Requiere agentes",
            ["Stage 1 - Core automation"] = "Fase 1 - Automatización básica",
            ["Stage 2 - Agent acceleration"] = "Fase 2 - Aceleración por agentes",
            ["Stage 3 - Modifier Lab"] = "Fase 3 - Lab de modificadores",
            ["Stage 4 - Machine Learning"] = "Fase 4 - Aprendizaje automático",
            ["Endgame - PPO training"] = "Final - entrenamiento PPO",
            ["Train PPO, then prestige from the Research menu."] = "Entrena PPO y luego haz prestigio desde el menú de investigación.",
            ["PPO is ready to unlock in Algorithms."] = "PPO está listo para desbloquear en Algoritmos.",
            ["Max every Modifier to open the Machine Learning layer."] = "Maximiza cada modificador para abrir la capa de aprendizaje automático.",
            ["Open Agents to start the next stage."] = "Abre los agentes para empezar la siguiente fase.",
            ["Unlock COMBO or LOOK solver to open Agents."] = "Desbloquea el solver COMBO o LOOK para abrir los agentes.",
            ["Unlock COMBO or LOOK solver first."] = "Desbloquea primero el solver COMBO o LOOK.",
            ["Modifiers Lab"] = "Lab de modificadores",
            ["Agents Lab"] = "Lab de agentes",
            ["Stack capacity"] = "Capacidad de pila",
            ["Difficulty"] = "Dificultad",
            ["Speed"] = "Velocidad",
            ["Auto solve"] = "Resolución auto",
            ["Auto restart"] = "Reinicio auto",
            ["Mode"] = "Modo",
            ["Run score"] = "Puntos de la run",
            ["Score"] = "Puntos",
            ["Median"] = "Mediana",
            ["Best"] = "Mejor",
            ["Moves"] = "Movimientos",
            ["Merges"] = "Fusiones",
            ["Current next"] = "Siguiente actual",
            ["Available actions"] = "Acciones disponibles",
            ["Solver"] = "Solver",
            ["Run modifiers"] = "Modificadores de run",
            ["Special blocks"] = "Bloques especiales",
            ["Solver tuning"] = "Ajuste del solver",
            ["+50 tokens"] = "+50 tokens",
            ["Locked in Upgrades."] = "Se desbloquea en Mejoras.",
            ["No tuning available for this solver."] = "No hay ajustes disponibles para este solver.",
            ["Default"] = "Por defecto",
            ["RAND has no tuning. Its identity is pure randomness."] = "RAND no tiene ajustes. Su identidad es el puro azar.",
            ["MERG stays greedy, but these sliders decide how hard it chases immediate value."] = "MERG sigue siendo ávido, pero estos controles deciden cuánto persigue el valor inmediato.",
            ["BAL remains a board stabilizer. Tune how defensive or merge-friendly it should be."] = "BAL sigue siendo un estabilizador del tablero. Ajusta cuán defensivo o proclive a fusionar debe ser.",
            ["HEUR is a weighted score formula. These are the clearest direct knobs."] = "HEUR es una fórmula de puntuación ponderada. Estos son sus ajustes directos más claros.",
            ["LOOK uses HEUR plus a follow-up estimate. Tune its greed and its second-step trust."] = "LOOK usa HEUR más una estimación del siguiente movimiento. Ajusta su avidez y su confianza en el segundo paso.",
            ["MOCA samples futures. Its tuning can spend a little more thinking on rollout depth or sample count."] = "MOCA muestrea futuros. Su ajuste puede dedicar algo más de cálculo a la profundidad de rollout o al número de muestras.",
            ["PLAN searches the visible queue. Tune how much it trusts short plans over current safety."] = "PLAN explora la cola visible. Ajusta cuánto confía en planes cortos frente a la seguridad actual.",
            ["PLAN-5 searches deeper queue lines. Tuning lets you decide whether it should be patient or practical."] = "PLAN-5 explora líneas de cola más profundas. El ajuste decide si debe ser paciente o práctico.",
            ["MOCA+ uses smarter rollouts. Tuning affects both how much it samples and how it values rollout boards."] = "MOCA+ usa rollouts más inteligentes. El ajuste afecta cuánto muestrea y cómo valora los tableros de rollout.",
            ["MCTS builds a tree. These sliders tune search behavior without replacing the tree search identity."] = "MCTS construye un árbol. Estos controles ajustan el comportamiento de búsqueda sin sustituir la identidad de búsqueda en árbol.",
            ["STALL is defensive. Tune how much it sacrifices score to keep the board alive."] = "STALL es defensivo. Ajusta cuántos puntos sacrifica para mantener vivo el tablero.",
            ["COMBO looks for chain setups. Tune how patient it should be while preparing cascades."] = "COMBO busca preparar cadenas. Ajusta cuán paciente debe ser al preparar cascadas.",
            ["PPO trains its own actor-critic network. These nudge the learning hyperparameters within safe bounds."] = "PPO entrena su propia red actor-crítico. Estos ajustan los hiperparámetros de aprendizaje dentro de límites seguros.",
            ["Merge reward"] = "Recompensa de fusión",
            ["Score delta"] = "Delta de puntos",
            ["High block"] = "Bloque alto",
            ["Height penalty"] = "Penalización de altura",
            ["Empty cells"] = "Celdas vacías",
            ["Smoothness"] = "Suavidad",
            ["Danger penalty"] = "Penalización de peligro",
            ["Queue fit"] = "Ajuste de cola",
            ["Follow-up trust"] = "Confianza en el siguiente",
            ["Simulation rounds"] = "Rondas de simulación",
            ["Rollout moves"] = "Movimientos de rollout",
            ["Planning depth"] = "Profundidad de plan",
            ["Future weight"] = "Peso del futuro",
            ["Rollout planning"] = "Planificación de rollout",
            ["Board eval"] = "Eval. del tablero",
            ["Anti-stall"] = "Anti-bloqueo",
            ["Tree visits"] = "Visitas al árbol",
            ["Exploration"] = "Exploración",
            ["Prior bias"] = "Sesgo previo",
            ["Safety cushion"] = "Colchón de seguridad",
            ["Combo setup"] = "Preparación de combo",
            ["Legal moves"] = "Movimientos legales",
            ["Height spread"] = "Dispersión de altura",
            ["Future depth"] = "Profundidad futura",
            ["Gamma (discount)"] = "Gamma (descuento)",
            ["Lambda (GAE)"] = "Lambda (GAE)",
            ["Clip epsilon"] = "Epsilon de clip",
            ["Raises or lowers the reward for immediate merges and cascade size."] = "Sube o baja la recompensa por fusiones inmediatas y el tamaño de las cascadas.",
            ["Changes how much raw score gained by the move matters."] = "Cambia cuánto importan los puntos brutos ganados por el movimiento.",
            ["Pushes the solver toward producing larger top blocks."] = "Empuja al solver a producir bloques superiores más grandes.",
            ["Positive values avoid tall uneven stacks more strongly."] = "Los valores positivos evitan con más fuerza las pilas altas e irregulares.",
            ["Rewards boards with more open cells after the move."] = "Recompensa tableros con más celdas libres tras el movimiento.",
            ["Rewards similar stack heights and penalizes lopsided boards."] = "Recompensa alturas de pila similares y penaliza tableros desequilibrados.",
            ["Penalizes stacks near capacity more strongly."] = "Penaliza con más fuerza las pilas cercanas a la capacidad.",
            ["Lets BAL accept more merge value before spreading out."] = "Permite a BAL aceptar más valor de fusión antes de dispersarse.",
            ["Changes how strongly immediate score gain affects the move score."] = "Cambia cuánto influye la ganancia de puntos inmediata en la puntuación del movimiento.",
            ["Rewards free stack cells after the move."] = "Recompensa las celdas de pila libres tras el movimiento.",
            ["Rewards smoother stack heights and fewer awkward bottlenecks."] = "Recompensa alturas de pila más suaves y menos cuellos de botella incómodos.",
            ["Rewards top blocks that match upcoming queue values."] = "Recompensa los bloques superiores que coinciden con los valores próximos de la cola.",
            ["Raises or lowers the value of immediate merge chains."] = "Sube o baja el valor de las cadenas de fusión inmediatas.",
            ["Makes near-full stacks scarier to the heuristic."] = "Hace que las pilas casi llenas parezcan más peligrosas para la heurística.",
            ["Changes how much the first move's score gain matters."] = "Cambia cuánto importa la ganancia de puntos del primer movimiento.",
            ["Rewards keeping more room open after the first move."] = "Recompensa mantener más espacio libre tras el primer movimiento.",
            ["Changes how much the simulated next move influences the choice."] = "Cambia cuánto influye el siguiente movimiento simulado en la elección.",
            ["Rewards stack tops that line up with visible upcoming blocks."] = "Recompensa las cimas de pila alineadas con los bloques próximos visibles.",
            ["Punishes positions that are close to stalling."] = "Castiga las posiciones cercanas al bloqueo.",
            ["Adjusts how many futures are sampled for each legal move."] = "Ajusta cuántos futuros se muestrean por cada movimiento legal.",
            ["Adjusts how many moves each future is played forward."] = "Ajusta cuántos movimientos se juega hacia adelante cada futuro.",
            ["Changes the immediate score bias inside rollout evaluation."] = "Cambia el sesgo de puntos inmediato dentro de la evaluación de rollout.",
            ["Rewards futures that leave more cells open."] = "Recompensa los futuros que dejan más celdas libres.",
            ["Makes dangerous simulated boards less attractive."] = "Hace menos atractivos los tableros simulados peligrosos.",
            ["Rewards rollouts that keep useful top blocks for the visible queue."] = "Recompensa los rollouts que conservan bloques superiores útiles para la cola visible.",
            ["Shifts how many visible queued blocks the search tries to use."] = "Ajusta cuántos bloques visibles en cola intenta usar la búsqueda.",
            ["Changes how strongly future planned moves affect the first move."] = "Cambia cuánto afectan los movimientos planeados futuros al primer movimiento.",
            ["Rewards stack tops that match upcoming values."] = "Recompensa las cimas de pila que coinciden con los valores próximos.",
            ["Rewards planned lines that keep space available."] = "Recompensa las líneas planeadas que mantienen espacio disponible.",
            ["Penalizes plans that leave near-full stacks."] = "Penaliza los planes que dejan pilas casi llenas.",
            ["Shifts how many queued blocks the search tries to use."] = "Ajusta cuántos bloques en cola intenta usar la búsqueda.",
            ["Changes how strongly deeper planned scores affect the first move."] = "Cambia cuánto afectan las puntuaciones planeadas más profundas al primer movimiento.",
            ["Rewards preserving useful stack tops for upcoming blocks."] = "Recompensa conservar cimas de pila útiles para los bloques próximos.",
            ["Rewards plans that leave more board room."] = "Recompensa los planes que dejan más espacio en el tablero.",
            ["Penalizes risky deep plans more strongly."] = "Penaliza con más fuerza los planes profundos arriesgados.",
            ["Adjusts how many smart futures are sampled for each move."] = "Ajusta cuántos futuros inteligentes se muestrean por movimiento.",
            ["Adjusts how far smart futures are played forward."] = "Ajusta hasta dónde se juegan los futuros inteligentes.",
            ["Adjusts how much queue planning each rollout uses."] = "Ajusta cuánta planificación de cola usa cada rollout.",
            ["Changes how much the final simulated board shape matters."] = "Cambia cuánto importa la forma final del tablero simulado.",
            ["Rewards futures that preserve legal moves and escape routes."] = "Recompensa los futuros que preservan movimientos legales y vías de escape.",
            ["Adjusts how many tree iterations are spent per decision."] = "Ajusta cuántas iteraciones de árbol se usan por decisión.",
            ["Higher values try less-proven branches more often."] = "Los valores más altos prueban ramas menos probadas más a menudo.",
            ["Changes how strongly heuristic prior scores guide the tree."] = "Cambia cuánto guían al árbol las puntuaciones previas heurísticas.",
            ["Adjusts how far rollouts play from a tree node."] = "Ajusta hasta dónde juegan los rollouts desde un nodo del árbol.",
            ["Rewards tree lines that leave room and legal moves."] = "Recompensa las líneas del árbol que dejan espacio y movimientos legales.",
            ["Rewards lines that create potential chain merges."] = "Recompensa las líneas que crean posibles fusiones en cadena.",
            ["Rewards positions with multiple available stacks."] = "Recompensa las posiciones con varias pilas disponibles.",
            ["Rewards spare capacity after each move."] = "Recompensa la capacidad libre tras cada movimiento.",
            ["Punishes near-full stacks more strongly."] = "Castiga con más fuerza las pilas casi llenas.",
            ["Penalizes uneven stack heights."] = "Penaliza las alturas de pila desiguales.",
            ["Lets STALL take more immediate merge value."] = "Permite a STALL tomar más valor de fusión inmediata.",
            ["Rewards adjacent equal values and future cascade potential."] = "Recompensa los valores iguales adyacentes y el potencial de cascada futuro.",
            ["Changes how much immediate merging competes with setup."] = "Cambia cuánto compite la fusión inmediata con la preparación.",
            ["Adjusts how many setup moves the combo estimate looks through."] = "Ajusta cuántos movimientos de preparación revisa la estimación de combo.",
            ["Keeps some space open while building combos."] = "Mantiene algo de espacio libre mientras construye combos.",
            ["How far ahead future reward is valued. Higher plans longer-term, lower is greedier."] = "Hasta qué punto se valora la recompensa futura. Más alto planifica a más largo plazo, más bajo es más ávido.",
            ["Advantage estimation bias/variance trade-off. Higher = lower bias, more variance."] = "Compromiso sesgo/varianza de la estimación de ventaja. Más alto = menos sesgo, más varianza.",
            ["How big a policy update each step may make. Smaller is more conservative and stable."] = "Cuán grande puede ser una actualización de política por paso. Más pequeño es más conservador y estable.",
            ["Completed"] = "Completado",
            ["Secrets"] = "Secretos",
            ["Statistics"] = "Estadísticas",
            ["PPO Progress"] = "Progreso de PPO",
            ["No completed runs yet. Let a run end to start collecting solver stats."] = "Aún no hay runs completadas. Deja que una run termine para empezar a reunir estadísticas de solvers.",
            ["Tip: use the editor benchmark window for large balance samples without touching player progression."] = "Consejo: usa la ventana de benchmark del editor para grandes muestras de balance sin tocar el progreso del jugador.",
            ["Earn 10000 <sprite name=\"chips\" tint=1> in total"] = "Gana 10000 <sprite name=\"chips\" tint=1> en total",
            ["Earn 1M <sprite name=\"chips\" tint=1> in total"] = "Gana 1M <sprite name=\"chips\" tint=1> en total",
            ["Earn 1B <sprite name=\"chips\" tint=1> in total"] = "Gana 1B <sprite name=\"chips\" tint=1> en total",
            ["Spend 10000 <sprite name=\"chips\" tint=1> in total"] = "Gasta 10000 <sprite name=\"chips\" tint=1> en total",
            ["Spend 100K <sprite name=\"chips\" tint=1> in total"] = "Gasta 100K <sprite name=\"chips\" tint=1> en total",
            ["Spend 100M <sprite name=\"chips\" tint=1> in total"] = "Gasta 100M <sprite name=\"chips\" tint=1> en total",
            ["Complete 10 runs while Auto Solver is turned off"] = "Completa 10 runs con el Auto-Solver desactivado",
            ["Complete 1000 runs with a solver"] = "Completa 1000 runs con un solver",
            ["Move a total of 10000 times"] = "Muévete 10000 veces en total",
            ["Move a total of 100K times"] = "Muévete 100K veces en total",
            ["Move a total of 1M times"] = "Muévete 1M veces en total",
            ["Merge a total of 10000 times"] = "Fusiona 10000 veces en total",
            ["Merge a total of 100K times"] = "Fusiona 100K veces en total",
            ["Merge a total of 1M times"] = "Fusiona 1M veces en total",
            ["Reach high 1024"] = "Alcanza el bloque 1024",
            ["Reach high 8192"] = "Alcanza el bloque 8192",
            ["Reach high 65536"] = "Alcanza el bloque 65536",
            ["Unlock Agents"] = "Desbloquea los agentes",
            ["Equip 3 Agents at once"] = "Equipa 3 agentes a la vez",
            ["Unlock Modifiers"] = "Desbloquea los modificadores",
            ["Use all solvers at least once"] = "Usa cada solver al menos una vez",
            ["Use all Agents at least once"] = "Usa cada agente al menos una vez",
            ["Let Unstable Stack save your run a total of 100 times"] = "Deja que Unstable Stack salve tu run 100 veces en total",
            ["Merge with a Joker for a total of 100 times"] = "Fusiona con un Joker 100 veces en total",
            ["Consume a total of 5000 <sprite name=\"token\" tint=1>"] = "Consume 5000 <sprite name=\"token\" tint=1> en total",
            ["Hold at least 10000 <sprite name=\"token\" tint=1> at once"] = "Ten al menos 10000 <sprite name=\"token\" tint=1> a la vez",
            ["Prestige reset for the first time"] = "Haz un reinicio de prestigio por primera vez",
            ["Prestige reset for a total of 5 times"] = "Haz un reinicio de prestigio 5 veces en total",
            ["Prestige reset for a total of 15 times"] = "Haz un reinicio de prestigio 15 veces en total",
            ["Run PPO once in Normal Mode"] = "Ejecuta PPO una vez en modo normal",
            ["Reach 100K PPO frames"] = "Alcanza 100K frames PPO",
            ["Earn 1000 <sprite name=\"insight\" tint=1> in total"] = "Gana 1000 <sprite name=\"insight\" tint=1> en total",
            ["Earn 10K <sprite name=\"insight\" tint=1> in total"] = "Gana 10K <sprite name=\"insight\" tint=1> en total",
            ["Earn 100K <sprite name=\"insight\" tint=1> in total"] = "Gana 100K <sprite name=\"insight\" tint=1> en total",
            ["Buy all the researches"] = "Compra todas las investigaciones",
            ["Have at least 1 unit in each Server Rack"] = "Ten al menos 1 unidad en cada Server Rack",
            ["Go above 1000 GF/s total compute"] = "Supera 1000 GF/s de cómputo total",
            ["Reach 1M PPO Training frames"] = "Alcanza 1M frames de entrenamiento PPO",
            ["Let It Cook"] = "Déjalo cocinar",
            ["Budget Intelligence"] = "Inteligencia económica",
            ["Surgical Move"] = "Movimiento quirúrgico",
            ["Perfectly Reasonable"] = "Perfectamente razonable",
            ["Full Autopilot"] = "Piloto automático total",
            ["Bad Financial Advice"] = "Mal consejo financiero",
            ["Still Here"] = "Sigo aquí",
            ["One More Run"] = "Una run más",
            ["See You Again"] = "Hasta pronto",
            ["Perfectly Balanced"] = "Perfectamente equilibrado",
            ["Second Thoughts"] = "Dudas",
            ["No Defaults Given"] = "Sin valores por defecto",
            ["Let it cook"] = "Déjalo cocinar",
            ["Old intelligence"] = "Vieja inteligencia",
            ["Remove something big"] = "Quita algo grande",
            ["A very specific reserve"] = "Una reserva muy concreta",
            ["Everything buys itself"] = "Todo se compra solo",
            ["Questionable first purchase"] = "Primera compra cuestionable",
            ["Stay a while"] = "Quédate un rato",
            ["Just one more run"] = "Solo una run más",
            ["Come back often"] = "Vuelve a menudo",
            ["Almost perfectly split"] = "Casi perfectamente repartido",
            ["Second thoughts"] = "Duda repentina",
            ["No defaults left"] = "No quedan valores por defecto",
            ["Earn offline rewards after being away for 8+ hours."] = "Obtén recompensas offline tras 8+ horas de ausencia.",
            ["Complete a run with RAND after unlocking PPO."] = "Completa una run con RAND tras desbloquear PPO.",
            ["Use Miner's Pickaxe on a block worth 1024 or higher."] = "Usa la Miner's Pickaxe en un bloque de 1024 o más.",
            ["Hold exactly 2048 <sprite name=\"token\" tint=1> after a run ends."] = "Ten exactamente 2048 <sprite name=\"token\" tint=1> al terminar una run.",
            ["Have all Auto Buy buttons enabled simultaneously."] = "Ten todos los botones de Auto-Compra activados a la vez.",
            ["Buy the Joker as your first Modifier in a prestige."] = "Compra el Joker como primer modificador en un prestigio.",
            ["Have 24 hours of lifetime playtime."] = "Alcanza 24 horas de tiempo de juego total.",
            ["Leave the game open for 2 hours straight."] = "Deja el juego abierto 2 horas seguidas.",
            ["Exit the game 10 times."] = "Sal del juego 10 veces.",
            ["Split Compute Allocation exactly 33-33-33-1."] = "Reparte la asignación de cómputo exactamente 33-33-33-1.",
            ["Deselect a solver immediately after selecting it."] = "Deselecciona un solver justo después de elegirlo.",
            ["Modify all parameters of PPO in Tuning."] = "Modifica todos los parámetros de PPO en el ajuste.",
            ["Unlocks Auto Buy for Algos, Upgrades, Agents and Mods"] = "Desbloquea la Auto-Compra para Algos, mejoras, agentes y mods",
            ["Unlocks Datacenter"] = "Desbloquea el centro de datos",
            ["Merge streak upgrade at max level is 5% stronger"] = "La mejora Racha de fusiones al nivel máximo es 5% más fuerte",
            ["PPO learns from your Manual runs"] = "PPO aprende de tus runs manuales",
            ["Higher frequency upgrade at max level is 2% stronger"] = "La mejora Mayor frecuencia al nivel máximo es 2% más fuerte",
            ["Unlocks Byte numeral for blocks"] = "Desbloquea la notación Byte para los bloques",
            ["Unlocks Power numeral for blocks"] = "Desbloquea la notación Potencia para los bloques",
            ["Unlocks Roman numeral for blocks"] = "Desbloquea la notación romana para los bloques",
            ["Unlocks Hexadecimal numeral for blocks"] = "Desbloquea la notación hexadecimal para los bloques",
            ["Unlocks Scientific numeral for blocks"] = "Desbloquea la notación científica para los bloques",
            ["Complete its goal to unlock this numeral"] = "Completa su objetivo para desbloquear esta notación",
            ["Consecutive merges multiply move income."] = "Las fusiones consecutivas multiplican el ingreso por movimiento.",
            ["Converts part of the run's score into <sprite name=\"chips\" tint=1>."] = "Convierte parte de los puntos de la run en <sprite name=\"chips\" tint=1>.",
            ["Held <sprite name=\"token\" tint=1> pay <sprite name=\"chips\" tint=1> times the √ of the hoard."] = "Los <sprite name=\"token\" tint=1> retenidos pagan <sprite name=\"chips\" tint=1>, multiplicados por la √ de la reserva.",
            ["The currency for Auto restart. Price rises the more <sprite name=\"token\" tint=1> you hold."] = "La moneda para el reinicio auto. El precio sube cuantos más <sprite name=\"token\" tint=1> tengas.",
            ["Standard"] = "Estándar",
            ["Byte"] = "Byte",
            ["Hexadecimal"] = "Hexadecimal",
            ["Power"] = "Potencia",
            ["Roman"] = "Romano",
            ["Scientific"] = "Científico",
            ["Audio"] = "Audio",
            ["Accessibility"] = "Accesibilidad",
            ["Application"] = "Aplicación",
            ["Display"] = "Pantalla",
            ["Manage save files"] = "Gestionar partidas guardadas",
            ["Block numerals visual"] = "Estilo de los números de bloque",
            ["How to play"] = "Cómo jugar",
            ["Highest"] = "Más alto",
            ["Highest median"] = "Mediana más alta",
            ["Runs"] = "Runs",
            ["Earned"] = "Ganado",
            ["Resets"] = "Reinicios",
            ["Playtime"] = "Tiempo de juego",
            ["Solvers"] = "Solvers",
            ["Recent Score Trend"] = "Tendencia reciente de puntos",
            ["Recent Runs"] = "Runs recientes",
            ["Lifetime Stats"] = "Estadísticas globales",
            ["Goals"] = "Objetivos",
            ["Prestige Summary"] = "Resumen de prestigio",
            ["Average time in runs"] = "Duración media de las runs",
            ["Total frame"] = "Frames totales",
            ["Average frame / Prestige"] = "Frames medios / prestigio",
            ["Total runs"] = "Runs totales",
            ["Total moves"] = "Movimientos totales",
            ["Total merges"] = "Fusiones totales",
            ["PPO knowledge"] = "Conocimiento de PPO",
            ["Total playtime"] = "Tiempo de juego total",
            ["Merge Broker"] = "Corredor de fusiones",
            ["Highwater Analyst"] = "Analista de récords",
            ["Score Auditor"] = "Auditor de puntos",
            ["Overclocker"] = "Overclockeador",
            ["Quartermaster"] = "Intendente",
            ["Restart Sponsor"] = "Patrocinador de reinicios",
            ["Token Prospector"] = "Prospector de tokens",
            ["Move Dividend"] = "Dividendo de movimientos",
            ["Velocity Trader"] = "Trader de velocidad",
            ["Unstable Stack"] = "Pila inestable",
            ["Catalyst Stack"] = "Pila catalizadora",
            ["Mirror Stack"] = "Pila espejo",
            ["Joker"] = "Joker",
            ["Miner's Pickaxe"] = "Pico de minero",
            ["Queue Scrubber"] = "Limpiador de cola",
            ["Neural Accelerator"] = "Acelerador neuronal",
            ["Boosts merge income."] = "Aumenta el ingreso por fusiones.",
            ["Rewards new highs."] = "Recompensa los nuevos récords.",
            ["Turns score into <sprite name=\"chips\" tint=1>."] = "Convierte los puntos en <sprite name=\"chips\" tint=1>.",
            ["Runs the solver faster."] = "Hace correr el solver más rápido.",
            ["Improves baseline income."] = "Mejora el ingreso base.",
            ["Keeps restarts funded."] = "Financia los reinicios.",
            ["Turns merge volume into restart fuel."] = "Convierte el volumen de fusiones en combustible de reinicio.",
            ["Rewards long, stable runs."] = "Recompensa las runs largas y estables.",
            ["Rewards fast solvers."] = "Recompensa los solvers rápidos.",
            ["Deletes bottom blocks when a full stack would fail."] = "Borra los bloques inferiores cuando una pila llena fallaría.",
            ["Converts merges into more <sprite name=\"chips\" tint=1>."] = "Convierte las fusiones en más <sprite name=\"chips\" tint=1>.",
            ["Lets stack ends interact."] = "Permite que los extremos de una pila interactúen.",
            ["Adds wild blocks to the queue."] = "Añade bloques comodín a la cola.",
            ["Lets solvers remove blocks from the board."] = "Permite a los solvers quitar bloques del tablero.",
            ["Lets solvers delete bad upcoming blocks."] = "Permite a los solvers borrar los bloques próximos malos.",
            ["Speeds up expensive solvers."] = "Acelera los solvers costosos.",
            ["Select an algorithm to inspect it. Locked algorithms hide detailed behavior until unlocked."] = "Elige un algoritmo para inspeccionarlo. Los algoritmos bloqueados ocultan su comportamiento detallado hasta desbloquearse.",
            ["Buy automation, unlock new layers, then push into riskier systems when the run history proves you are ready."] = "Compra automatización, desbloquea nuevas capas y lánzate a sistemas más arriesgados cuando el historial demuestre que estás listo.",
            ["Equipped Agents give various bonuses to progress faster."] = "Los agentes equipados dan varios bonos para progresar más rápido.",
            ["Late-game rule modules. They raise the ceiling, create rescue tools, and make solver choice matter more than raw price."] = "Módulos de reglas del final del juego. Suben el techo, crean herramientas de rescate y hacen que la elección del solver importe más que el simple precio.",
            ["They expand the game rules, allowing for further production. Each solver is effective in different ways."] = "Amplían las reglas del juego, permitiendo más producción. Cada solver es eficaz de forma distinta.",
            ["Rule-changing modules that apply to new runs and amplify the differences between solvers."] = "Módulos que cambian las reglas, se aplican a las nuevas runs y amplifican las diferencias entre solvers.",
            ["Modifiers apply to new runs and amplify solver differences."] = "Los modificadores se aplican a las nuevas runs y amplifican las diferencias entre solvers.",
            ["You can track how many tasks you've completed. As you progress, you'll automatically unlock them."] = "Puedes ver cuántas tareas has completado. A medida que avanzas, las desbloqueas automáticamente.",
            ["Permanent late-game research. Prestige turns PPO Normal-mode performance into Insight, then the tree makes every future reset faster and deeper."] = "Investigación permanente del final del juego. El prestigio convierte el rendimiento del modo normal de PPO en Insight, y luego el árbol hace cada reinicio futuro más rápido y profundo.",
            ["Permanent late-game research. The tree makes every future reset faster and deeper."] = "Investigación permanente del final del juego. El árbol hace cada reinicio futuro más rápido y profundo.",
            ["Research locked. Finish PPO Training, then run PPO in Normal mode."] = "Investigación bloqueada. Termina el entrenamiento PPO y luego ejecuta PPO en modo normal.",
            ["Track your recent runs and the performance of your used solvers."] = "Sigue tus runs recientes y el rendimiento de los solvers usados.",
            ["Description"] = "Descripción",
            ["<b>Manual controls</b>"] = "<b>Controles manuales</b>",
            ["Free baseline solver."] = "Solver básico gratuito.",
            ["Randomly chooses any valid stack. Weak, chaotic, but fast."] = "Elige al azar cualquier pila válida. Débil, caótico, pero rápido.",
            ["Looks for direct merges."] = "Busca fusiones directas.",
            ["Prioritizes immediate merges and cascades before anything else."] = "Prioriza las fusiones y cascadas inmediatas antes que nada.",
            ["Keeps stacks even."] = "Mantiene las pilas equilibradas.",
            ["Avoids tall dangerous stacks and spreads risk across the board."] = "Evita las pilas altas y peligrosas y reparte el riesgo por el tablero.",
            ["Scores every legal move."] = "Puntúa cada movimiento legal.",
            ["Uses handcrafted heuristics: merge value, danger, future queue fit, and free space."] = "Usa heurísticas hechas a mano: valor de fusión, peligro, ajuste futuro de la cola y espacio libre.",
            ["Plans one move deeper."] = "Planifica un movimiento más allá.",
            ["Tests each move, then estimates the best follow-up move before deciding."] = "Prueba cada movimiento y luego estima el mejor movimiento siguiente antes de decidir.",
            ["Runs simulations."] = "Ejecuta simulaciones.",
            ["Rolls out multiple futures, judging each by the surviving board and the peak tier it reaches."] = "Despliega varios futuros, juzgando cada uno por el tablero superviviente y el nivel máximo que alcanza.",
            ["Reads the visible queue."] = "Lee la cola visible.",
            ["Queue planner. Searches lines through up to 3 visible next blocks before choosing."] = "Planificador de cola. Busca líneas a través de hasta 3 bloques siguientes visibles antes de elegir.",
            ["Queue planner. Searches lines through the visible next blocks. Planning depth (3–5) can be tuned for patience vs practicality."] = "Planificador de cola. Busca líneas a través de los bloques siguientes visibles. La profundidad de plan (3–5) se ajusta entre paciencia y practicidad.",
            ["Uses the extended queue."] = "Usa la cola extendida.",
            ["Deep queue planner. Searches lines through up to 5 visible next blocks. Stronger once next preview upgrades are unlocked."] = "Planificador de cola profundo. Busca líneas a través de hasta 5 bloques siguientes visibles. Más fuerte con las mejoras de vista previa desbloqueadas.",
            ["Smarter Monte Carlo rollouts."] = "Rollouts Monte Carlo más inteligentes.",
            ["Enhanced Monte Carlo. Each rollout uses short queue planning and an anti-stall board score."] = "Monte Carlo mejorado. Cada rollout usa una breve planificación de cola y una puntuación de tablero anti-bloqueo.",
            ["Builds a search tree."] = "Construye un árbol de búsqueda.",
            ["Monte Carlo Tree Search. Balances exploring new lines with exploiting lines that already score well."] = "Monte Carlo Tree Search. Equilibra explorar nuevas líneas con explotar las líneas que ya puntúan bien.",
            ["Avoids dead boards."] = "Evita los tableros muertos.",
            ["Anti-stall solver. Heavily protects legal moves, semi-empty stacks, and escape routes over greedy merges."] = "Solver anti-bloqueo. Protege con fuerza los movimientos legales, las pilas medio vacías y las vías de escape frente a las fusiones ávidas.",
            ["Sets up chain merges."] = "Prepara fusiones en cadena.",
            ["Combo-focused solver. Reads the queue and rewards positions that can cascade over the next 2-3 turns."] = "Solver centrado en combos. Lee la cola y recompensa las posiciones que pueden encadenar en los próximos 2-3 turnos.",
            ["Endgame learner. Requires every Modifier to be fully purchased."] = "Aprendiz del final del juego. Requiere que cada modificador esté completamente comprado.",
            ["Proximal Policy Optimization is a lightweight actor-critic neural network that learns its policy from run trajectories, clipped policy updates, value estimates, and entropy-driven exploration."] = "Proximal Policy Optimization es una red neuronal actor-crítico ligera que aprende su política a partir de trayectorias de runs, actualizaciones de política recortadas, estimaciones de valor y exploración guiada por entropía.",
            ["+75% <sprite name=\"chips\" tint=1> from merge rewards."] = "+75% de <sprite name=\"chips\" tint=1> de las recompensas de fusión.",
            ["+200% <sprite name=\"chips\" tint=1> from new highest-block rewards."] = "+200% de <sprite name=\"chips\" tint=1> de las recompensas por nuevo bloque récord.",
            ["+200% <sprite name=\"chips\" tint=1> from end-of-run score bonus."] = "+200% de <sprite name=\"chips\" tint=1> del bono de puntos de fin de run.",
            ["Solver move interval is 25% shorter."] = "El intervalo de movimiento del solver es 25% más corto.",
            ["+10 <sprite name=\"chips\" tint=1> on every successful placement."] = "+10 <sprite name=\"chips\" tint=1> por cada colocación exitosa.",
            ["Auto Restart consumes no tokens while this agent is active."] = "El reinicio auto no consume tokens mientras este agente esté activo.",
            ["+1 token for every 8 merges while active."] = "+1 token por cada 8 fusiones mientras esté activo.",
            ["End-of-run <sprite name=\"chips\" tint=1> gain a bonus from total moves completed."] = "Los <sprite name=\"chips\" tint=1> de fin de run reciben un bono según el total de movimientos.",
            ["End-of-run <sprite name=\"chips\" tint=1> gain a throughput bonus from moves per second."] = "Los <sprite name=\"chips\" tint=1> de fin de run reciben un bono de rendimiento según los movimientos por segundo.",
            ["Each level gives one rescue per run. If a full stack receives a non-merge block, its bottom block is removed without reducing score."] = "Cada nivel da un rescate por run. Si una pila llena recibe un bloque sin fusión, su bloque inferior se elimina sin reducir la puntuación.",
            ["Merge rewards are permanently doubled on every run after purchase."] = "Las recompensas de fusión se duplican permanentemente en cada run tras la compra.",
            ["Unlocks a special merge. If the top and bottom block of a stack match, they merge through the stack."] = "Desbloquea una fusión especial. Si el bloque superior e inferior de una pila coinciden, se fusionan a través de la pila.",
            ["Unlocks occasional Joker blocks. A Joker placed onto any block merges with it."] = "Desbloquea bloques Joker ocasionales. Un Joker colocado sobre cualquier bloque se fusiona con él.",
            ["Each level gives one pickaxe use per run. The solver may delete any block in any stack."] = "Cada nivel da un uso de pico por run. El solver puede borrar cualquier bloque de cualquier pila.",
            ["Each level gives one queue skip per run. The current next block is removed and the following block moves forward."] = "Cada nivel da un salto de cola por run. El bloque siguiente actual se elimina y el siguiente avanza.",
            ["MOCA, MOCA+, and MCTS run permanently about twice as fast. Negative speed tuning on those solvers is also twice as effective."] = "MOCA, MOCA+ y MCTS corren permanentemente unas dos veces más rápido. El ajuste de velocidad negativo también es dos veces más eficaz en esos solvers.",
            ["MOCA runs permanently about twice as fast. Negative speed tuning on it is also twice as effective."] = "MOCA corre permanentemente unas dos veces más rápido. El ajuste de velocidad negativo también es dos veces más eficaz.",
            ["+35% <sprite name=\"insight\" tint=1> from every future prestige per level."] = "+35% de <sprite name=\"insight\" tint=1> de cada prestigio futuro por nivel.",
            ["Start after each prestige reset with <sprite name=\"chips\" tint=1> already banked. This allows making purchases right at the beginning of the game."] = "Empieza tras cada reinicio de prestigio con <sprite name=\"chips\" tint=1> ya guardados. Esto permite comprar justo al inicio de la partida.",
            ["Permanently remembers automation unlocks per level after prestige: Auto Solve, Auto Restart <sprite name=\"token\" tint=1>, then Solver Tuning."] = "Recuerda permanentemente un desbloqueo de automatización por nivel tras el prestigio: Resolución auto, Reinicio auto <sprite name=\"token\" tint=1>, luego Ajuste del solver.",
            ["Start future prestiges with early algorithms already known: BAL, HEUR, COMBO, then LOOK."] = "Empieza los prestigios futuros con algoritmos tempranos ya conocidos: BAL, HEUR, COMBO, luego LOOK.",
            ["+18% <sprite name=\"chips\" tint=1> from every reward per level. It stacks with Chip Yield and stage multipliers."] = "+18% de <sprite name=\"chips\" tint=1> de cada recompensa por nivel. Se acumula con el rendimiento de chips y los multiplicadores de fase.",
            ["+50% <sprite name=\"chips\" tint=1> from every reward per level. It stacks with Chip Yield and stage multipliers, making every future playthrough visibly faster."] = "+50% de <sprite name=\"chips\" tint=1> de cada recompensa por nivel. Se acumula con el rendimiento de chips y los multiplicadores de fase, haciendo cada partida futura notablemente más rápida.",
            ["PPO still resets every prestige, but each level lowers the trained frame requirement for Normal Mode by 8%."] = "PPO sigue reiniciándose en cada prestigio, pero cada nivel reduce el requisito de frames entrenados del modo normal en un 8%.",
            ["Prestige banks 50000 PPO training frames per level. The next playthrough's PPO Training starts from that saved progress, with the knowledge already learned (instead of zero)."] = "El prestigio guarda 50000 frames de entrenamiento PPO por nivel. El entrenamiento PPO de la siguiente partida parte de ese progreso guardado, con el conocimiento ya aprendido (en vez de cero).",
            ["Each level lowers the cycle frame requirement for PPO Normal Mode by 8%. At level 5, PPO Curriculum upgrades can be bought before PPO is unlocked and can fully automate the remaining cycle requirement."] = "Cada nivel reduce el requisito de frames de ciclo del modo normal PPO en un 8%. En el nivel 5, las mejoras PPO Curriculum pueden comprarse antes de desbloquear PPO y automatizar por completo el requisito de ciclo restante.",
            ["Prestige banks 50000 PPO cycle frames per level. The next playthrough's PPO Training starts from that saved cycle progress, while Datacenter training remains as permanent PPO knowledge."] = "El prestigio guarda 50000 frames de ciclo PPO por nivel. El entrenamiento PPO de la siguiente partida parte de ese progreso de ciclo guardado, mientras el entrenamiento del centro de datos permanece como conocimiento PPO permanente.",
            ["Prestige banks 40000 PPO cycle frames per level. The next playthrough's PPO Training starts from that saved cycle progress, while Datacenter training remains as permanent PPO knowledge."] = "El prestigio guarda 40000 frames de ciclo PPO por nivel. El entrenamiento PPO de la siguiente partida parte de ese progreso de ciclo guardado, mientras el entrenamiento del centro de datos permanece como conocimiento PPO permanente.",
            ["Raises PPO's reward signal for creating new highest blocks. This pushes the learner toward bigger blocks instead of only safer runs."] = "Aumenta la señal de recompensa de PPO por crear nuevos bloques récord. Esto empuja al aprendiz hacia bloques más grandes en vez de solo runs más seguras.",
            ["Improves PPO's survival shaping and danger penalties, making high-focus policies less likely to crash early."] = "Mejora el modelado de supervivencia y las penalizaciones de peligro de PPO, haciendo que las políticas centradas en récords caigan menos temprano.",
            ["+50% <sprite name=\"insight\" tint=1> from PPO Normal Mode performance per level. This is the late neural payoff node."] = "+50% de <sprite name=\"insight\" tint=1> del rendimiento del modo normal PPO por nivel. Es el nodo de recompensa neuronal tardío.",
            ["Boosts <sprite name=\"insight\" tint=1> earned directly from PPO Normal Mode runs. Training mode never feeds this, and long cycles softcap so prestige stays valuable."] = "Aumenta el <sprite name=\"insight\" tint=1> ganado directamente de las runs en modo normal PPO. El modo entrenamiento nunca lo alimenta, y los ciclos largos tienen tope suave para que el prestigio siga valiendo la pena.",
            ["Offline Engine\", \"While the game is closed, <sprite name=\"chips\" tint=1> and <sprite name=\"insight\" tint=1> continue at a reduced rate based on your current prestige strength."] = "Mientras el juego está cerrado, los <sprite name=\"chips\" tint=1> y el <sprite name=\"insight\" tint=1> continúan a un ritmo reducido según tu fuerza de prestigio actual.",
            ["Extends how many closed-game hours can be converted into offline <sprite name=\"chips\" tint=1> and <sprite name=\"insight\" tint=1>."] = "Amplía cuántas horas con el juego cerrado se convierten en <sprite name=\"chips\" tint=1> e <sprite name=\"insight\" tint=1> offline.",
            ["Every hired Agent's bonus effect is 40% stronger per level. Agents become a core engine of faster replays."] = "El efecto de bono de cada agente contratado es 40% más fuerte por nivel. Los agentes se vuelven un motor central de partidas más rápidas.",
            ["Upgrades, Agents and Modifiers cost 5% less per level, and the Modifiers requirement needs 15% fewer runs & merges per level. At level 5, Datacenter costs are 20% cheaper."] = "Las mejoras, agentes y modificadores cuestan 5% menos por nivel, y el requisito de modificadores necesita 15% menos runs y fusiones por nivel. En el nivel 5, los costes del centro de datos son 20% más baratos.",
            ["Shortens the result-evaluation pause after every PPO Training run by 15% per level, so Training mode gets through its runs much faster."] = "Acorta la pausa de evaluación de resultados tras cada run de entrenamiento PPO en un 15% por nivel, así el modo entrenamiento avanza mucho más rápido.",
            ["Unlock PPO to begin the prestige layer."] = "Desbloquea PPO para empezar la capa de prestigio.",
            ["Prestige for"] = "Recompensa de prestigio:",
            ["You can keep playing PPO in Playing Mode to increase <sprite name=\"insight\" tint=1>."] = "Puedes seguir jugando PPO en modo Juego para aumentar el <sprite name=\"insight\" tint=1>.",
            ["Current effect"] = "Efecto actual",
            ["Game"] = "Juego",
            ["Gameplay"] = "Jugabilidad",
            ["Selected"] = "Seleccionado",
            ["Deselected"] = "Deseleccionado",
            ["Needs modifiers"] = "Requiere modificadores",
            ["Needs all\nModifiers"] = "Requiere todos\nlos modificadores",
            ["Unlock\nUpgrades"] = "Desbloquear en\nMejoras",
            ["Unlock this algorithm to reveal details."] = "Desbloquea este algoritmo para revelar los detalles.",
            ["Agents\nLocked"] = "Agentes\nBloqueados",
            ["Unlock in\nUpgrades"] = "Desbloquear en\nMejoras",
            ["Bonus slot\nNeeds upgrade"] = "Ranura extra\nRequiere mejora",
            ["Agents Locked"] = "Agentes bloqueados",
            ["Unlock the Agents menu in Upgrades."] = "Desbloquea el menú de agentes en Mejoras.",
            ["Equipped"] = "Equipado",
            ["No free slot"] = "No hay ranura libre",
            ["Unequip someone first"] = "Desequipa a alguien primero",
            ["Needs upgrade"] = "Requiere mejora",
            ["Empty"] = "Vacío",
            ["Modifier Lab Locked"] = "Lab de modificadores bloqueado",
            ["Reach the stage goal in Upgrades to unlock board modifiers. They make runs richer, riskier, and much harder to play optimally by hand."] = "Alcanza el objetivo de fase en Mejoras para desbloquear los modificadores de tablero. Hacen las runs más ricas, más arriesgadas y mucho más difíciles de jugar de forma óptima a mano.",
            ["Not active"] = "No activo",
            ["Activate"] = "Activar",
            ["Upgrade"] = "Mejorar",
            ["Ready: every Modifier is fully purchased."] = "Listo: cada modificador está completamente comprado.",
            ["PPO model is not initialized yet."] = "El modelo PPO aún no está inicializado.",
            ["Prestige once to open Research."] = "Haz un prestigio para abrir la investigación.",
            ["Research maxed."] = "Investigación al máximo.",
            ["Not enough Insight."] = "No hay suficiente Insight.",
            ["Not enough <sprite name=\"insight\" tint=1>."] = "No hay suficiente <sprite name=\"insight\" tint=1>.",
            ["Requires Seed Capital L1."] = "Requiere Capital inicial N1.",
            ["Requires Automation Memory L1."] = "Requiere Memoria de automatización N1.",
            ["Requires Algorithm Archive L1."] = "Requiere Archivo de algoritmos N1.",
            ["Requires Agent Synergy L1."] = "Requiere Sinergia de agentes N1.",
            ["Requires Bulk Discount L1."] = "Requiere Descuento por volumen N1.",
            ["Requires PPO Bootcamp L1."] = "Requiere PPO Bootcamp N1.",
            ["Requires Evaluation Efficiency L1."] = "Requiere Eficiencia de evaluación N1.",
            ["Requires PPO Memory L1."] = "Requiere Memoria PPO N1.",
            ["Requires High Focus L1."] = "Requiere Alto enfoque N1.",
            ["Requires Stability Model L1."] = "Requiere Modelo de estabilidad N1.",
            ["Requires Insight Amplifier L1."] = "Requiere Amplificador de Insight N1.",
            ["Requires Passive Insight L1."] = "Requiere Insight pasivo N1.",
            ["Requires Offline Engine L1."] = "Requiere Motor offline N1.",
            ["Ready to buy."] = "Listo para comprar.",
            ["Not enough chips"] = "No hay suficientes chips",
            ["PPO requires every Modifier maxed"] = "PPO requiere cada modificador al máximo",
            ["Unlock Agents first"] = "Desbloquea primero los agentes",
            ["Modifier Lab requirements not met"] = "No se cumplen los requisitos del Lab de modificadores",
            ["Run PPO in Normal mode first"] = "Ejecuta primero PPO en modo normal",
            ["Agents menu unlocked"] = "Menú de agentes desbloqueado",
            ["Agent unavailable"] = "Agente no disponible",
            ["No free agent slot"] = "No hay ranura de agente libre",
            ["Speed level"] = "Nivel de velocidad",
            ["Risk level"] = "Nivel de riesgo",
            ["Chip yield level"] = "Nivel de rendimiento de chips",
            ["Next preview"] = "Vista previa siguiente",
            ["Scaling frequency upgrade unavailable"] = "Mejora de frecuencia de escalado no disponible",
            ["Profitable ending upgrade unavailable"] = "Mejora de final rentable no disponible",
            ["Modifier upgrade unavailable"] = "Mejora de modificador no disponible",
            ["<b>Auto Buy</b>"] = "<b>Auto-Compra</b>",
            ["Auto Buy"] = "Auto-Compra",
            ["Enabled"] = "Activado",
            ["Disabled"] = "Desactivado",
            ["FPS --"] = "FPS --",
            ["Policy loss"] = "Pérdida de política",
            ["Policy loss:"] = "Pérdida de política:",
            ["Value loss"] = "Pérdida de valor",
            ["Value loss:"] = "Pérdida de valor:",
            ["Entropy"] = "Entropía",
            ["Entropy:"] = "Entropía:",
            ["Updates"] = "Actualizaciones",
            ["Updates:"] = "Actualizaciones:",
            ["PPO is trained, prestige reset unlocked."] = "PPO está entrenado, reinicio de prestigio desbloqueado.",
            ["Gain:"] = "Ganancia:",
            ["You made"] = "Has ganado",
            ["while you were offline."] = "mientras estabas offline.",
            ["Offline reward time:"] = "Tiempo de recompensa offline:",
            ["You have to finish PPO Training to unlock prestige."] = "Debes terminar el entrenamiento PPO para desbloquear el prestigio.",
            ["In case of a Prestige reset, the game will restart. All <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, upgrades, Agents, and Modifiers will be lost.\n\n" +
                "However, existing <sprite name=\"insight\" tint=1> and purchased research will remain, which will make further resets progressively more valuable.\n\n" +
                "<b>It is recommended to use PPO in Normal Mode before resetting to gain <sprite name=\"insight\" tint=1> multiplier.</b>"] =
            "En caso de un reinicio de prestigio, el juego se reinicia. Se perderán todos los <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, mejoras, agentes y modificadores.\n\n" +
            "Sin embargo, el <sprite name=\"insight\" tint=1> existente y la investigación comprada se conservan, lo que hace los reinicios posteriores cada vez más valiosos.\n\n" +
            "<b>Se recomienda usar PPO en modo normal antes de reiniciar para aumentar el multiplicador de <sprite name=\"insight\" tint=1>.</b>",
            ["Reset for"] = "Recompensa de reinicio:",
            ["Datacenter"] = "Centro de datos",
            ["Compute Allocation"] = "Asignación de cómputo",
            ["Server Racks"] = "Racks de servidores",
            ["Facility Upgrades"] = "Mejoras de instalación",
            ["CPU Rack"] = "Rack CPU",
            ["GPU Rack"] = "Rack GPU",
            ["TPU Pod"] = "Pod TPU",
            ["Neural Fabric"] = "Neural Fabric",
            ["Power Grid"] = "Red eléctrica",
            ["Cooling Loop"] = "Circuito de refrigeración",
            ["Fabric Interconnect"] = "Interconexión Fabric",
            ["Commodity silicon. Cheap, dependable, slow."] = "Silicio de consumo. Barato, fiable, lento.",
            ["Parallel throughput for tensor math."] = "Rendimiento paralelo para cálculo tensorial.",
            ["Tensor pods. Systolic arrays with obscene throughput."] = "Pods tensoriales. Matrices sistólicas con un rendimiento obsceno.",
            ["Experimental wafer-scale mesh. Draws its own weather."] = "Malla experimental a escala de oblea. Genera su propio clima.",
            ["Dedicated feeders and battery buffer."] = "Alimentadores dedicados y búfer de batería.",
            ["Immersion + rear-door heat exchangers."] = "Inmersión e intercambiadores de calor en puerta trasera.",
            ["Low-latency mesh between pods."] = "Malla de baja latencia entre pods.",
            ["Total compute"] = "Cómputo total",
            ["allocated"] = "asignado",
            ["units"] = "unidades",
            ["unit"] = "unidad",
            ["total"] = "total",
            ["Training Cluster"] = "Clúster de entrenamiento",
            ["Analysis Node"] = "Nodo de análisis",
            ["Market Bots"] = "Bots de mercado",
            ["Passive PPO frame. Shortens the prestige cycle."] = "Frames PPO pasivos. Acorta el ciclo de prestigio.",
            ["Passively generates <sprite name=\"insight\" tint=1> (softcapped)."] = "Genera pasivamente <sprite name=\"insight\" tint=1> (con tope suave).",
            ["Producing <sprite name=\"chips\" tint=1> gets an income multiplier."] = "La producción de <sprite name=\"chips\" tint=1> recibe un multiplicador de ingresos.",
            ["Requires every Modifier maxed"] = "Requiere cada modificador al máximo",
            ["Agent bonuses"] = "Bonos de agentes",
            ["Shop prices"] = "Precios de la tienda",
            ["Training eval pause"] = "Pausa de evaluación de entrenamiento",
            ["Prestige Insight"] = "Insight de prestigio",
            ["Start chips"] = "Chips iniciales",
            ["Chip rewards"] = "Recompensas en chips",
            ["No automation is remembered yet."] = "Aún no se recuerda ninguna automatización.",
            ["Auto Solve unlock remembered."] = "Desbloqueo de Resolución auto recordado.",
            ["Auto Restart unlock and 50 tokens remembered."] = "Desbloqueo de Reinicio auto y 50 tokens recordados.",
            ["Auto Solve, Auto Restart, tokens, and Solver Tuning remembered."] = "Resolución auto, Reinicio auto, tokens y Ajuste del solver recordados.",
            ["No algorithms remembered yet."] = "Aún no se recuerda ningún algoritmo.",
            ["Start with RAND."] = "Empieza con RAND.",
            ["Start with RAND and MERG."] = "Empieza con RAND y MERG.",
            ["Start with RAND, MERG, and BAL."] = "Empieza con RAND, MERG y BAL.",
            ["Start with RAND, MERG, BAL, and HEUR."] = "Empieza con RAND, MERG, BAL y HEUR.",
            ["Insight Amplifier"] = "Amplificador de Insight",
            ["Seed Capital"] = "Capital inicial",
            ["Automation Memory"] = "Memoria de automatización",
            ["Algorithm Archive"] = "Archivo de algoritmos",
            ["Yield Theory"] = "Teoría del rendimiento",
            ["PPO Bootcamp"] = "PPO Bootcamp",
            ["PPO Memory"] = "Memoria PPO",
            ["High Focus"] = "Alto enfoque",
            ["Stability Model"] = "Modelo de estabilidad",
            ["Insight Extractor"] = "Extractor de Insight",
            ["Passive Insight"] = "Insight pasivo",
            ["Offline Engine"] = "Motor offline",
            ["Offline Buffer"] = "Búfer offline",
            ["Agent Synergy"] = "Sinergia de agentes",
            ["Bulk Discount"] = "Descuento por volumen",
            ["Evaluation Efficiency"] = "Eficiencia de evaluación",
            ["Insight"] = "Insight",
            ["RAND selected"] = "RAND seleccionado",
            ["RAND deselected"] = "RAND deseleccionado",
            ["BAL selected"] = "BAL seleccionado",
            ["BAL deselected"] = "BAL deseleccionado",
            ["BAL tuning updated"] = "Ajuste de BAL actualizado",
            ["BAL tuning reset"] = "Ajuste de BAL reiniciado",
            ["HEUR selected"] = "HEUR seleccionado",
            ["HEUR deselected"] = "HEUR deseleccionado",
            ["HEUR tuning updated"] = "Ajuste de HEUR actualizado",
            ["HEUR tuning reset"] = "Ajuste de HEUR reiniciado",
            ["COMBO selected"] = "COMBO seleccionado",
            ["COMBO deselected"] = "COMBO deseleccionado",
            ["COMBO tuning updated"] = "Ajuste de COMBO actualizado",
            ["COMBO tuning reset"] = "Ajuste de COMBO reiniciado",
            ["LOOK selected"] = "LOOK seleccionado",
            ["LOOK deselected"] = "LOOK deseleccionado",
            ["LOOK tuning updated"] = "Ajuste de LOOK actualizado",
            ["LOOK tuning reset"] = "Ajuste de LOOK reiniciado",
            ["MOCA selected"] = "MOCA seleccionado",
            ["MOCA deselected"] = "MOCA deseleccionado",
            ["MOCA tuning updated"] = "Ajuste de MOCA actualizado",
            ["MOCA tuning reset"] = "Ajuste de MOCA reiniciado",
            ["PLAN selected"] = "PLAN seleccionado",
            ["PLAN deselected"] = "PLAN deseleccionado",
            ["PLAN tuning updated"] = "Ajuste de PLAN actualizado",
            ["PLAN tuning reset"] = "Ajuste de PLAN reiniciado",
            ["Export"] = "Exportar",
            ["Import"] = "Importar",
            ["To import your game data, paste in your export text.\n\n" +
                "Importing will overwrite all progress in all of your saves, and it will not be possible to recover old progress."] =
            "Para importar tus datos de juego, pega tu texto de exportación.\n\n" +
            "La importación sobrescribirá todo el progreso de todas tus partidas, y no será posible recuperar el progreso anterior.",

            // ---- How To Play + menu help ---------------------------------------------------------
            ["This part of the game is still locked. Keep progressing to reveal this help section."] = "Esta parte del juego sigue bloqueada. Sigue progresando para revelar esta sección de ayuda.",
            ["Welcome!"] = "¡Bienvenido!",
            ["Basics"] = "Básicos",
            ["Purpose"] = "Propósito",
            ["Priorities"] = "Prioridades",
            ["Tip"] = "Consejo",
            ["Usage"] = "Uso",
            ["Reward rules"] = "Reglas de recompensa",
            ["Income formula"] = "Fórmula de ingresos",
            ["Speed formula"] = "Fórmula de velocidad",
            ["Synergy formula"] = "Fórmula de sinergia",
            ["Main formula"] = "Fórmula principal",
            ["Allocations"] = "Asignaciones",
            ["Allocation formulas"] = "Fórmulas de asignación",
            ["Main multipliers"] = "Multiplicadores principales",
            ["Layer progression"] = "Progresión de capas",
            ["Prestige Reset"] = "Reinicio de prestigio",
            ["PPO"] = "PPO",
            ["<sprite name=\"insight\" tint=1> reward formula"] = "Fórmula de recompensa de <sprite name=\"insight\" tint=1>",
            ["General:\n" +
                    "<b>moveInterval = max(minInterval, speedInterval x solverPacing x computePacing x agentPacing x trainingPacing)</b>\n\n" +
                    "For heavy search solvers:\n" +
                    "<b>computePacing = max(0.35, 1 - 0.11 x ComputeSpeedLevel)</b>"] =
                "General:\n" +
                "<b>moveInterval = max(minInterval, speedInterval x solverPacing x computePacing x agentPacing x trainingPacing)</b>\n\n" +
                "Para solvers de búsqueda pesada:\n" +
                "<b>computePacing = max(0.35, 1 - 0.11 x ComputeSpeedLevel)</b>",
            ["Catalyst Stack doubles merge rewards.\n\n" +
                    "<b>salvage = ceil(score x salvageShare x 0.25) x stage x globalIncome</b>\n\n" +
                    "Because runs become longer and more flexible, planning solvers and PPO also become more valuable."] =
                "Catalyst Stack duplica las recompensas de fusión.\n\n" +
                "<b>salvage = ceil(score x salvageShare x 0.25) x stage x globalIncome</b>\n\n" +
                "Como las runs se vuelven más largas y flexibles, los solvers de planificación y PPO también ganan valor.",
            ["<b><sprite name=\"insight\" tint=1> ~= round((1 + performance x 1.25 + cycleCarry) x usage x insightMultiplier)</b>\n\n" +
                    "Performance is based on PPO score and highest block. Usage comes from Normal Mode runs and frames."] =
                "<b><sprite name=\"insight\" tint=1> ~= round((1 + performance x 1.25 + cycleCarry) x usage x insightMultiplier)</b>\n\n" +
                "El rendimiento se basa en la puntuación de PPO y el bloque más alto. El uso proviene de las runs y frames en modo normal.",

            ["The core gameplay is very simple. Place blocks into one of the four stacks.\n\n" +
                    "You can merge two blocks of the same value by placing one on top of the other, earning more score and a larger in-game currency reward <sprite name=\"chips\" tint=1>.\n\n" +
                    "Always make sure there is at least one free space available, and try to keep your runs going for as long as possible. A run ends when the next block can no longer be placed anywhere."] =
                "La jugabilidad principal es muy simple. Coloca bloques en una de las cuatro pilas.\n\n" +
                "Puedes fusionar dos bloques del mismo valor colocando uno sobre otro, ganando más puntos y una mayor recompensa de moneda del juego <sprite name=\"chips\" tint=1>.\n\n" +
                "Asegúrate siempre de tener al menos un espacio libre, e intenta mantener tus runs el mayor tiempo posible. Una run termina cuando el siguiente bloque ya no puede colocarse en ninguna parte.",
            ["The gameplay changes early on, when algorithms begin playing instead of you. From that point forward, your job is to spend your income on upgrades that make future runs faster, longer, and more valuable."] =
                "La jugabilidad cambia pronto, cuando los algoritmos empiezan a jugar en tu lugar. A partir de ahí, tu trabajo es gastar tus ingresos en mejoras que hacen las runs futuras más rápidas, largas y valiosas.",
            ["The stage multiplier starts at 1x, increases to 5x after unlocking Agents, and reaches 24x after unlocking Modifiers. Because of this, unlocking a new layer is usually more valuable than buying another standard income upgrade."] =
                "El multiplicador de fase empieza en 1x, sube a 5x tras desbloquear los agentes y llega a 24x tras desbloquear los modificadores. Por eso, desbloquear una nueva capa suele valer más que comprar otra mejora de ingresos estándar.",
            ["Algorithms (solvers) automatically play the game for you.\n\n" +
                    "When Auto Solve is enabled, the selected solver places the blocks. If no solver is selected, the run remains Manual."] =
                "Los algoritmos (solvers) juegan automáticamente por ti.\n\n" +
                "Cuando la Resolución auto está activada, el solver elegido coloca los bloques. Si no hay solver elegido, la run permanece manual.",
            ["Each solver prioritizes different values when making decisions, so comparing them is worthwhile.\n\n" +
                    "Their behavior can be adjusted after unlocking Tuning. Tuning parameters can be modified using sliders, but their effects may also negatively impact gameplay.\n\n" +
                    "Besides search depth, the biggest difference between solvers is their speed. Solver speed can be upgraded in several places throughout the game."] =
                "Cada solver prioriza valores distintos al decidir, así que vale la pena compararlos.\n\n" +
                "Su comportamiento se ajusta tras desbloquear el Ajuste. Los parámetros se modifican con controles deslizantes, pero sus efectos también pueden perjudicar la jugabilidad.\n\n" +
                "Además de la profundidad de búsqueda, la mayor diferencia entre solvers es su velocidad. La velocidad del solver se mejora en varios lugares del juego.",
            ["The ultimate goal is to unlock PPO, which is a learning algorithm. It starts out weak because it doesn't understand the game's rules, so it must first be trained in Training Mode.\n\n" +
                    "Later, it becomes the gateway to Prestige and permanent progression.\n\n" +
                    "<b>The requirements to unlock it only become achievable later in the game.</b>"] =
                "El objetivo final es desbloquear PPO, un algoritmo de aprendizaje. Empieza débil porque no entiende las reglas del juego, así que primero debe entrenarse en modo entrenamiento.\n\n" +
                "Más tarde, se convierte en la puerta al prestigio y la progresión permanente.\n\n" +
                "<b>Los requisitos para desbloquearlo solo se vuelven alcanzables más adelante en el juego.</b>",
            ["This is the primary place to spend <sprite name=\"chips\" tint=1> during the early game.\n\n" +
                    "Here you unlock automation, speed up and expand gameplay, and increase your income generation.\n\n" +
                    "<b>Some upgrades have little impact on their own but become much stronger when combined with others.</b>"] =
                "Este es el lugar principal para gastar <sprite name=\"chips\" tint=1> al inicio del juego.\n\n" +
                "Aquí desbloqueas la automatización, aceleras y amplías la jugabilidad, y aumentas tu generación de ingresos.\n\n" +
                "<b>Algunas mejoras tienen poco impacto por sí solas pero se vuelven mucho más fuertes combinadas con otras.</b>",
            ["It's recommended to purchase automation upgrades first so you can start focusing on management as soon as possible."] =
                "Se recomienda comprar primero las mejoras de automatización para poder centrarte en la gestión lo antes posible.",
            ["<b>Keep in mind that Auto Restart consumes <sprite name=\"token\" tint=1>, and cannot function without it.</b>"] =
                "<b>Ten en cuenta que el reinicio auto consume <sprite name=\"token\" tint=1> y no puede funcionar sin ellos.</b>",
            ["<b>Unlocking Agents increases the game to a 5x stage multiplier.</b>"] =
                "<b>Desbloquear los agentes sube el multiplicador de fase a 5x.</b>",
            ["Agents provide active loadout bonuses.\n\n" +
                    "Simply purchasing an Agent isn't enough to make it available, it must also be selected. By default, you can equip two Agents at once, and this limit can be increased through upgrades."] =
                "Los agentes proporcionan bonos de loadout activos.\n\n" +
                "Comprar un agente no basta para tenerlo disponible, también hay que seleccionarlo. Por defecto puedes equipar dos agentes a la vez, y este límite se aumenta con mejoras.",
            ["<b>The combination of equipped Agents determines which aspect of a run becomes more efficient, since most Agents improve a specific reward source instead of multiplying the entire economy.</b>"] =
                "<b>La combinación de agentes equipados determina qué aspecto de una run se vuelve más eficiente, ya que la mayoría de los agentes mejoran una fuente de recompensa concreta en lugar de multiplicar toda la economía.</b>",
            ["Some Agents have little effect on their own, but become significantly stronger when combined with other Agents and upgrades."] =
                "Algunos agentes tienen poco efecto por sí solos, pero se vuelven mucho más fuertes combinados con otros agentes y mejoras.",
            ["Choose Agents based on what's currently limiting your progress. If runs end too quickly, prioritize stability. Once your runs are long enough, score, high-block, or merge rewards become more valuable."] =
                "Elige agentes según lo que limita tu progreso. Si las runs terminan muy rápido, prioriza la estabilidad. Cuando tus runs son bastante largas, las recompensas de puntuación, bloque alto o fusión ganan valor.",
            ["<b>Unlocking Modifiers increases the game to a 24x stage multiplier.</b>"] =
                "<b>Desbloquear los modificadores sube el multiplicador de fase a 24x.</b>",
            ["Modifiers change the rules of future runs. They provide a higher ceiling, a more flexible board, and more tools for advanced solvers to take advantage of."] =
                "Los modificadores cambian las reglas de las runs futuras. Ofrecen un techo más alto, un tablero más flexible y más herramientas que los solvers avanzados pueden aprovechar.",
            ["Some Modifiers grant actions that can be freely used during gameplay. Every Modifier can also be used in Manual Mode."] =
                "Algunos modificadores otorgan acciones que se pueden usar libremente durante el juego. Cada modificador también se puede usar en modo manual.",
            ["Research is responsible for speeding up and deepening future playthroughs, and it is also where Prestige Reset becomes available.\n\n" +
                    "Here you can purchase permanent upgrades that make gameplay easier, but they require <sprite name=\"insight\" tint=1>.\n\n"] =
                "La investigación se encarga de acelerar y profundizar las partidas futuras, y también es donde se habilita el reinicio de prestigio.\n\n" +
                "Aquí puedes comprar mejoras permanentes que facilitan el juego, pero requieren <sprite name=\"insight\" tint=1>.\n\n",
            ["<sprite name=\"insight\" tint=1> is generated by letting PPO play in Normal Mode.\n\n" +
                    "<b>You must perform a Prestige Reset to claim your <sprite name=\"insight\" tint=1>.</b>"] =
                "El <sprite name=\"insight\" tint=1> se genera dejando que PPO juegue en modo normal.\n\n" +
                "<b>Debes realizar un reinicio de prestigio para reclamar tu <sprite name=\"insight\" tint=1>.</b>",
            ["A Prestige Reset removes all accumulated <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, Upgrades, Agents, and Modifiers.\n\n" +
                    "However, your <sprite name=\"insight\" tint=1>, purchased Research, permanent PPO knowledge, and Datacenter progress are preserved."] =
                "Un reinicio de prestigio elimina todos los <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, mejoras, agentes y modificadores acumulados.\n\n" +
                "Sin embargo, tu <sprite name=\"insight\" tint=1>, la investigación comprada, el conocimiento permanente de PPO y el progreso del centro de datos se conservan.",
            ["Datacenter is a permanent compute layer that unlocks after your 5th Prestige Reset.\n\n" +
                    "Every upgrade here accelerates different stages of gameplay.\n\n" +
                    "This layer uses <sprite name=\"chips\" tint=1> as its currency again, meaning the production accumulated by PPO in Normal Mode is no longer lost after Prestige Reset."] =
                "El centro de datos es una capa de cómputo permanente que se desbloquea tras tu 5.º reinicio de prestigio.\n\n" +
                "Cada mejora aquí acelera distintas fases del juego.\n\n" +
                "Esta capa vuelve a usar los <sprite name=\"chips\" tint=1> como moneda, así que la producción acumulada por PPO en modo normal ya no se pierde tras un reinicio de prestigio.",
            ["<b>Be sure to spend your accumulated <sprite name=\"chips\" tint=1> before performing a Prestige Reset, otherwise they will be lost.</b>"] =
                "<b>Asegúrate de gastar tus <sprite name=\"chips\" tint=1> acumulados antes de un reinicio de prestigio, o se perderán.</b>",
            ["You can purchase Server Racks and Facility Upgrades, then allocate the resulting compute capacity however you like between passive PPO training, passive <sprite name=\"insight\" tint=1> generation, or a <sprite name=\"chips\" tint=1> income multiplier."] =
                "Puedes comprar racks de servidores y mejoras de instalación, y luego asignar la capacidad de cómputo resultante como quieras entre entrenamiento PPO pasivo, generación pasiva de <sprite name=\"insight\" tint=1> o un multiplicador de ingresos de <sprite name=\"chips\" tint=1>.",

            ["Place the blocks into one of the four stacks.\n\n" +
                "By placing two blocks with the same value on top of each other, you can merge them, earning more score and receiving a larger in-game currency <sprite name=\"chips\" tint=1> reward.\n\n" +
                "Make sure to always keep at least one free space available, and try to make your runs last as long as possible.\n\n" +
                "The gameplay changes early on, when algorithms start playing instead of you. From that point onward, your role is to purchase various upgrades and manage them.\n\n" +
                "<b>You can find details about every important game feature in Settings > How to Play menu.</b>"] =
                "Coloca los bloques en una de las cuatro pilas.\n\n" +
                "Al poner dos bloques del mismo valor uno sobre otro, los fusionas, ganando más puntos y una mayor recompensa de moneda del juego <sprite name=\"chips\" tint=1>.\n\n" +
                "Mantén siempre al menos un espacio libre e intenta que tus runs duren lo máximo posible.\n\n" +
                "La jugabilidad cambia pronto, cuando los algoritmos empiezan a jugar en tu lugar. A partir de ahí, tu papel es comprar diversas mejoras y gestionarlas.\n\n" +
                "<b>Encontrarás detalles de cada función importante en Ajustes > Cómo jugar.</b>",
            ["Algorithms are responsible for playing the game automatically for you.\n\n" +
                "Each solver prioritizes different values when making decisions, so it's worth comparing them. Their behavior can be tuned once Tuning is unlocked.\n\n" +
                "The ultimate goal is to unlock PPO, which is a learning algorithm. The requirements for unlocking it can only be met later in the game."] =
                "Los algoritmos se encargan de jugar automáticamente por ti.\n\n" +
                "Cada solver prioriza valores distintos al decidir, así que vale la pena compararlos. Su comportamiento se ajusta una vez desbloqueado el Ajuste.\n\n" +
                "El objetivo final es desbloquear PPO, un algoritmo de aprendizaje. Sus requisitos de desbloqueo solo se pueden cumplir más adelante en el juego.",
            ["Upgrades are the early-game progression layer based on <sprite name=\"chips\" tint=1>.\n\n" +
                "This is where you unlock automation, speed up and expand gameplay, and increase your income generation.\n\n" +
                "It's generally best to prioritize automation upgrades so you can focus on managing your run as early as possible.\n\n" +
                "<b>Keep in mind that Auto Restart consumes <sprite name=\"token\" tint=1>.</b>"] =
                "Las mejoras son la capa de progresión del inicio del juego basada en <sprite name=\"chips\" tint=1>.\n\n" +
                "Aquí desbloqueas la automatización, aceleras y amplías la jugabilidad, y aumentas tu generación de ingresos.\n\n" +
                "Suele ser mejor priorizar las mejoras de automatización para centrarte en gestionar tu run lo antes posible.\n\n" +
                "<b>Ten en cuenta que el reinicio auto consume <sprite name=\"token\" tint=1>.</b>",
            ["Agents provide active loadout bonuses.\n\n" +
                "Not every owned Agent is active: the combination equipped in your slots determines which aspects of your run become more effective."] =
                "Los agentes proporcionan bonos de loadout activos.\n\n" +
                "No todos los agentes que posees están activos: la combinación equipada en tus ranuras determina qué aspectos de tu run se vuelven más eficaces.",
            ["Modifiers change the rules of future runs. They unlock new possibilities and increase your income, but they also make the board more complex.\n\n" +
                "Some Modifiers can be upgraded multiple times.\n\n" +
                "<b>Purchasing every Modifier unlocks the PPO algorithm, marking the gateway to the endgame.</b>"] =
                "Los modificadores cambian las reglas de las runs futuras. Abren nuevas posibilidades y aumentan tus ingresos, pero también hacen el tablero más complejo.\n\n" +
                "Algunos modificadores se pueden mejorar varias veces.\n\n" +
                "<b>Comprar cada modificador desbloquea el algoritmo PPO, la puerta al final del juego.</b>",
            ["Research is the progression layer that unlocks the ability to Prestige Reset.\n\n" +
                "Here, you can purchase permanent upgrades that make gameplay easier and faster, but they require <sprite name=\"insight\" tint=1>.\n\n" +
                "<sprite name=\"insight\" tint=1> is generated by running the PPO algorithm in Normal Mode.\n\n" +
                "To claim your <sprite name=\"insight\" tint=1>, you must perform a Prestige Reset. You can find details in the Console."] =
                "La investigación es la capa de progresión que desbloquea el reinicio de prestigio.\n\n" +
                "Aquí puedes comprar mejoras permanentes que hacen el juego más fácil y rápido, pero requieren <sprite name=\"insight\" tint=1>.\n\n" +
                "El <sprite name=\"insight\" tint=1> se genera al ejecutar el algoritmo PPO en modo normal.\n\n" +
                "Para reclamar tu <sprite name=\"insight\" tint=1>, debes realizar un reinicio de prestigio. Encontrarás detalles en la Consola.",
            ["Datacenter is a persistent compute layer that speeds up your Prestiges.\n\n" +
                "Here, <sprite name=\"chips\" tint=1> becomes the currency again, meaning the production accumulated in PPO Normal Mode is no longer wasted when you perform a Prestige Reset.\n\n" +
                "<b>Be sure to spend your accumulated <sprite name=\"chips\" tint=1> before resetting, as any unspent amount will be lost.</b>\n\n" +
                "You can purchase Server Racks and Facility Upgrades, then allocate the resulting compute capacity however you like: to passive PPO training, passive <sprite name=\"insight\" tint=1> generation, or a <sprite name=\"chips\" tint=1> production multiplier."] =
                "El centro de datos es una capa de cómputo persistente que acelera tus prestigios.\n\n" +
                "Aquí, los <sprite name=\"chips\" tint=1> vuelven a ser la moneda, así que la producción acumulada en modo normal PPO ya no se desperdicia al realizar un reinicio de prestigio.\n\n" +
                "<b>Asegúrate de gastar tus <sprite name=\"chips\" tint=1> acumulados antes de reiniciar, ya que cualquier cantidad sin gastar se perderá.</b>\n\n" +
                "Puedes comprar racks de servidores y mejoras de instalación, y luego asignar la capacidad de cómputo resultante como quieras: a entrenamiento PPO pasivo, generación pasiva de <sprite name=\"insight\" tint=1> o un multiplicador de producción de <sprite name=\"chips\" tint=1>.",
            ["Here you can see detailed data on how your runs perform during the current Prestige cycle.\n\n" +
                "You can view your highest score, best median performance, average run duration, and results for each solver.\n\n" +
                "<b>Measure how a new algorithm, Tuning, or any other modification affects your performance.</b>"] =
                "Aquí puedes ver datos detallados sobre el rendimiento de tus runs durante el ciclo de prestigio actual.\n\n" +
                "Puedes ver tu puntuación más alta, la mejor mediana, la duración media de las runs y los resultados de cada solver.\n\n" +
                "<b>Mide cómo un nuevo algoritmo, un ajuste o cualquier otra modificación afecta a tu rendimiento.</b>",
            ["Here you can track your best results achieved throughout your playtime, along with a summary of your overall progress. You can also see which goals you have already completed.\n\n" +
                "<b>Some milestones grant permanent rewards or cosmetic unlocks.</b>"] =
                "Aquí puedes seguir tus mejores resultados logrados a lo largo de tu tiempo de juego, junto con un resumen de tu progreso general. También ves qué objetivos ya has completado.\n\n" +
                "<b>Algunos hitos otorgan recompensas permanentes o desbloqueos cosméticos.</b>",

            // ---- Dynamically-composed labels + datacenter allocation bodies ----------------------
            ["reach Prestige"] = "alcanza Prestigio",
            ["rack FLOPS"] = "FLOPS de rack",
            ["TPU / Fabric"] = "TPU / Fabric",
            ["Effect"] = "Efecto",
            ["Level"] = "Nivel",
            ["Completed goals"] = "Objetivos completados",
            ["Best run"] = "Mejor run",
            ["moves"] = "movimientos",
            ["manual"] = "manual",
            ["Restart in"] = "Reinicio en",
            ["Equipped Agents"] = "Agentes equipados",
            ["Active Modifiers"] = "Modificadores activos",
            ["Buy all Facility Upgrades"] = "Compra todas las mejoras de instalación",
            ["Offline cap"] = "Límite offline",
            ["Offline efficiency"] = "Eficiencia offline",
            ["New-high learning"] = "Aprendizaje de récord",
            ["Survival shaping"] = "Modelado de supervivencia",
            ["PPO Normal mode at"] = "Modo normal PPO en",
            ["Start with"] = "Empieza con",
            ["cycle frames"] = "frames de ciclo",
            ["frames retained"] = "frames conservados",
            ["training: +0 chips"] = "entrenamiento: +0 fichas",
            ["Pickaxe"] = "Pico",
            ["Scrubbed"] = "Eliminado",
            ["Merge"] = "Fusión",
            ["Combo"] = "Combo",
            ["Spent"] = "Gastado",
            ["Passively trains PPO, which counts as Training Mode frames. <b>PPO learns permanently even when not in use.</b>"] =
                "Entrena PPO de forma pasiva, lo que cuenta como frames de modo entrenamiento. <b>PPO aprende de forma permanente aunque no se use.</b>",
            ["Passively generates <sprite name=\"insight\" tint=1> at any stage of the game, so using PPO in Normal Mode is no longer required for that."] =
                "Genera <sprite name=\"insight\" tint=1> de forma pasiva en cualquier etapa del juego, así que ya no hace falta usar PPO en modo normal para eso.",
            ["It gives an income multiplier to everything that produces <sprite name=\"chips\" tint=1> in any form."] =
                "Da un multiplicador de ingresos a todo lo que produce <sprite name=\"chips\" tint=1> de cualquier forma.",
        };
    }
}
