using System;
using System.Collections.Generic;

namespace StackMerge
{
    // German (Deutsch) translation table. Keys are the exact English source strings; sprite tags
    // like <sprite name="chips" tint=1> are preserved verbatim. Game-specific proper nouns (solver
    // names RAND/MERG/BAL/HEUR/LOOK/MOCA/PLAN/COMBO/MCTS, PPO) are kept as-is.
    internal static class StackMergeLocalizationDe
    {
        public static readonly Dictionary<string, string> Table = new(StringComparer.Ordinal)
        {
            ["Play"] = "Spiel",
            ["Algos"] = "Algos",
            ["Algorithms"] = "Algorithmen",
            ["Upgrades"] = "Upgrades",
            ["Agents"] = "Agenten",
            ["Mods"] = "Mods",
            ["Modifiers"] = "Modifikatoren",
            ["Research"] = "Forschung",
            ["DC"] = "RZ",
            ["Next"] = "Nächste",
            ["History"] = "Verlauf",
            ["Achievements"] = "Erfolge",
            ["Settings"] = "Einstellungen",
            ["Locked"] = "Gesperrt",
            ["Unlocked"] = "Freigeschaltet",
            ["Select"] = "Wählen",
            ["Deselect"] = "Abwählen",
            ["Tune"] = "Justieren",
            ["Change mode"] = "Modus wechseln",
            ["Buy"] = "Kaufen",
            ["Equip"] = "Ausrüsten",
            ["Unequip"] = "Ablegen",
            ["Maxed"] = "Maximal",
            ["Done"] = "Fertig",
            ["New run"] = "Neuer Run",
            ["Manual"] = "Manuell",
            ["Manual mode"] = "Manueller Modus",
            ["Auto solving"] = "Auto-Lösen",
            ["Run ended"] = "Run beendet",
            ["Run time"] = "Run-Zeit",
            ["Config info"] = "Konfig-Info",
            ["Import save"] = "Spielstand importieren",
            ["Automatization"] = "Automatisierung",
            ["Income Bonus"] = "Einkommensbonus",
            ["Passive Production"] = "Passive Produktion",
            ["Solver Speed"] = "Solver-Tempo",
            ["Stack Capacity"] = "Stack-Kapazität",
            ["Number of next blocks visible"] = "Anzahl sichtbarer nächster Blöcke",
            ["Higher blocks spawn"] = "Höhere Blöcke erscheinen",
            ["Lab Unlocks"] = "Lab-Freischaltungen",
            ["Passive PPO frame reduction"] = "Passive PPO-Frame-Reduktion",
            ["All Agents"] = "Alle Agenten",
            ["Base <sprite name=\"chips\" tint=1> income"] = "Basis-<sprite name=\"chips\" tint=1>-Einkommen",
            ["Ending profit"] = "Endgewinn",
            ["Merge streak"] = "Merge-Serie",
            ["Score salvage"] = "Punkte-Bergung",
            ["Passive <sprite name=\"chips\" tint=1> / tick"] = "Passive <sprite name=\"chips\" tint=1> / Tick",
            ["Passive tick rate"] = "Passive Tickrate",
            ["Active multiplier"] = "Aktiver Multiplikator",
            ["Faster solver"] = "Schnellerer Solver",
            ["Solver delay"] = "Solver-Verzögerung",
            ["Stack rows"] = "Stack-Reihen",
            ["Visible blocks"] = "Sichtbare Blöcke",
            ["Higher chance"] = "Höhere Chance",
            ["Higher frequency"] = "Höhere Frequenz",
            ["Stage Progression"] = "Phasen-Fortschritt",
            ["Prestige Console"] = "Prestige-Konsole",
            ["Collection"] = "Sammlung",
            ["PPO Training complete — prestige reset unlocked."] = "PPO-Training abgeschlossen — Prestige-Reset freigeschaltet.",
            ["Auto restart needs token"] = "Auto-Neustart braucht Token",
            ["The run hasn't started yet."] = "Der Run hat noch nicht begonnen.",
            ["No moves left — run over"] = "Keine Züge mehr — Run vorbei",
            ["Not enough <sprite name=\"chips\" tint=1>"] = "Nicht genug <sprite name=\"chips\" tint=1>",
            ["Buy an algorithm first"] = "Kaufe zuerst einen Algorithmus",
            ["Speed upgrade unavailable"] = "Tempo-Upgrade nicht verfügbar",
            ["Stack upgrade unavailable"] = "Stack-Upgrade nicht verfügbar",
            ["Next preview upgrade unavailable"] = "Next-Vorschau-Upgrade nicht verfügbar",
            ["Income upgrade unavailable"] = "Einkommens-Upgrade nicht verfügbar",
            ["Solver tuning unlocked"] = "Solver-Justierung freigeschaltet",
            ["Auto solve updated"] = "Auto-Lösen aktualisiert",
            ["Auto restart updated"] = "Auto-Neustart aktualisiert",
            ["Modifier Lab unlocked"] = "Modifikator-Lab freigeschaltet",
            ["Unlock Agents in Upgrades first"] = "Schalte zuerst die Agenten in den Upgrades frei",
            ["Unlock Modifier Lab in Upgrades first"] = "Schalte zuerst das Modifikator-Lab in den Upgrades frei",
            ["Finish PPO Training first"] = "Beende zuerst das PPO-Training",
            ["Unlock PPO to open Research"] = "Schalte PPO frei, um die Forschung zu öffnen",
            ["Normal mode is still locked."] = "Der Normalmodus ist noch gesperrt.",
            ["PPO: Training mode"] = "PPO: Trainingsmodus",
            ["PPO: Normal mode"] = "PPO: Normalmodus",
            ["Training Mode"] = "Trainingsmodus",
            ["Normal Mode"] = "Normalmodus",
            ["Normal Mode\nLocked"] = "Normalmodus\nGesperrt",
            ["PPO Mode Overlay is not assigned."] = "PPO Mode Overlay ist nicht zugewiesen.",
            ["Training: keeps learning, earns no chips.\nNormal: plays for chips like other solvers."] = "Training: lernt weiter, verdient keine Chips.\nNormal: spielt für Chips wie andere Solver.",
            ["Music"] = "Musik",
            ["Sound"] = "Ton",
            ["Enable haptic feedback"] = "Haptisches Feedback aktivieren",
            ["Show FPS"] = "FPS anzeigen",
            ["Hide FPS"] = "FPS verbergen",
            ["Achievement Pop-ups"] = "Erfolgs-Pop-ups",
            ["Hide achievement pop-ups"] = "Erfolgs-Pop-ups ausblenden",
            ["Export / Import game"] = "Spiel exportieren / importieren",
            ["Language"] = "Sprache",
            ["Manual controls"] = "Manuelle Steuerung",
            ["Tap a stack to place the current next block."] = "Tippe auf einen Stack, um den aktuellen nächsten Block zu platzieren.",
            ["Equip Miner's Pickaxe, then tap a stack block to remove it."] = "Rüste die Miner's Pickaxe aus und tippe dann auf einen Stack-Block, um ihn zu entfernen.",
            ["Equip Queue Scrubber, then tap the first next block to remove it."] = "Rüste den Queue Scrubber aus und tippe dann auf den ersten nächsten Block, um ihn zu entfernen.",
            ["Tap a block to remove it with Miner's Pickaxe"] = "Tippe auf einen Block, um ihn mit der Miner's Pickaxe zu entfernen",
            ["Tap the first next block to scrub it"] = "Tippe auf den ersten nächsten Block, um ihn zu entfernen",
            ["Miner's Pickaxe equipped"] = "Miner's Pickaxe ausgerüstet",
            ["Miner's Pickaxe unequipped"] = "Miner's Pickaxe abgelegt",
            ["Queue Scrubber equipped"] = "Queue Scrubber ausgerüstet",
            ["Queue Scrubber unequipped"] = "Queue Scrubber abgelegt",
            ["Miner's Pickaxe is locked"] = "Die Miner's Pickaxe ist gesperrt",
            ["Queue Scrubber is locked"] = "Der Queue Scrubber ist gesperrt",
            ["Miner's Pickaxe has no uses left"] = "Keine Miner's-Pickaxe-Nutzungen mehr übrig",
            ["Queue Scrubber has no uses left"] = "Keine Queue-Scrubber-Nutzungen mehr übrig",
            ["No block available for Miner's Pickaxe"] = "Kein Block für die Miner's Pickaxe verfügbar",
            ["No next block available for Queue Scrubber"] = "Kein nächster Block für den Queue Scrubber verfügbar",
            ["Modifier unavailable"] = "Modifikator nicht verfügbar",
            ["Unlocks rule-changing modules that apply to new runs."] = "Schaltet regeländernde Module frei, die für neue Runs gelten.",
            ["The solver places blocks faster with each level."] = "Der Solver platziert Blöcke mit jeder Stufe schneller.",
            ["Solver is automatically playing the game."] = "Der Solver spielt das Spiel automatisch.",
            ["When the run ends, a new one starts automatically."] = "Wenn der Run endet, startet automatisch ein neuer.",
            ["The currency for Auto restart."] = "Die Währung für den Auto-Neustart.",
            ["Allows you to modify the solver parameters."] = "Ermöglicht das Anpassen der Solver-Parameter.",
            ["Another slot so you can use 3 Agents at once."] = "Ein weiterer Slot, um 3 Agenten gleichzeitig zu nutzen.",
            ["They give you extra bonuses when you unlock them."] = "Sie geben zusätzliche Boni, wenn du sie freischaltest.",
            ["Increases the capacity of each stack by 1 per level."] = "Erhöht die Kapazität jedes Stacks um 1 pro Stufe.",
            ["Shows 1 more upcoming block per level."] = "Zeigt pro Stufe 1 kommenden Block mehr.",
            ["Increases the chance of spawning higher blocks."] = "Erhöht die Chance auf höhere Blöcke.",
            ["Slightly increases how often higher blocks appear."] = "Erhöht leicht, wie oft höhere Blöcke erscheinen.",
            ["Boosts base <sprite name=\"chips\" tint=1> income. Early levels give larger gains."] = "Steigert das Basis-<sprite name=\"chips\" tint=1>-Einkommen. Frühe Stufen bringen mehr.",
            ["Boosts the <sprite name=\"chips\" tint=1> bonus at the end of the runs."] = "Steigert den <sprite name=\"chips\" tint=1>-Bonus am Ende der Runs.",
            ["Boosts the <sprite name=\"chips\" tint=1> earned during merges and runs."] = "Steigert die aus Merges und Runs verdienten <sprite name=\"chips\" tint=1>.",
            ["Shrinks the delay of MOCA and PLAN solvers."] = "Verkürzt die Verzögerung der Solver MOCA und PLAN.",
            ["Chips trickle in on a timer, on top of your normal play."] = "Chips fließen zusätzlich zum normalen Spiel per Timer ein.",
            ["Passive Production ticks more often."] = "Die Passive Produktion tickt häufiger.",
            ["Lowers the frame needed in Training Mode."] = "Senkt die im Trainingsmodus nötigen Frames.",
            ["Lowers the frames needed for PPO Normal Mode."] = "Senkt die für den PPO-Normalmodus nötigen Frames.",
            ["Each level shortens how often Curriculum lowers the PPO requirement."] = "Jede Stufe verkürzt, wie oft das Curriculum die PPO-Anforderung senkt.",
            ["Needs Difficulty L1"] = "Braucht Schwierigkeit L1",
            ["Needs PPO or Bootcamp L5"] = "Braucht PPO oder Bootcamp L5",
            ["Needs Curriculum"] = "Braucht Curriculum",
            ["Boosts Passive Production while you're actively playing."] = "Steigert die Passive Produktion, während du aktiv spielst.",
            ["Passive yield upgrade unavailable"] = "Passiv-Ertrag-Upgrade nicht verfügbar",
            ["Passive tick rate upgrade unavailable"] = "Passiv-Tickrate-Upgrade nicht verfügbar",
            ["Active multiplier upgrade unavailable"] = "Aktiv-Multiplikator-Upgrade nicht verfügbar",
            ["Compute speed upgrade unavailable"] = "Rechentempo-Upgrade nicht verfügbar",
            ["Stage locked"] = "Phase gesperrt",
            ["Needs algorithm"] = "Braucht Algorithmus",
            ["Needs Agents"] = "Braucht Agenten",
            ["Stage 1 - Core automation"] = "Phase 1 - Basis-Automatisierung",
            ["Stage 2 - Agent acceleration"] = "Phase 2 - Agenten-Beschleunigung",
            ["Stage 3 - Modifier Lab"] = "Phase 3 - Modifikator-Lab",
            ["Stage 4 - Machine Learning"] = "Phase 4 - Maschinelles Lernen",
            ["Endgame - PPO training"] = "Endgame - PPO-Training",
            ["Train PPO, then prestige from the Research menu."] = "Trainiere PPO und mache dann Prestige über das Forschungsmenü.",
            ["PPO is ready to unlock in Algorithms."] = "PPO kann in den Algorithmen freigeschaltet werden.",
            ["Max every Modifier to open the Machine Learning layer."] = "Maximiere jeden Modifikator, um die Machine-Learning-Ebene zu öffnen.",
            ["Open Agents to start the next stage."] = "Öffne die Agenten, um die nächste Phase zu starten.",
            ["Unlock COMBO or LOOK solver to open Agents."] = "Schalte den Solver COMBO oder LOOK frei, um die Agenten zu öffnen.",
            ["Unlock COMBO or LOOK solver first."] = "Schalte zuerst den Solver COMBO oder LOOK frei.",
            ["Modifiers Lab"] = "Modifikator-Lab",
            ["Agents Lab"] = "Agenten-Lab",
            ["Stack capacity"] = "Stack-Kapazität",
            ["Difficulty"] = "Schwierigkeit",
            ["Speed"] = "Tempo",
            ["Auto solve"] = "Auto-Lösen",
            ["Auto restart"] = "Auto-Neustart",
            ["Mode"] = "Modus",
            ["Run score"] = "Run-Punkte",
            ["Score"] = "Punkte",
            ["Median"] = "Median",
            ["Best"] = "Beste",
            ["Moves"] = "Züge",
            ["Merges"] = "Merges",
            ["Current next"] = "Aktueller Next",
            ["Available actions"] = "Verfügbare Aktionen",
            ["Solver"] = "Solver",
            ["Run modifiers"] = "Run-Modifikatoren",
            ["Special blocks"] = "Spezialblöcke",
            ["Solver tuning"] = "Solver-Justierung",
            ["+50 tokens"] = "+50 Token",
            ["Locked in Upgrades."] = "In den Upgrades freischaltbar.",
            ["No tuning available for this solver."] = "Für diesen Solver ist keine Justierung verfügbar.",
            ["Default"] = "Standard",
            ["RAND has no tuning. Its identity is pure randomness."] = "RAND hat keine Justierung. Seine Identität ist reiner Zufall.",
            ["MERG stays greedy, but these sliders decide how hard it chases immediate value."] = "MERG bleibt gierig, aber diese Regler bestimmen, wie stark er sofortigen Wert jagt.",
            ["BAL remains a board stabilizer. Tune how defensive or merge-friendly it should be."] = "BAL bleibt ein Brett-Stabilisator. Stelle ein, wie defensiv oder merge-freundlich er sein soll.",
            ["HEUR is a weighted score formula. These are the clearest direct knobs."] = "HEUR ist eine gewichtete Punkteformel. Dies sind die klarsten direkten Regler.",
            ["LOOK uses HEUR plus a follow-up estimate. Tune its greed and its second-step trust."] = "LOOK nutzt HEUR plus eine Folgezug-Schätzung. Stelle seine Gier und sein Vertrauen in den zweiten Schritt ein.",
            ["MOCA samples futures. Its tuning can spend a little more thinking on rollout depth or sample count."] = "MOCA sampelt Zukünfte. Seine Justierung kann etwas mehr Rechenzeit auf Rollout-Tiefe oder Sample-Anzahl legen.",
            ["PLAN searches the visible queue. Tune how much it trusts short plans over current safety."] = "PLAN durchsucht die sichtbare Queue. Stelle ein, wie sehr er kurzen Plänen gegenüber aktueller Sicherheit vertraut.",
            ["PLAN-5 searches deeper queue lines. Tuning lets you decide whether it should be patient or practical."] = "PLAN-5 durchsucht tiefere Queue-Linien. Die Justierung entscheidet, ob er geduldig oder praktisch sein soll.",
            ["MOCA+ uses smarter rollouts. Tuning affects both how much it samples and how it values rollout boards."] = "MOCA+ nutzt klügere Rollouts. Die Justierung beeinflusst sowohl das Sampling als auch die Bewertung der Rollout-Bretter.",
            ["MCTS builds a tree. These sliders tune search behavior without replacing the tree search identity."] = "MCTS baut einen Baum. Diese Regler justieren das Suchverhalten, ohne die Baumsuche-Identität zu ersetzen.",
            ["STALL is defensive. Tune how much it sacrifices score to keep the board alive."] = "STALL ist defensiv. Stelle ein, wie viel Punkte er opfert, um das Brett am Leben zu halten.",
            ["COMBO looks for chain setups. Tune how patient it should be while preparing cascades."] = "COMBO sucht nach Ketten-Vorbereitungen. Stelle ein, wie geduldig er beim Aufbau von Kaskaden sein soll.",
            ["PPO trains its own actor-critic network. These nudge the learning hyperparameters within safe bounds."] = "PPO trainiert sein eigenes Actor-Critic-Netz. Diese verschieben die Lern-Hyperparameter in sicheren Grenzen.",
            ["Merge reward"] = "Merge-Belohnung",
            ["Score delta"] = "Punkte-Delta",
            ["High block"] = "Hoher Block",
            ["Height penalty"] = "Höhenstrafe",
            ["Empty cells"] = "Leere Zellen",
            ["Smoothness"] = "Glätte",
            ["Danger penalty"] = "Gefahrenstrafe",
            ["Queue fit"] = "Queue-Passung",
            ["Follow-up trust"] = "Folgezug-Vertrauen",
            ["Simulation rounds"] = "Simulationsrunden",
            ["Rollout moves"] = "Rollout-Züge",
            ["Planning depth"] = "Planungstiefe",
            ["Future weight"] = "Zukunftsgewicht",
            ["Rollout planning"] = "Rollout-Planung",
            ["Board eval"] = "Brettbewertung",
            ["Anti-stall"] = "Anti-Stall",
            ["Tree visits"] = "Baum-Besuche",
            ["Exploration"] = "Erkundung",
            ["Prior bias"] = "Prior-Gewicht",
            ["Safety cushion"] = "Sicherheitspolster",
            ["Combo setup"] = "Combo-Vorbereitung",
            ["Legal moves"] = "Legale Züge",
            ["Height spread"] = "Höhenverteilung",
            ["Future depth"] = "Zukunftstiefe",
            ["Gamma (discount)"] = "Gamma (Diskont)",
            ["Lambda (GAE)"] = "Lambda (GAE)",
            ["Clip epsilon"] = "Clip-Epsilon",
            ["Raises or lowers the reward for immediate merges and cascade size."] = "Erhöht oder senkt die Belohnung für sofortige Merges und Kaskadengröße.",
            ["Changes how much raw score gained by the move matters."] = "Ändert, wie stark die durch den Zug gewonnenen Rohpunkte zählen.",
            ["Pushes the solver toward producing larger top blocks."] = "Drängt den Solver dazu, größere oberste Blöcke zu erzeugen.",
            ["Positive values avoid tall uneven stacks more strongly."] = "Positive Werte vermeiden hohe, ungleiche Stacks stärker.",
            ["Rewards boards with more open cells after the move."] = "Belohnt Bretter mit mehr freien Zellen nach dem Zug.",
            ["Rewards similar stack heights and penalizes lopsided boards."] = "Belohnt ähnliche Stack-Höhen und bestraft schiefe Bretter.",
            ["Penalizes stacks near capacity more strongly."] = "Bestraft Stacks nahe der Kapazität stärker.",
            ["Lets BAL accept more merge value before spreading out."] = "Lässt BAL mehr Merge-Wert annehmen, bevor er sich verteilt.",
            ["Changes how strongly immediate score gain affects the move score."] = "Ändert, wie stark der sofortige Punktgewinn die Zugbewertung beeinflusst.",
            ["Rewards free stack cells after the move."] = "Belohnt freie Stack-Zellen nach dem Zug.",
            ["Rewards smoother stack heights and fewer awkward bottlenecks."] = "Belohnt gleichmäßigere Stack-Höhen und weniger unangenehme Engpässe.",
            ["Rewards top blocks that match upcoming queue values."] = "Belohnt oberste Blöcke, die zu kommenden Queue-Werten passen.",
            ["Raises or lowers the value of immediate merge chains."] = "Erhöht oder senkt den Wert sofortiger Merge-Ketten.",
            ["Makes near-full stacks scarier to the heuristic."] = "Lässt fast volle Stacks für die Heuristik bedrohlicher wirken.",
            ["Changes how much the first move's score gain matters."] = "Ändert, wie stark der Punktgewinn des ersten Zuges zählt.",
            ["Rewards keeping more room open after the first move."] = "Belohnt es, nach dem ersten Zug mehr Platz frei zu halten.",
            ["Changes how much the simulated next move influences the choice."] = "Ändert, wie stark der simulierte nächste Zug die Wahl beeinflusst.",
            ["Rewards stack tops that line up with visible upcoming blocks."] = "Belohnt Stack-Spitzen, die zu sichtbaren kommenden Blöcken passen.",
            ["Punishes positions that are close to stalling."] = "Bestraft Positionen, die kurz vor dem Stillstand stehen.",
            ["Adjusts how many futures are sampled for each legal move."] = "Passt an, wie viele Zukünfte pro legalem Zug gesampelt werden.",
            ["Adjusts how many moves each future is played forward."] = "Passt an, wie viele Züge jede Zukunft vorgespielt wird.",
            ["Changes the immediate score bias inside rollout evaluation."] = "Ändert die Sofortpunkt-Gewichtung in der Rollout-Bewertung.",
            ["Rewards futures that leave more cells open."] = "Belohnt Zukünfte, die mehr Zellen frei lassen.",
            ["Makes dangerous simulated boards less attractive."] = "Macht gefährliche simulierte Bretter weniger attraktiv.",
            ["Rewards rollouts that keep useful top blocks for the visible queue."] = "Belohnt Rollouts, die nützliche oberste Blöcke für die sichtbare Queue behalten.",
            ["Shifts how many visible queued blocks the search tries to use."] = "Verschiebt, wie viele sichtbare Queue-Blöcke die Suche zu nutzen versucht.",
            ["Changes how strongly future planned moves affect the first move."] = "Ändert, wie stark zukünftige geplante Züge den ersten Zug beeinflussen.",
            ["Rewards stack tops that match upcoming values."] = "Belohnt Stack-Spitzen, die zu kommenden Werten passen.",
            ["Rewards planned lines that keep space available."] = "Belohnt geplante Linien, die Platz frei halten.",
            ["Penalizes plans that leave near-full stacks."] = "Bestraft Pläne, die fast volle Stacks hinterlassen.",
            ["Shifts how many queued blocks the search tries to use."] = "Verschiebt, wie viele Queue-Blöcke die Suche zu nutzen versucht.",
            ["Changes how strongly deeper planned scores affect the first move."] = "Ändert, wie stark tiefere geplante Punkte den ersten Zug beeinflussen.",
            ["Rewards preserving useful stack tops for upcoming blocks."] = "Belohnt das Bewahren nützlicher Stack-Spitzen für kommende Blöcke.",
            ["Rewards plans that leave more board room."] = "Belohnt Pläne, die mehr Brettplatz lassen.",
            ["Penalizes risky deep plans more strongly."] = "Bestraft riskante tiefe Pläne stärker.",
            ["Adjusts how many smart futures are sampled for each move."] = "Passt an, wie viele smarte Zukünfte pro Zug gesampelt werden.",
            ["Adjusts how far smart futures are played forward."] = "Passt an, wie weit smarte Zukünfte vorgespielt werden.",
            ["Adjusts how much queue planning each rollout uses."] = "Passt an, wie viel Queue-Planung jeder Rollout nutzt.",
            ["Changes how much the final simulated board shape matters."] = "Ändert, wie stark die endgültige simulierte Brettform zählt.",
            ["Rewards futures that preserve legal moves and escape routes."] = "Belohnt Zukünfte, die legale Züge und Fluchtwege bewahren.",
            ["Adjusts how many tree iterations are spent per decision."] = "Passt an, wie viele Baum-Iterationen pro Entscheidung verwendet werden.",
            ["Higher values try less-proven branches more often."] = "Höhere Werte probieren weniger bewährte Zweige häufiger.",
            ["Changes how strongly heuristic prior scores guide the tree."] = "Ändert, wie stark heuristische Prior-Punkte den Baum leiten.",
            ["Adjusts how far rollouts play from a tree node."] = "Passt an, wie weit Rollouts von einem Baumknoten aus spielen.",
            ["Rewards tree lines that leave room and legal moves."] = "Belohnt Baum-Linien, die Platz und legale Züge lassen.",
            ["Rewards lines that create potential chain merges."] = "Belohnt Linien, die potenzielle Ketten-Merges schaffen.",
            ["Rewards positions with multiple available stacks."] = "Belohnt Positionen mit mehreren verfügbaren Stacks.",
            ["Rewards spare capacity after each move."] = "Belohnt freie Kapazität nach jedem Zug.",
            ["Punishes near-full stacks more strongly."] = "Bestraft fast volle Stacks stärker.",
            ["Penalizes uneven stack heights."] = "Bestraft ungleiche Stack-Höhen.",
            ["Lets STALL take more immediate merge value."] = "Lässt STALL mehr sofortigen Merge-Wert nehmen.",
            ["Rewards adjacent equal values and future cascade potential."] = "Belohnt benachbarte gleiche Werte und zukünftiges Kaskadenpotenzial.",
            ["Changes how much immediate merging competes with setup."] = "Ändert, wie stark sofortiges Mergen mit dem Aufbau konkurriert.",
            ["Adjusts how many setup moves the combo estimate looks through."] = "Passt an, wie viele Vorbereitungszüge die Combo-Schätzung durchsieht.",
            ["Keeps some space open while building combos."] = "Hält beim Combo-Aufbau etwas Platz frei.",
            ["How far ahead future reward is valued. Higher plans longer-term, lower is greedier."] = "Wie weit voraus zukünftige Belohnung zählt. Höher plant langfristiger, niedriger ist gieriger.",
            ["Advantage estimation bias/variance trade-off. Higher = lower bias, more variance."] = "Bias/Varianz-Abwägung der Advantage-Schätzung. Höher = weniger Bias, mehr Varianz.",
            ["How big a policy update each step may make. Smaller is more conservative and stable."] = "Wie groß ein Policy-Update pro Schritt sein darf. Kleiner ist konservativer und stabiler.",
            ["Completed"] = "Abgeschlossen",
            ["Secrets"] = "Geheimnisse",
            ["Statistics"] = "Statistiken",
            ["PPO Progress"] = "PPO-Fortschritt",
            ["No completed runs yet. Let a run end to start collecting solver stats."] = "Noch keine abgeschlossenen Runs. Lass einen Run enden, um Solver-Statistiken zu sammeln.",
            ["Tip: use the editor benchmark window for large balance samples without touching player progression."] = "Tipp: Nutze das Editor-Benchmark-Fenster für große Balance-Stichproben, ohne den Spielfortschritt zu berühren.",
            ["Earn 10000 <sprite name=\"chips\" tint=1> in total"] = "Verdiene insgesamt 10000 <sprite name=\"chips\" tint=1>",
            ["Earn 1M <sprite name=\"chips\" tint=1> in total"] = "Verdiene insgesamt 1M <sprite name=\"chips\" tint=1>",
            ["Earn 1B <sprite name=\"chips\" tint=1> in total"] = "Verdiene insgesamt 1B <sprite name=\"chips\" tint=1>",
            ["Spend 10000 <sprite name=\"chips\" tint=1> in total"] = "Gib insgesamt 10000 <sprite name=\"chips\" tint=1> aus",
            ["Spend 100K <sprite name=\"chips\" tint=1> in total"] = "Gib insgesamt 100K <sprite name=\"chips\" tint=1> aus",
            ["Spend 100M <sprite name=\"chips\" tint=1> in total"] = "Gib insgesamt 100M <sprite name=\"chips\" tint=1> aus",
            ["Complete 10 runs while Auto Solver is turned off"] = "Beende 10 Runs bei ausgeschaltetem Auto-Solver",
            ["Complete 1000 runs with a solver"] = "Beende 1000 Runs mit einem Solver",
            ["Move a total of 10000 times"] = "Ziehe insgesamt 10000 Mal",
            ["Move a total of 100K times"] = "Ziehe insgesamt 100K Mal",
            ["Move a total of 1M times"] = "Ziehe insgesamt 1M Mal",
            ["Merge a total of 10000 times"] = "Merge insgesamt 10000 Mal",
            ["Merge a total of 100K times"] = "Merge insgesamt 100K Mal",
            ["Merge a total of 1M times"] = "Merge insgesamt 1M Mal",
            ["Reach high 1024"] = "Erreiche Block 1024",
            ["Reach high 8192"] = "Erreiche Block 8192",
            ["Reach high 65536"] = "Erreiche Block 65536",
            ["Unlock Agents"] = "Agenten freischalten",
            ["Equip 3 Agents at once"] = "Rüste 3 Agenten gleichzeitig aus",
            ["Unlock Modifiers"] = "Modifikatoren freischalten",
            ["Use all solvers at least once"] = "Nutze jeden Solver mindestens einmal",
            ["Use all Agents at least once"] = "Nutze jeden Agenten mindestens einmal",
            ["Let Unstable Stack save your run a total of 100 times"] = "Lass Unstable Stack deinen Run insgesamt 100 Mal retten",
            ["Merge with a Joker for a total of 100 times"] = "Merge insgesamt 100 Mal mit einem Joker",
            ["Consume a total of 5000 <sprite name=\"token\" tint=1>"] = "Verbrauche insgesamt 5000 <sprite name=\"token\" tint=1>",
            ["Hold at least 10000 <sprite name=\"token\" tint=1> at once"] = "Halte gleichzeitig mindestens 10000 <sprite name=\"token\" tint=1>",
            ["Prestige reset for the first time"] = "Mache zum ersten Mal einen Prestige-Reset",
            ["Prestige reset for a total of 5 times"] = "Mache insgesamt 5 Prestige-Resets",
            ["Prestige reset for a total of 15 times"] = "Mache insgesamt 15 Prestige-Resets",
            ["Run PPO once in Normal Mode"] = "Führe PPO einmal im Normalmodus aus",
            ["Reach 100K PPO frames"] = "Erreiche 100K PPO-Frames",
            ["Earn 1000 <sprite name=\"insight\" tint=1> in total"] = "Verdiene insgesamt 1000 <sprite name=\"insight\" tint=1>",
            ["Earn 10K <sprite name=\"insight\" tint=1> in total"] = "Verdiene insgesamt 10K <sprite name=\"insight\" tint=1>",
            ["Earn 100K <sprite name=\"insight\" tint=1> in total"] = "Verdiene insgesamt 100K <sprite name=\"insight\" tint=1>",
            ["Buy all the researches"] = "Kaufe alle Forschungen",
            ["Have at least 1 unit in each Server Rack"] = "Besitze mindestens 1 Einheit in jedem Server-Rack",
            ["Go above 1000 GF/s total compute"] = "Überschreite 1000 GF/s Gesamtrechenleistung",
            ["Reach 1M PPO Training frames"] = "Erreiche 1M PPO-Trainings-Frames",
            ["Let It Cook"] = "Lass es köcheln",
            ["Budget Intelligence"] = "Sparsame Intelligenz",
            ["Surgical Move"] = "Chirurgischer Zug",
            ["Perfectly Reasonable"] = "Völlig vernünftig",
            ["Full Autopilot"] = "Voller Autopilot",
            ["Bad Financial Advice"] = "Schlechter Finanztipp",
            ["Still Here"] = "Immer noch hier",
            ["One More Run"] = "Noch ein Run",
            ["See You Again"] = "Bis bald",
            ["Perfectly Balanced"] = "Perfekt ausbalanciert",
            ["Second Thoughts"] = "Zweifel",
            ["No Defaults Given"] = "Keine Standards mehr",
            ["Let it cook"] = "Lass es köcheln",
            ["Old intelligence"] = "Alte Intelligenz",
            ["Remove something big"] = "Entferne etwas Großes",
            ["A very specific reserve"] = "Eine sehr genaue Reserve",
            ["Everything buys itself"] = "Alles kauft sich selbst",
            ["Questionable first purchase"] = "Fragwürdiger erster Kauf",
            ["Stay a while"] = "Bleib eine Weile",
            ["Just one more run"] = "Nur noch ein Run",
            ["Come back often"] = "Komm oft wieder",
            ["Almost perfectly split"] = "Fast perfekt aufgeteilt",
            ["Second thoughts"] = "Plötzliche Zweifel",
            ["No defaults left"] = "Keine Standards übrig",
            ["Earn offline rewards after being away for 8+ hours."] = "Erhalte Offline-Belohnungen nach 8+ Stunden Abwesenheit.",
            ["Complete a run with RAND after unlocking PPO."] = "Beende einen Run mit RAND, nachdem du PPO freigeschaltet hast.",
            ["Use Miner's Pickaxe on a block worth 1024 or higher."] = "Benutze die Miner's Pickaxe auf einem Block von 1024 oder höher.",
            ["Hold exactly 2048 <sprite name=\"token\" tint=1> after a run ends."] = "Halte am Ende eines Runs genau 2048 <sprite name=\"token\" tint=1>.",
            ["Have all Auto Buy buttons enabled simultaneously."] = "Aktiviere alle Auto-Buy-Schalter gleichzeitig.",
            ["Buy the Joker as your first Modifier in a prestige."] = "Kaufe den Joker als ersten Modifikator in einem Prestige.",
            ["Have 24 hours of lifetime playtime."] = "Erreiche 24 Stunden Gesamtspielzeit.",
            ["Leave the game open for 2 hours straight."] = "Lass das Spiel 2 Stunden am Stück offen.",
            ["Exit the game 10 times."] = "Verlasse das Spiel 10 Mal.",
            ["Split Compute Allocation exactly 33-33-33-1."] = "Teile die Compute-Zuteilung genau 33-33-33-1 auf.",
            ["Deselect a solver immediately after selecting it."] = "Wähle einen Solver direkt nach dem Auswählen wieder ab.",
            ["Modify all parameters of PPO in Tuning."] = "Ändere alle Parameter von PPO in der Justierung.",
            ["Unlocks Auto Buy for Algos, Upgrades, Agents and Mods"] = "Schaltet Auto-Buy für Algos, Upgrades, Agenten und Mods frei",
            ["Unlocks Datacenter"] = "Schaltet das Rechenzentrum frei",
            ["Merge streak upgrade at max level is 5% stronger"] = "Das Merge-Serie-Upgrade ist auf Maximalstufe 5% stärker",
            ["PPO learns from your Manual runs"] = "PPO lernt aus deinen manuellen Runs",
            ["Higher frequency upgrade at max level is 2% stronger"] = "Das Höhere-Frequenz-Upgrade ist auf Maximalstufe 2% stärker",
            ["Unlocks Byte numeral for blocks"] = "Schaltet die Byte-Zahlendarstellung für Blöcke frei",
            ["Unlocks Power numeral for blocks"] = "Schaltet die Potenz-Zahlendarstellung für Blöcke frei",
            ["Unlocks Roman numeral for blocks"] = "Schaltet die römische Zahlendarstellung für Blöcke frei",
            ["Unlocks Hexadecimal numeral for blocks"] = "Schaltet die hexadezimale Zahlendarstellung für Blöcke frei",
            ["Unlocks Scientific numeral for blocks"] = "Schaltet die wissenschaftliche Zahlendarstellung für Blöcke frei",
            ["Complete its goal to unlock this numeral"] = "Erfülle das zugehörige Ziel, um diese Darstellung freizuschalten",
            ["Consecutive merges multiply move income."] = "Aufeinanderfolgende Merges vervielfachen das Zug-Einkommen.",
            ["Converts part of the run's score into <sprite name=\"chips\" tint=1>."] = "Wandelt einen Teil der Run-Punkte in <sprite name=\"chips\" tint=1> um.",
            ["Held <sprite name=\"token\" tint=1> pay <sprite name=\"chips\" tint=1> times the √ of the hoard."] = "Gehaltene <sprite name=\"token\" tint=1> zahlen <sprite name=\"chips\" tint=1> mal der √ des Vorrats.",
            ["The currency for Auto restart. Price rises the more <sprite name=\"token\" tint=1> you hold."] = "Die Währung für den Auto-Neustart. Der Preis steigt, je mehr <sprite name=\"token\" tint=1> du hältst.",
            ["Standard"] = "Standard",
            ["Byte"] = "Byte",
            ["Hexadecimal"] = "Hexadezimal",
            ["Power"] = "Potenz",
            ["Roman"] = "Römisch",
            ["Scientific"] = "Wissenschaftlich",
            ["Audio"] = "Audio",
            ["Accessibility"] = "Barrierefreiheit",
            ["Application"] = "Anwendung",
            ["Display"] = "Anzeige",
            ["Manage save files"] = "Spielstände verwalten",
            ["Block numerals visual"] = "Blockzahlen-Darstellung",
            ["How to play"] = "Spielanleitung",
            ["Highest"] = "Höchster",
            ["Highest median"] = "Höchster Median",
            ["Runs"] = "Runs",
            ["Earned"] = "Verdient",
            ["Resets"] = "Resets",
            ["Playtime"] = "Spielzeit",
            ["Solvers"] = "Solver",
            ["Recent Score Trend"] = "Letzter Punkte-Trend",
            ["Recent Runs"] = "Letzte Runs",
            ["Lifetime Stats"] = "Gesamtstatistiken",
            ["Goals"] = "Ziele",
            ["Prestige Summary"] = "Prestige-Übersicht",
            ["Average time in runs"] = "Durchschnittliche Run-Zeit",
            ["Total frame"] = "Frames gesamt",
            ["Average frame / Prestige"] = "Ø Frames / Prestige",
            ["Total runs"] = "Runs gesamt",
            ["Total moves"] = "Züge gesamt",
            ["Total merges"] = "Merges gesamt",
            ["PPO knowledge"] = "PPO-Wissen",
            ["Total playtime"] = "Gesamtspielzeit",
            ["Merge Broker"] = "Merge-Broker",
            ["Highwater Analyst"] = "Höchststand-Analyst",
            ["Score Auditor"] = "Punkte-Prüfer",
            ["Overclocker"] = "Übertakter",
            ["Quartermaster"] = "Quartiermeister",
            ["Restart Sponsor"] = "Neustart-Sponsor",
            ["Token Prospector"] = "Token-Schürfer",
            ["Move Dividend"] = "Zug-Dividende",
            ["Velocity Trader"] = "Tempo-Händler",
            ["Unstable Stack"] = "Instabiler Stack",
            ["Catalyst Stack"] = "Katalysator-Stack",
            ["Mirror Stack"] = "Spiegel-Stack",
            ["Joker"] = "Joker",
            ["Miner's Pickaxe"] = "Bergmannsspitzhacke",
            ["Queue Scrubber"] = "Warteschlangenreiniger",
            ["Neural Accelerator"] = "Neural-Beschleuniger",
            ["Boosts merge income."] = "Steigert das Merge-Einkommen.",
            ["Rewards new highs."] = "Belohnt neue Höchstblöcke.",
            ["Turns score into <sprite name=\"chips\" tint=1>."] = "Wandelt Punkte in <sprite name=\"chips\" tint=1> um.",
            ["Runs the solver faster."] = "Lässt den Solver schneller laufen.",
            ["Improves baseline income."] = "Verbessert das Basis-Einkommen.",
            ["Keeps restarts funded."] = "Finanziert die Neustarts.",
            ["Turns merge volume into restart fuel."] = "Wandelt Merge-Volumen in Neustart-Treibstoff um.",
            ["Rewards long, stable runs."] = "Belohnt lange, stabile Runs.",
            ["Rewards fast solvers."] = "Belohnt schnelle Solver.",
            ["Deletes bottom blocks when a full stack would fail."] = "Löscht unterste Blöcke, wenn ein voller Stack scheitern würde.",
            ["Converts merges into more <sprite name=\"chips\" tint=1>."] = "Wandelt Merges in mehr <sprite name=\"chips\" tint=1> um.",
            ["Lets stack ends interact."] = "Lässt die Stack-Enden interagieren.",
            ["Adds wild blocks to the queue."] = "Fügt der Queue Wild-Blöcke hinzu.",
            ["Lets solvers remove blocks from the board."] = "Lässt Solver Blöcke vom Brett entfernen.",
            ["Lets solvers delete bad upcoming blocks."] = "Lässt Solver schlechte kommende Blöcke löschen.",
            ["Speeds up expensive solvers."] = "Beschleunigt rechenintensive Solver.",
            ["Select an algorithm to inspect it. Locked algorithms hide detailed behavior until unlocked."] = "Wähle einen Algorithmus, um ihn zu untersuchen. Gesperrte Algorithmen verbergen ihr Detailverhalten bis zur Freischaltung.",
            ["Buy automation, unlock new layers, then push into riskier systems when the run history proves you are ready."] = "Kaufe Automatisierung, schalte neue Ebenen frei und wage dich in riskantere Systeme, wenn der Run-Verlauf zeigt, dass du bereit bist.",
            ["Equipped Agents give various bonuses to progress faster."] = "Ausgerüstete Agenten geben verschiedene Boni für schnelleren Fortschritt.",
            ["Late-game rule modules. They raise the ceiling, create rescue tools, and make solver choice matter more than raw price."] = "Late-Game-Regelmodule. Sie heben die Obergrenze, schaffen Rettungswerkzeuge und machen die Solver-Wahl wichtiger als den reinen Preis.",
            ["They expand the game rules, allowing for further production. Each solver is effective in different ways."] = "Sie erweitern die Spielregeln und ermöglichen mehr Produktion. Jeder Solver ist auf andere Weise effektiv.",
            ["Rule-changing modules that apply to new runs and amplify the differences between solvers."] = "Regeländernde Module, die für neue Runs gelten und die Unterschiede zwischen Solvern verstärken.",
            ["Modifiers apply to new runs and amplify solver differences."] = "Modifikatoren gelten für neue Runs und verstärken die Solver-Unterschiede.",
            ["You can track how many tasks you've completed. As you progress, you'll automatically unlock them."] = "Du kannst verfolgen, wie viele Aufgaben du erledigt hast. Mit dem Fortschritt schaltest du sie automatisch frei.",
            ["Permanent late-game research. Prestige turns PPO Normal-mode performance into Insight, then the tree makes every future reset faster and deeper."] = "Dauerhafte Late-Game-Forschung. Prestige wandelt PPO-Normalmodus-Leistung in Insight um, dann macht der Baum jeden künftigen Reset schneller und tiefer.",
            ["Permanent late-game research. The tree makes every future reset faster and deeper."] = "Dauerhafte Late-Game-Forschung. Der Baum macht jeden künftigen Reset schneller und tiefer.",
            ["Research locked. Finish PPO Training, then run PPO in Normal mode."] = "Forschung gesperrt. Beende das PPO-Training und führe PPO dann im Normalmodus aus.",
            ["Track your recent runs and the performance of your used solvers."] = "Verfolge deine letzten Runs und die Leistung deiner genutzten Solver.",
            ["Description"] = "Beschreibung",
            ["<b>Manual controls</b>"] = "<b>Manuelle Steuerung</b>",
            ["Free baseline solver."] = "Kostenloser Basis-Solver.",
            ["Randomly chooses any valid stack. Weak, chaotic, but fast."] = "Wählt zufällig einen gültigen Stack. Schwach, chaotisch, aber schnell.",
            ["Looks for direct merges."] = "Sucht nach direkten Merges.",
            ["Prioritizes immediate merges and cascades before anything else."] = "Priorisiert sofortige Merges und Kaskaden vor allem anderen.",
            ["Keeps stacks even."] = "Hält die Stacks gleichmäßig.",
            ["Avoids tall dangerous stacks and spreads risk across the board."] = "Vermeidet hohe, gefährliche Stacks und verteilt das Risiko über das Brett.",
            ["Scores every legal move."] = "Bewertet jeden legalen Zug.",
            ["Uses handcrafted heuristics: merge value, danger, future queue fit, and free space."] = "Nutzt handgefertigte Heuristiken: Merge-Wert, Gefahr, künftige Queue-Passung und freien Platz.",
            ["Plans one move deeper."] = "Plant einen Zug tiefer.",
            ["Tests each move, then estimates the best follow-up move before deciding."] = "Testet jeden Zug und schätzt vor der Entscheidung den besten Folgezug.",
            ["Runs simulations."] = "Führt Simulationen aus.",
            ["Rolls out multiple futures, judging each by the surviving board and the peak tier it reaches."] = "Spielt mehrere Zukünfte aus und bewertet jede nach dem überlebenden Brett und der erreichten Höchststufe.",
            ["Reads the visible queue."] = "Liest die sichtbare Queue.",
            ["Queue planner. Searches lines through up to 3 visible next blocks before choosing."] = "Queue-Planer. Sucht vor der Wahl Linien durch bis zu 3 sichtbare nächste Blöcke.",
            ["Queue planner. Searches lines through the visible next blocks. Planning depth (3–5) can be tuned for patience vs practicality."] = "Queue-Planer. Sucht Linien durch die sichtbaren nächsten Blöcke. Die Planungstiefe (3–5) ist zwischen Geduld und Praxis justierbar.",
            ["Uses the extended queue."] = "Nutzt die erweiterte Queue.",
            ["Deep queue planner. Searches lines through up to 5 visible next blocks. Stronger once next preview upgrades are unlocked."] = "Tiefer Queue-Planer. Sucht Linien durch bis zu 5 sichtbare nächste Blöcke. Stärker, sobald Next-Vorschau-Upgrades freigeschaltet sind.",
            ["Smarter Monte Carlo rollouts."] = "Klügere Monte-Carlo-Rollouts.",
            ["Enhanced Monte Carlo. Each rollout uses short queue planning and an anti-stall board score."] = "Verbessertes Monte Carlo. Jeder Rollout nutzt kurze Queue-Planung und eine Anti-Stall-Brettbewertung.",
            ["Builds a search tree."] = "Baut einen Suchbaum.",
            ["Monte Carlo Tree Search. Balances exploring new lines with exploiting lines that already score well."] = "Monte Carlo Tree Search. Balanciert das Erkunden neuer Linien mit dem Ausnutzen bereits gut bewerteter Linien.",
            ["Avoids dead boards."] = "Vermeidet tote Bretter.",
            ["Anti-stall solver. Heavily protects legal moves, semi-empty stacks, and escape routes over greedy merges."] = "Anti-Stall-Solver. Schützt legale Züge, halbleere Stacks und Fluchtwege stark gegenüber gierigen Merges.",
            ["Sets up chain merges."] = "Bereitet Ketten-Merges vor.",
            ["Combo-focused solver. Reads the queue and rewards positions that can cascade over the next 2-3 turns."] = "Combo-fokussierter Solver. Liest die Queue und belohnt Positionen, die über die nächsten 2-3 Züge kaskadieren können.",
            ["Endgame learner. Requires every Modifier to be fully purchased."] = "Endgame-Lerner. Erfordert, dass jeder Modifikator vollständig gekauft ist.",
            ["Proximal Policy Optimization is a lightweight actor-critic neural network that learns its policy from run trajectories, clipped policy updates, value estimates, and entropy-driven exploration."] = "Proximal Policy Optimization ist ein leichtgewichtiges Actor-Critic-Netz, das seine Policy aus Run-Trajektorien, geclippten Policy-Updates, Wertschätzungen und entropiegetriebener Erkundung lernt.",
            ["+75% <sprite name=\"chips\" tint=1> from merge rewards."] = "+75% <sprite name=\"chips\" tint=1> aus Merge-Belohnungen.",
            ["+200% <sprite name=\"chips\" tint=1> from new highest-block rewards."] = "+200% <sprite name=\"chips\" tint=1> aus neuen Höchstblock-Belohnungen.",
            ["+200% <sprite name=\"chips\" tint=1> from end-of-run score bonus."] = "+200% <sprite name=\"chips\" tint=1> aus dem Run-End-Punktebonus.",
            ["Solver move interval is 25% shorter."] = "Das Solver-Zugintervall ist 25% kürzer.",
            ["+10 <sprite name=\"chips\" tint=1> on every successful placement."] = "+10 <sprite name=\"chips\" tint=1> bei jeder erfolgreichen Platzierung.",
            ["Auto Restart consumes no tokens while this agent is active."] = "Der Auto-Neustart verbraucht keine Token, solange dieser Agent aktiv ist.",
            ["+1 token for every 8 merges while active."] = "+1 Token pro 8 Merges, solange aktiv.",
            ["End-of-run <sprite name=\"chips\" tint=1> gain a bonus from total moves completed."] = "Das Run-End-<sprite name=\"chips\" tint=1> erhält einen Bonus aus der Gesamtzahl der Züge.",
            ["End-of-run <sprite name=\"chips\" tint=1> gain a throughput bonus from moves per second."] = "Das Run-End-<sprite name=\"chips\" tint=1> erhält einen Durchsatzbonus aus Zügen pro Sekunde.",
            ["Each level gives one rescue per run. If a full stack receives a non-merge block, its bottom block is removed without reducing score."] = "Jede Stufe gibt eine Rettung pro Run. Erhält ein voller Stack einen Nicht-Merge-Block, wird sein unterster Block ohne Punktverlust entfernt.",
            ["Merge rewards are permanently doubled on every run after purchase."] = "Merge-Belohnungen werden nach dem Kauf in jedem Run dauerhaft verdoppelt.",
            ["Unlocks a special merge. If the top and bottom block of a stack match, they merge through the stack."] = "Schaltet einen Spezial-Merge frei. Passen der oberste und unterste Block eines Stacks zusammen, mergen sie durch den Stack.",
            ["Unlocks occasional Joker blocks. A Joker placed onto any block merges with it."] = "Schaltet gelegentliche Joker-Blöcke frei. Ein auf einen Block gelegter Joker mergt mit ihm.",
            ["Each level gives one pickaxe use per run. The solver may delete any block in any stack."] = "Jede Stufe gibt eine Pickaxe-Nutzung pro Run. Der Solver darf jeden Block in jedem Stack löschen.",
            ["Each level gives one queue skip per run. The current next block is removed and the following block moves forward."] = "Jede Stufe gibt eine Queue-Löschung pro Run. Der aktuelle nächste Block wird entfernt und der folgende rückt vor.",
            ["MOCA, MOCA+, and MCTS run permanently about twice as fast. Negative speed tuning on those solvers is also twice as effective."] = "MOCA, MOCA+ und MCTS laufen dauerhaft etwa doppelt so schnell. Negative Tempo-Justierung ist bei diesen Solvern ebenfalls doppelt so wirksam.",
            ["MOCA runs permanently about twice as fast. Negative speed tuning on it is also twice as effective."] = "MOCA läuft dauerhaft etwa doppelt so schnell. Negative Tempo-Justierung ist ebenfalls doppelt so wirksam.",
            ["+35% <sprite name=\"insight\" tint=1> from every future prestige per level."] = "+35% <sprite name=\"insight\" tint=1> aus jedem künftigen Prestige pro Stufe.",
            ["Start after each prestige reset with <sprite name=\"chips\" tint=1> already banked. This allows making purchases right at the beginning of the game."] = "Beginne nach jedem Prestige-Reset mit bereits vorhandenen <sprite name=\"chips\" tint=1>. So kannst du gleich zu Spielbeginn kaufen.",
            ["Permanently remembers automation unlocks per level after prestige: Auto Solve, Auto Restart <sprite name=\"token\" tint=1>, then Solver Tuning."] = "Merkt sich nach dem Prestige pro Stufe dauerhaft eine Automatisierung: Auto-Lösen, Auto-Neustart <sprite name=\"token\" tint=1>, dann Solver-Justierung.",
            ["Start future prestiges with early algorithms already known: BAL, HEUR, COMBO, then LOOK."] = "Beginne künftige Prestiges mit bereits bekannten frühen Algorithmen: BAL, HEUR, COMBO, dann LOOK.",
            ["+18% <sprite name=\"chips\" tint=1> from every reward per level. It stacks with Chip Yield and stage multipliers."] = "+18% <sprite name=\"chips\" tint=1> aus jeder Belohnung pro Stufe. Stapelt sich mit Chip-Ertrag und Phasen-Multiplikatoren.",
            ["+50% <sprite name=\"chips\" tint=1> from every reward per level. It stacks with Chip Yield and stage multipliers, making every future playthrough visibly faster."] = "+50% <sprite name=\"chips\" tint=1> aus jeder Belohnung pro Stufe. Stapelt sich mit Chip-Ertrag und Phasen-Multiplikatoren und macht jeden künftigen Durchlauf sichtbar schneller.",
            ["PPO still resets every prestige, but each level lowers the trained frame requirement for Normal Mode by 8%."] = "PPO wird weiterhin bei jedem Prestige zurückgesetzt, aber jede Stufe senkt die trainierte Frame-Anforderung für den Normalmodus um 8%.",
            ["Prestige banks 50000 PPO training frames per level. The next playthrough's PPO Training starts from that saved progress, with the knowledge already learned (instead of zero)."] = "Prestige speichert 50000 PPO-Trainings-Frames pro Stufe. Das PPO-Training des nächsten Durchlaufs startet von diesem Fortschritt mit dem bereits gelernten Wissen (statt von Null).",
            ["Each level lowers the cycle frame requirement for PPO Normal Mode by 8%. At level 5, PPO Curriculum upgrades can be bought before PPO is unlocked and can fully automate the remaining cycle requirement."] = "Jede Stufe senkt die Zyklus-Frame-Anforderung für den PPO-Normalmodus um 8%. Auf Stufe 5 können PPO-Curriculum-Upgrades vor der Freischaltung von PPO gekauft werden und die restliche Zyklus-Anforderung voll automatisieren.",
            ["Prestige banks 50000 PPO cycle frames per level. The next playthrough's PPO Training starts from that saved cycle progress, while Datacenter training remains as permanent PPO knowledge."] = "Prestige speichert 50000 PPO-Zyklus-Frames pro Stufe. Das PPO-Training des nächsten Durchlaufs startet von diesem Zyklus-Fortschritt, während das Rechenzentrum-Training als dauerhaftes PPO-Wissen bleibt.",
            ["Prestige banks 40000 PPO cycle frames per level. The next playthrough's PPO Training starts from that saved cycle progress, while Datacenter training remains as permanent PPO knowledge."] = "Prestige speichert 40000 PPO-Zyklus-Frames pro Stufe. Das PPO-Training des nächsten Durchlaufs startet von diesem Zyklus-Fortschritt, während das Rechenzentrum-Training als dauerhaftes PPO-Wissen bleibt.",
            ["Raises PPO's reward signal for creating new highest blocks. This pushes the learner toward bigger blocks instead of only safer runs."] = "Erhöht das Belohnungssignal von PPO für neue Höchstblöcke. Das lenkt den Lerner zu größeren Blöcken statt nur zu sichereren Runs.",
            ["Improves PPO's survival shaping and danger penalties, making high-focus policies less likely to crash early."] = "Verbessert die Überlebens-Formung und Gefahrenstrafen von PPO, sodass high-fokussierte Policies seltener früh abstürzen.",
            ["+50% <sprite name=\"insight\" tint=1> from PPO Normal Mode performance per level. This is the late neural payoff node."] = "+50% <sprite name=\"insight\" tint=1> aus der PPO-Normalmodus-Leistung pro Stufe. Dies ist der späte neuronale Ertragsknoten.",
            ["Boosts <sprite name=\"insight\" tint=1> earned directly from PPO Normal Mode runs. Training mode never feeds this, and long cycles softcap so prestige stays valuable."] = "Steigert das direkt aus PPO-Normalmodus-Runs verdiente <sprite name=\"insight\" tint=1>. Der Trainingsmodus speist dies nie, und lange Zyklen haben einen Softcap, damit Prestige wertvoll bleibt.",
            ["Offline Engine\", \"While the game is closed, <sprite name=\"chips\" tint=1> and <sprite name=\"insight\" tint=1> continue at a reduced rate based on your current prestige strength."] = "Während das Spiel geschlossen ist, laufen <sprite name=\"chips\" tint=1> und <sprite name=\"insight\" tint=1> mit reduzierter Rate weiter, basierend auf deiner aktuellen Prestige-Stärke.",
            ["Extends how many closed-game hours can be converted into offline <sprite name=\"chips\" tint=1> and <sprite name=\"insight\" tint=1>."] = "Verlängert, wie viele geschlossene Spielstunden in Offline-<sprite name=\"chips\" tint=1> und <sprite name=\"insight\" tint=1> umgewandelt werden können.",
            ["Every hired Agent's bonus effect is 40% stronger per level. Agents become a core engine of faster replays."] = "Der Bonuseffekt jedes angeheuerten Agenten ist pro Stufe 40% stärker. Agenten werden zum Kernmotor schnellerer Durchläufe.",
            ["Upgrades, Agents and Modifiers cost 5% less per level, and the Modifiers requirement needs 15% fewer runs & merges per level. At level 5, Datacenter costs are 20% cheaper."] = "Upgrades, Agenten und Modifikatoren kosten pro Stufe 5% weniger, und die Modifikator-Anforderung braucht pro Stufe 15% weniger Runs & Merges. Auf Stufe 5 sind Rechenzentrum-Kosten 20% günstiger.",
            ["Shortens the result-evaluation pause after every PPO Training run by 15% per level, so Training mode gets through its runs much faster."] = "Verkürzt die Auswertungspause nach jedem PPO-Trainings-Run pro Stufe um 15%, sodass der Trainingsmodus seine Runs viel schneller durchläuft.",
            ["Unlock PPO to begin the prestige layer."] = "Schalte PPO frei, um die Prestige-Ebene zu beginnen.",
            ["Prestige for"] = "Prestige-Belohnung:",
            ["You can keep playing PPO in Playing Mode to increase <sprite name=\"insight\" tint=1>."] = "Du kannst PPO weiter im Spielmodus spielen, um <sprite name=\"insight\" tint=1> zu erhöhen.",
            ["Current effect"] = "Aktuelle Wirkung",
            ["Game"] = "Spiel",
            ["Gameplay"] = "Gameplay",
            ["Selected"] = "Ausgewählt",
            ["Deselected"] = "Abgewählt",
            ["Needs modifiers"] = "Braucht Modifikatoren",
            ["Needs all\nModifiers"] = "Braucht alle\nModifikatoren",
            ["Unlock\nUpgrades"] = "In Upgrades\nfreischalten",
            ["Unlock this algorithm to reveal details."] = "Schalte diesen Algorithmus frei, um Details zu sehen.",
            ["Agents\nLocked"] = "Agenten\nGesperrt",
            ["Unlock in\nUpgrades"] = "In Upgrades\nfreischalten",
            ["Bonus slot\nNeeds upgrade"] = "Bonus-Slot\nBraucht Upgrade",
            ["Agents Locked"] = "Agenten gesperrt",
            ["Unlock the Agents menu in Upgrades."] = "Schalte das Agenten-Menü in den Upgrades frei.",
            ["Equipped"] = "Ausgerüstet",
            ["No free slot"] = "Kein freier Slot",
            ["Unequip someone first"] = "Lege zuerst jemanden ab",
            ["Needs upgrade"] = "Braucht Upgrade",
            ["Empty"] = "Leer",
            ["Modifier Lab Locked"] = "Modifikator-Lab gesperrt",
            ["Reach the stage goal in Upgrades to unlock board modifiers. They make runs richer, riskier, and much harder to play optimally by hand."] = "Erreiche das Phasenziel in den Upgrades, um Brett-Modifikatoren freizuschalten. Sie machen Runs reicher, riskanter und von Hand viel schwerer optimal zu spielen.",
            ["Not active"] = "Nicht aktiv",
            ["Activate"] = "Aktivieren",
            ["Upgrade"] = "Upgrade",
            ["Ready: every Modifier is fully purchased."] = "Bereit: jeder Modifikator ist vollständig gekauft.",
            ["PPO model is not initialized yet."] = "Das PPO-Modell ist noch nicht initialisiert.",
            ["Prestige once to open Research."] = "Mache einmal Prestige, um die Forschung zu öffnen.",
            ["Research maxed."] = "Forschung maximiert.",
            ["Not enough Insight."] = "Nicht genug Insight.",
            ["Not enough <sprite name=\"insight\" tint=1>."] = "Nicht genug <sprite name=\"insight\" tint=1>.",
            ["Requires Seed Capital L1."] = "Erfordert Startkapital L1.",
            ["Requires Automation Memory L1."] = "Erfordert Automatisierungsspeicher L1.",
            ["Requires Algorithm Archive L1."] = "Erfordert Algorithmus-Archiv L1.",
            ["Requires Agent Synergy L1."] = "Erfordert Agenten-Synergie L1.",
            ["Requires Bulk Discount L1."] = "Erfordert Mengenrabatt L1.",
            ["Requires PPO Bootcamp L1."] = "Erfordert PPO-Bootcamp L1.",
            ["Requires Evaluation Efficiency L1."] = "Erfordert Auswertungs-Effizienz L1.",
            ["Requires PPO Memory L1."] = "Erfordert PPO-Speicher L1.",
            ["Requires High Focus L1."] = "Erfordert Hoher Fokus L1.",
            ["Requires Stability Model L1."] = "Erfordert Stabilitätsmodell L1.",
            ["Requires Insight Amplifier L1."] = "Erfordert Insight-Verstärker L1.",
            ["Requires Passive Insight L1."] = "Erfordert Passiver Insight L1.",
            ["Requires Offline Engine L1."] = "Erfordert Offline-Engine L1.",
            ["Ready to buy."] = "Kaufbereit.",
            ["Not enough chips"] = "Nicht genug Chips",
            ["PPO requires every Modifier maxed"] = "PPO erfordert jeden Modifikator auf Maximum",
            ["Unlock Agents first"] = "Schalte zuerst die Agenten frei",
            ["Modifier Lab requirements not met"] = "Modifikator-Lab-Anforderungen nicht erfüllt",
            ["Run PPO in Normal mode first"] = "Führe PPO zuerst im Normalmodus aus",
            ["Agents menu unlocked"] = "Agenten-Menü freigeschaltet",
            ["Agent unavailable"] = "Agent nicht verfügbar",
            ["No free agent slot"] = "Kein freier Agenten-Slot",
            ["Speed level"] = "Tempo-Stufe",
            ["Risk level"] = "Risiko-Stufe",
            ["Chip yield level"] = "Chip-Ertrag-Stufe",
            ["Next preview"] = "Next-Vorschau",
            ["Scaling frequency upgrade unavailable"] = "Skalierungsfrequenz-Upgrade nicht verfügbar",
            ["Profitable ending upgrade unavailable"] = "Profitables-Ende-Upgrade nicht verfügbar",
            ["Modifier upgrade unavailable"] = "Modifikator-Upgrade nicht verfügbar",
            ["<b>Auto Buy</b>"] = "<b>Auto-Kauf</b>",
            ["Auto Buy"] = "Auto-Kauf",
            ["Enabled"] = "An",
            ["Disabled"] = "Aus",
            ["FPS --"] = "FPS --",
            ["Policy loss"] = "Policy-Verlust",
            ["Policy loss:"] = "Policy-Verlust:",
            ["Value loss"] = "Value-Verlust",
            ["Value loss:"] = "Value-Verlust:",
            ["Entropy"] = "Entropie",
            ["Entropy:"] = "Entropie:",
            ["Updates"] = "Updates",
            ["Updates:"] = "Updates:",
            ["PPO is trained, prestige reset unlocked."] = "PPO ist trainiert, Prestige-Reset freigeschaltet.",
            ["Gain:"] = "Gewinn:",
            ["You made"] = "Du hast",
            ["while you were offline."] = "verdient, während du offline warst.",
            ["Offline reward time:"] = "Offline-Belohnungszeit:",
            ["You have to finish PPO Training to unlock prestige."] = "Du musst das PPO-Training beenden, um Prestige freizuschalten.",
            ["In case of a Prestige reset, the game will restart. All <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, upgrades, Agents, and Modifiers will be lost.\n\n" +
                "However, existing <sprite name=\"insight\" tint=1> and purchased research will remain, which will make further resets progressively more valuable.\n\n" +
                "<b>It is recommended to use PPO in Normal Mode before resetting to gain <sprite name=\"insight\" tint=1> multiplier.</b>"] =
            "Bei einem Prestige-Reset startet das Spiel neu. Alle <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, Upgrades, Agenten und Modifikatoren gehen verloren.\n\n" +
            "Vorhandene <sprite name=\"insight\" tint=1> und gekaufte Forschung bleiben jedoch erhalten und machen weitere Resets zunehmend wertvoller.\n\n" +
            "<b>Es wird empfohlen, PPO vor dem Reset im Normalmodus zu nutzen, um den <sprite name=\"insight\" tint=1>-Multiplikator zu erhöhen.</b>",
            ["Reset for"] = "Reset-Belohnung:",
            ["Datacenter"] = "Rechenzentrum",
            ["Compute Allocation"] = "Rechen-Zuteilung",
            ["Server Racks"] = "Server-Racks",
            ["Facility Upgrades"] = "Anlagen-Upgrades",
            ["CPU Rack"] = "CPU-Rack",
            ["GPU Rack"] = "GPU-Rack",
            ["TPU Pod"] = "TPU-Pod",
            ["Neural Fabric"] = "Neural Fabric",
            ["Power Grid"] = "Stromnetz",
            ["Cooling Loop"] = "Kühlkreislauf",
            ["Fabric Interconnect"] = "Fabric-Interconnect",
            ["Commodity silicon. Cheap, dependable, slow."] = "Standard-Silizium. Billig, zuverlässig, langsam.",
            ["Parallel throughput for tensor math."] = "Paralleler Durchsatz für Tensor-Mathematik.",
            ["Tensor pods. Systolic arrays with obscene throughput."] = "Tensor-Pods. Systolische Arrays mit obszönem Durchsatz.",
            ["Experimental wafer-scale mesh. Draws its own weather."] = "Experimentelles Wafer-Scale-Mesh. Erzeugt sein eigenes Wetter.",
            ["Dedicated feeders and battery buffer."] = "Dedizierte Einspeisungen und Batteriepuffer.",
            ["Immersion + rear-door heat exchangers."] = "Immersions- und Rücktür-Wärmetauscher.",
            ["Low-latency mesh between pods."] = "Latenzarmes Mesh zwischen den Pods.",
            ["Total compute"] = "Gesamt-Rechenleistung",
            ["allocated"] = "zugeteilt",
            ["units"] = "Einheiten",
            ["unit"] = "Einheit",
            ["total"] = "gesamt",
            ["Training Cluster"] = "Trainings-Cluster",
            ["Analysis Node"] = "Analyse-Knoten",
            ["Market Bots"] = "Markt-Bots",
            ["Passive PPO frame. Shortens the prestige cycle."] = "Passive PPO-Frames. Verkürzt den Prestige-Zyklus.",
            ["Passively generates <sprite name=\"insight\" tint=1> (softcapped)."] = "Erzeugt passiv <sprite name=\"insight\" tint=1> (mit Softcap).",
            ["Producing <sprite name=\"chips\" tint=1> gets an income multiplier."] = "Die <sprite name=\"chips\" tint=1>-Produktion erhält einen Einkommens-Multiplikator.",
            ["Requires every Modifier maxed"] = "Erfordert jeden Modifikator auf Maximum",
            ["Agent bonuses"] = "Agenten-Boni",
            ["Shop prices"] = "Shop-Preise",
            ["Training eval pause"] = "Trainings-Auswertungspause",
            ["Prestige Insight"] = "Prestige-Insight",
            ["Start chips"] = "Start-Chips",
            ["Chip rewards"] = "Chip-Belohnungen",
            ["No automation is remembered yet."] = "Noch keine Automatisierung gemerkt.",
            ["Auto Solve unlock remembered."] = "Auto-Lösen-Freischaltung gemerkt.",
            ["Auto Restart unlock and 50 tokens remembered."] = "Auto-Neustart-Freischaltung und 50 Token gemerkt.",
            ["Auto Solve, Auto Restart, tokens, and Solver Tuning remembered."] = "Auto-Lösen, Auto-Neustart, Token und Solver-Justierung gemerkt.",
            ["No algorithms remembered yet."] = "Noch keine Algorithmen gemerkt.",
            ["Start with RAND."] = "Beginne mit RAND.",
            ["Start with RAND and MERG."] = "Beginne mit RAND und MERG.",
            ["Start with RAND, MERG, and BAL."] = "Beginne mit RAND, MERG und BAL.",
            ["Start with RAND, MERG, BAL, and HEUR."] = "Beginne mit RAND, MERG, BAL und HEUR.",
            ["Insight Amplifier"] = "Insight-Verstärker",
            ["Seed Capital"] = "Startkapital",
            ["Automation Memory"] = "Automatisierungsspeicher",
            ["Algorithm Archive"] = "Algorithmus-Archiv",
            ["Yield Theory"] = "Ertragstheorie",
            ["PPO Bootcamp"] = "PPO-Bootcamp",
            ["PPO Memory"] = "PPO-Speicher",
            ["High Focus"] = "Hoher Fokus",
            ["Stability Model"] = "Stabilitätsmodell",
            ["Insight Extractor"] = "Insight-Extraktor",
            ["Passive Insight"] = "Passiver Insight",
            ["Offline Engine"] = "Offline-Engine",
            ["Offline Buffer"] = "Offline-Puffer",
            ["Agent Synergy"] = "Agenten-Synergie",
            ["Bulk Discount"] = "Mengenrabatt",
            ["Evaluation Efficiency"] = "Auswertungs-Effizienz",
            ["Insight"] = "Insight",
            ["RAND selected"] = "RAND ausgewählt",
            ["RAND deselected"] = "RAND abgewählt",
            ["BAL selected"] = "BAL ausgewählt",
            ["BAL deselected"] = "BAL abgewählt",
            ["BAL tuning updated"] = "BAL-Justierung aktualisiert",
            ["BAL tuning reset"] = "BAL-Justierung zurückgesetzt",
            ["HEUR selected"] = "HEUR ausgewählt",
            ["HEUR deselected"] = "HEUR abgewählt",
            ["HEUR tuning updated"] = "HEUR-Justierung aktualisiert",
            ["HEUR tuning reset"] = "HEUR-Justierung zurückgesetzt",
            ["COMBO selected"] = "COMBO ausgewählt",
            ["COMBO deselected"] = "COMBO abgewählt",
            ["COMBO tuning updated"] = "COMBO-Justierung aktualisiert",
            ["COMBO tuning reset"] = "COMBO-Justierung zurückgesetzt",
            ["LOOK selected"] = "LOOK ausgewählt",
            ["LOOK deselected"] = "LOOK abgewählt",
            ["LOOK tuning updated"] = "LOOK-Justierung aktualisiert",
            ["LOOK tuning reset"] = "LOOK-Justierung zurückgesetzt",
            ["MOCA selected"] = "MOCA ausgewählt",
            ["MOCA deselected"] = "MOCA abgewählt",
            ["MOCA tuning updated"] = "MOCA-Justierung aktualisiert",
            ["MOCA tuning reset"] = "MOCA-Justierung zurückgesetzt",
            ["PLAN selected"] = "PLAN ausgewählt",
            ["PLAN deselected"] = "PLAN abgewählt",
            ["PLAN tuning updated"] = "PLAN-Justierung aktualisiert",
            ["PLAN tuning reset"] = "PLAN-Justierung zurückgesetzt",
            ["Export"] = "Exportieren",
            ["Import"] = "Importieren",
            ["To import your game data, paste in your export text.\n\n" +
                "Importing will overwrite all progress in all of your saves, and it will not be possible to recover old progress."] =
            "Um deine Spieldaten zu importieren, füge deinen Export-Text ein.\n\n" +
            "Der Import überschreibt allen Fortschritt in all deinen Spielständen, und alter Fortschritt kann nicht wiederhergestellt werden.",

            // ---- How To Play + menu help ---------------------------------------------------------
            ["This part of the game is still locked. Keep progressing to reveal this help section."] = "Dieser Teil des Spiels ist noch gesperrt. Mach weiter Fortschritte, um diesen Hilfeabschnitt freizuschalten.",
            ["Welcome!"] = "Willkommen!",
            ["Basics"] = "Grundlagen",
            ["Purpose"] = "Zweck",
            ["Priorities"] = "Prioritäten",
            ["Tip"] = "Tipp",
            ["Usage"] = "Verwendung",
            ["Reward rules"] = "Belohnungsregeln",
            ["Income formula"] = "Einkommensformel",
            ["Speed formula"] = "Tempoformel",
            ["Synergy formula"] = "Synergieformel",
            ["Main formula"] = "Hauptformel",
            ["Allocations"] = "Zuteilungen",
            ["Allocation formulas"] = "Zuteilungsformeln",
            ["Main multipliers"] = "Haupt-Multiplikatoren",
            ["Layer progression"] = "Ebenen-Fortschritt",
            ["Prestige Reset"] = "Prestige-Reset",
            ["PPO"] = "PPO",
            ["<sprite name=\"insight\" tint=1> reward formula"] = "<sprite name=\"insight\" tint=1>-Belohnungsformel",
            ["General:\n" +
                    "<b>moveInterval = max(minInterval, speedInterval x solverPacing x computePacing x agentPacing x trainingPacing)</b>\n\n" +
                    "For heavy search solvers:\n" +
                    "<b>computePacing = max(0.35, 1 - 0.11 x ComputeSpeedLevel)</b>"] =
                "Allgemein:\n" +
                "<b>moveInterval = max(minInterval, speedInterval x solverPacing x computePacing x agentPacing x trainingPacing)</b>\n\n" +
                "Für rechenintensive Such-Solver:\n" +
                "<b>computePacing = max(0.35, 1 - 0.11 x ComputeSpeedLevel)</b>",
            ["Catalyst Stack doubles merge rewards.\n\n" +
                    "<b>salvage = ceil(score x salvageShare x 0.25) x stage x globalIncome</b>\n\n" +
                    "Because runs become longer and more flexible, planning solvers and PPO also become more valuable."] =
                "Catalyst Stack verdoppelt die Merge-Belohnungen.\n\n" +
                "<b>salvage = ceil(score x salvageShare x 0.25) x stage x globalIncome</b>\n\n" +
                "Da Runs länger und flexibler werden, werden auch planende Solver und PPO wertvoller.",
            ["<b><sprite name=\"insight\" tint=1> ~= round((1 + performance x 1.25 + cycleCarry) x usage x insightMultiplier)</b>\n\n" +
                    "Performance is based on PPO score and highest block. Usage comes from Normal Mode runs and frames."] =
                "<b><sprite name=\"insight\" tint=1> ~= round((1 + performance x 1.25 + cycleCarry) x usage x insightMultiplier)</b>\n\n" +
                "Die Leistung basiert auf PPO-Punkten und Höchstblock. Die Nutzung ergibt sich aus Normalmodus-Runs und -Frames.",

            // How To Play — descriptions
            ["The core gameplay is very simple. Place blocks into one of the four stacks.\n\n" +
                    "You can merge two blocks of the same value by placing one on top of the other, earning more score and a larger in-game currency reward <sprite name=\"chips\" tint=1>.\n\n" +
                    "Always make sure there is at least one free space available, and try to keep your runs going for as long as possible. A run ends when the next block can no longer be placed anywhere."] =
                "Das Kern-Gameplay ist sehr einfach. Setze Blöcke in einen der vier Stacks.\n\n" +
                "Du kannst zwei Blöcke gleichen Werts verschmelzen, indem du einen auf den anderen setzt — das bringt mehr Punkte und eine größere Belohnung an Spielwährung <sprite name=\"chips\" tint=1>.\n\n" +
                "Achte immer darauf, mindestens einen freien Platz zu haben, und versuche, deine Runs so lange wie möglich am Laufen zu halten. Ein Run endet, wenn der nächste Block nirgends mehr platziert werden kann.",
            ["The gameplay changes early on, when algorithms begin playing instead of you. From that point forward, your job is to spend your income on upgrades that make future runs faster, longer, and more valuable."] =
                "Das Gameplay ändert sich früh, wenn Algorithmen statt dir zu spielen beginnen. Ab da ist es deine Aufgabe, dein Einkommen in Upgrades zu stecken, die künftige Runs schneller, länger und wertvoller machen.",
            ["The stage multiplier starts at 1x, increases to 5x after unlocking Agents, and reaches 24x after unlocking Modifiers. Because of this, unlocking a new layer is usually more valuable than buying another standard income upgrade."] =
                "Der Phasen-Multiplikator startet bei 1x, steigt nach dem Freischalten der Agenten auf 5x und erreicht nach dem Freischalten der Modifikatoren 24x. Deshalb ist das Freischalten einer neuen Ebene meist wertvoller als ein weiteres Standard-Einkommens-Upgrade.",
            ["Algorithms (solvers) automatically play the game for you.\n\n" +
                    "When Auto Solve is enabled, the selected solver places the blocks. If no solver is selected, the run remains Manual."] =
                "Algorithmen (Solver) spielen das Spiel automatisch für dich.\n\n" +
                "Wenn Auto-Lösen aktiv ist, setzt der gewählte Solver die Blöcke. Ist kein Solver gewählt, bleibt der Run manuell.",
            ["Each solver prioritizes different values when making decisions, so comparing them is worthwhile.\n\n" +
                    "Their behavior can be adjusted after unlocking Tuning. Tuning parameters can be modified using sliders, but their effects may also negatively impact gameplay.\n\n" +
                    "Besides search depth, the biggest difference between solvers is their speed. Solver speed can be upgraded in several places throughout the game."] =
                "Jeder Solver priorisiert bei Entscheidungen andere Werte, daher lohnt sich ein Vergleich.\n\n" +
                "Sein Verhalten lässt sich nach dem Freischalten der Justierung anpassen. Die Parameter werden mit Reglern verändert, ihre Wirkung kann das Gameplay aber auch verschlechtern.\n\n" +
                "Neben der Suchtiefe ist der größte Unterschied zwischen Solvern ihr Tempo. Das Solver-Tempo lässt sich an mehreren Stellen im Spiel verbessern.",
            ["The ultimate goal is to unlock PPO, which is a learning algorithm. It starts out weak because it doesn't understand the game's rules, so it must first be trained in Training Mode.\n\n" +
                    "Later, it becomes the gateway to Prestige and permanent progression.\n\n" +
                    "<b>The requirements to unlock it only become achievable later in the game.</b>"] =
                "Das oberste Ziel ist, PPO freizuschalten, einen lernenden Algorithmus. Er startet schwach, weil er die Spielregeln nicht kennt, und muss daher zuerst im Trainingsmodus trainiert werden.\n\n" +
                "Später wird er zum Tor zu Prestige und dauerhaftem Fortschritt.\n\n" +
                "<b>Die Voraussetzungen zum Freischalten werden erst später im Spiel erreichbar.</b>",
            ["This is the primary place to spend <sprite name=\"chips\" tint=1> during the early game.\n\n" +
                    "Here you unlock automation, speed up and expand gameplay, and increase your income generation.\n\n" +
                    "<b>Some upgrades have little impact on their own but become much stronger when combined with others.</b>"] =
                "Hier gibst du im frühen Spiel hauptsächlich <sprite name=\"chips\" tint=1> aus.\n\n" +
                "Hier schaltest du Automatisierung frei, beschleunigst und erweiterst das Gameplay und steigerst deine Einkommensproduktion.\n\n" +
                "<b>Manche Upgrades wirken allein kaum, werden aber im Zusammenspiel mit anderen viel stärker.</b>",
            ["It's recommended to purchase automation upgrades first so you can start focusing on management as soon as possible."] =
                "Es empfiehlt sich, zuerst Automatisierungs-Upgrades zu kaufen, damit du dich so früh wie möglich auf das Management konzentrieren kannst.",
            ["<b>Keep in mind that Auto Restart consumes <sprite name=\"token\" tint=1>, and cannot function without it.</b>"] =
                "<b>Beachte, dass der Auto-Neustart <sprite name=\"token\" tint=1> verbraucht und ohne sie nicht funktioniert.</b>",
            ["<b>Unlocking Agents increases the game to a 5x stage multiplier.</b>"] =
                "<b>Das Freischalten der Agenten erhöht den Phasen-Multiplikator auf 5x.</b>",
            ["Agents provide active loadout bonuses.\n\n" +
                    "Simply purchasing an Agent isn't enough to make it available, it must also be selected. By default, you can equip two Agents at once, and this limit can be increased through upgrades."] =
                "Agenten geben aktive Loadout-Boni.\n\n" +
                "Einen Agenten nur zu kaufen reicht nicht, er muss auch ausgewählt werden. Standardmäßig kannst du zwei Agenten gleichzeitig ausrüsten; dieses Limit lässt sich durch Upgrades erhöhen.",
            ["<b>The combination of equipped Agents determines which aspect of a run becomes more efficient, since most Agents improve a specific reward source instead of multiplying the entire economy.</b>"] =
                "<b>Die Kombination der ausgerüsteten Agenten bestimmt, welcher Aspekt eines Runs effizienter wird, da die meisten Agenten eine bestimmte Belohnungsquelle verbessern, statt die gesamte Wirtschaft zu multiplizieren.</b>",
            ["Some Agents have little effect on their own, but become significantly stronger when combined with other Agents and upgrades."] =
                "Manche Agenten wirken allein kaum, werden aber in Kombination mit anderen Agenten und Upgrades deutlich stärker.",
            ["Choose Agents based on what's currently limiting your progress. If runs end too quickly, prioritize stability. Once your runs are long enough, score, high-block, or merge rewards become more valuable."] =
                "Wähle Agenten danach, was deinen Fortschritt gerade begrenzt. Enden Runs zu schnell, priorisiere Stabilität. Sind deine Runs lang genug, werden Punkte-, Höchstblock- oder Merge-Belohnungen wertvoller.",
            ["<b>Unlocking Modifiers increases the game to a 24x stage multiplier.</b>"] =
                "<b>Das Freischalten der Modifikatoren erhöht den Phasen-Multiplikator auf 24x.</b>",
            ["Modifiers change the rules of future runs. They provide a higher ceiling, a more flexible board, and more tools for advanced solvers to take advantage of."] =
                "Modifikatoren ändern die Regeln künftiger Runs. Sie bieten eine höhere Obergrenze, ein flexibleres Brett und mehr Werkzeuge, die fortgeschrittene Solver nutzen können.",
            ["Some Modifiers grant actions that can be freely used during gameplay. Every Modifier can also be used in Manual Mode."] =
                "Manche Modifikatoren gewähren Aktionen, die im Spiel frei nutzbar sind. Jeder Modifikator kann auch im manuellen Modus genutzt werden.",
            ["Research is responsible for speeding up and deepening future playthroughs, and it is also where Prestige Reset becomes available.\n\n" +
                    "Here you can purchase permanent upgrades that make gameplay easier, but they require <sprite name=\"insight\" tint=1>.\n\n"] =
                "Die Forschung beschleunigt und vertieft künftige Durchläufe und ist auch der Ort, an dem der Prestige-Reset verfügbar wird.\n\n" +
                "Hier kaufst du dauerhafte Upgrades, die das Gameplay erleichtern, aber sie brauchen <sprite name=\"insight\" tint=1>.\n\n",
            ["<sprite name=\"insight\" tint=1> is generated by letting PPO play in Normal Mode.\n\n" +
                    "<b>You must perform a Prestige Reset to claim your <sprite name=\"insight\" tint=1>.</b>"] =
                "<sprite name=\"insight\" tint=1> entsteht, indem du PPO im Normalmodus spielen lässt.\n\n" +
                "<b>Du musst einen Prestige-Reset durchführen, um deinen <sprite name=\"insight\" tint=1> einzufordern.</b>",
            ["A Prestige Reset removes all accumulated <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, Upgrades, Agents, and Modifiers.\n\n" +
                    "However, your <sprite name=\"insight\" tint=1>, purchased Research, permanent PPO knowledge, and Datacenter progress are preserved."] =
                "Ein Prestige-Reset entfernt alle angesammelten <sprite name=\"chips\" tint=1>, <sprite name=\"token\" tint=1>, Upgrades, Agenten und Modifikatoren.\n\n" +
                "Dein <sprite name=\"insight\" tint=1>, gekaufte Forschung, dauerhaftes PPO-Wissen und der Rechenzentrum-Fortschritt bleiben jedoch erhalten.",
            ["Datacenter is a permanent compute layer that unlocks after your 5th Prestige Reset.\n\n" +
                    "Every upgrade here accelerates different stages of gameplay.\n\n" +
                    "This layer uses <sprite name=\"chips\" tint=1> as its currency again, meaning the production accumulated by PPO in Normal Mode is no longer lost after Prestige Reset."] =
                "Das Rechenzentrum ist eine dauerhafte Rechen-Ebene, die nach deinem 5. Prestige-Reset freigeschaltet wird.\n\n" +
                "Jedes Upgrade hier beschleunigt andere Phasen des Gameplays.\n\n" +
                "Diese Ebene nutzt wieder <sprite name=\"chips\" tint=1> als Währung, sodass die von PPO im Normalmodus angesammelte Produktion nach einem Prestige-Reset nicht mehr verloren geht.",
            ["<b>Be sure to spend your accumulated <sprite name=\"chips\" tint=1> before performing a Prestige Reset, otherwise they will be lost.</b>"] =
                "<b>Gib deine angesammelten <sprite name=\"chips\" tint=1> unbedingt vor einem Prestige-Reset aus, sonst gehen sie verloren.</b>",
            ["You can purchase Server Racks and Facility Upgrades, then allocate the resulting compute capacity however you like between passive PPO training, passive <sprite name=\"insight\" tint=1> generation, or a <sprite name=\"chips\" tint=1> income multiplier."] =
                "Du kannst Server-Racks und Anlagen-Upgrades kaufen und die entstehende Rechenkapazität beliebig zwischen passivem PPO-Training, passiver <sprite name=\"insight\" tint=1>-Erzeugung oder einem <sprite name=\"chips\" tint=1>-Einkommens-Multiplikator aufteilen.",

            // Menu help — bodies
            ["Place the blocks into one of the four stacks.\n\n" +
                "By placing two blocks with the same value on top of each other, you can merge them, earning more score and receiving a larger in-game currency <sprite name=\"chips\" tint=1> reward.\n\n" +
                "Make sure to always keep at least one free space available, and try to make your runs last as long as possible.\n\n" +
                "The gameplay changes early on, when algorithms start playing instead of you. From that point onward, your role is to purchase various upgrades and manage them.\n\n" +
                "<b>You can find details about every important game feature in Settings > How to Play menu.</b>"] =
                "Setze die Blöcke in einen der vier Stacks.\n\n" +
                "Indem du zwei Blöcke gleichen Werts aufeinandersetzt, verschmilzt du sie, erhältst mehr Punkte und eine größere Belohnung an Spielwährung <sprite name=\"chips\" tint=1>.\n\n" +
                "Halte stets mindestens einen freien Platz frei und versuche, deine Runs so lange wie möglich dauern zu lassen.\n\n" +
                "Das Gameplay ändert sich früh, wenn Algorithmen statt dir zu spielen beginnen. Ab da besteht deine Rolle darin, verschiedene Upgrades zu kaufen und zu verwalten.\n\n" +
                "<b>Details zu jeder wichtigen Spielfunktion findest du unter Einstellungen > Spielanleitung.</b>",
            ["Algorithms are responsible for playing the game automatically for you.\n\n" +
                "Each solver prioritizes different values when making decisions, so it's worth comparing them. Their behavior can be tuned once Tuning is unlocked.\n\n" +
                "The ultimate goal is to unlock PPO, which is a learning algorithm. The requirements for unlocking it can only be met later in the game."] =
                "Algorithmen spielen das Spiel automatisch für dich.\n\n" +
                "Jeder Solver priorisiert bei Entscheidungen andere Werte, daher lohnt sich ein Vergleich. Sein Verhalten lässt sich justieren, sobald die Justierung freigeschaltet ist.\n\n" +
                "Das oberste Ziel ist, PPO freizuschalten, einen lernenden Algorithmus. Die Voraussetzungen dafür sind erst später im Spiel erfüllbar.",
            ["Upgrades are the early-game progression layer based on <sprite name=\"chips\" tint=1>.\n\n" +
                "This is where you unlock automation, speed up and expand gameplay, and increase your income generation.\n\n" +
                "It's generally best to prioritize automation upgrades so you can focus on managing your run as early as possible.\n\n" +
                "<b>Keep in mind that Auto Restart consumes <sprite name=\"token\" tint=1>.</b>"] =
                "Upgrades sind die auf <sprite name=\"chips\" tint=1> basierende Fortschritts-Ebene des frühen Spiels.\n\n" +
                "Hier schaltest du Automatisierung frei, beschleunigst und erweiterst das Gameplay und steigerst deine Einkommensproduktion.\n\n" +
                "Meist ist es am besten, Automatisierungs-Upgrades zu priorisieren, damit du dich so früh wie möglich auf das Verwalten deines Runs konzentrieren kannst.\n\n" +
                "<b>Beachte, dass der Auto-Neustart <sprite name=\"token\" tint=1> verbraucht.</b>",
            ["Agents provide active loadout bonuses.\n\n" +
                "Not every owned Agent is active: the combination equipped in your slots determines which aspects of your run become more effective."] =
                "Agenten geben aktive Loadout-Boni.\n\n" +
                "Nicht jeder besessene Agent ist aktiv: Die in deinen Slots ausgerüstete Kombination bestimmt, welche Aspekte deines Runs effektiver werden.",
            ["Modifiers change the rules of future runs. They unlock new possibilities and increase your income, but they also make the board more complex.\n\n" +
                "Some Modifiers can be upgraded multiple times.\n\n" +
                "<b>Purchasing every Modifier unlocks the PPO algorithm, marking the gateway to the endgame.</b>"] =
                "Modifikatoren ändern die Regeln künftiger Runs. Sie eröffnen neue Möglichkeiten und erhöhen dein Einkommen, machen das Brett aber auch komplexer.\n\n" +
                "Manche Modifikatoren lassen sich mehrfach verbessern.\n\n" +
                "<b>Der Kauf jedes Modifikators schaltet den PPO-Algorithmus frei — das Tor zum Endgame.</b>",
            ["Research is the progression layer that unlocks the ability to Prestige Reset.\n\n" +
                "Here, you can purchase permanent upgrades that make gameplay easier and faster, but they require <sprite name=\"insight\" tint=1>.\n\n" +
                "<sprite name=\"insight\" tint=1> is generated by running the PPO algorithm in Normal Mode.\n\n" +
                "To claim your <sprite name=\"insight\" tint=1>, you must perform a Prestige Reset. You can find details in the Console."] =
                "Die Forschung ist die Fortschritts-Ebene, die den Prestige-Reset freischaltet.\n\n" +
                "Hier kaufst du dauerhafte Upgrades, die das Gameplay leichter und schneller machen, aber sie brauchen <sprite name=\"insight\" tint=1>.\n\n" +
                "<sprite name=\"insight\" tint=1> entsteht, indem du den PPO-Algorithmus im Normalmodus laufen lässt.\n\n" +
                "Um deinen <sprite name=\"insight\" tint=1> einzufordern, musst du einen Prestige-Reset durchführen. Details findest du in der Konsole.",
            ["Datacenter is a persistent compute layer that speeds up your Prestiges.\n\n" +
                "Here, <sprite name=\"chips\" tint=1> becomes the currency again, meaning the production accumulated in PPO Normal Mode is no longer wasted when you perform a Prestige Reset.\n\n" +
                "<b>Be sure to spend your accumulated <sprite name=\"chips\" tint=1> before resetting, as any unspent amount will be lost.</b>\n\n" +
                "You can purchase Server Racks and Facility Upgrades, then allocate the resulting compute capacity however you like: to passive PPO training, passive <sprite name=\"insight\" tint=1> generation, or a <sprite name=\"chips\" tint=1> production multiplier."] =
                "Das Rechenzentrum ist eine dauerhafte Rechen-Ebene, die deine Prestiges beschleunigt.\n\n" +
                "Hier wird wieder <sprite name=\"chips\" tint=1> zur Währung, sodass die im PPO-Normalmodus angesammelte Produktion bei einem Prestige-Reset nicht mehr verschwendet wird.\n\n" +
                "<b>Gib deine angesammelten <sprite name=\"chips\" tint=1> unbedingt vor dem Reset aus, da nicht ausgegebene Beträge verloren gehen.</b>\n\n" +
                "Du kannst Server-Racks und Anlagen-Upgrades kaufen und die entstehende Rechenkapazität beliebig aufteilen: auf passives PPO-Training, passive <sprite name=\"insight\" tint=1>-Erzeugung oder einen <sprite name=\"chips\" tint=1>-Produktions-Multiplikator.",
            ["Here you can see detailed data on how your runs perform during the current Prestige cycle.\n\n" +
                "You can view your highest score, best median performance, average run duration, and results for each solver.\n\n" +
                "<b>Measure how a new algorithm, Tuning, or any other modification affects your performance.</b>"] =
                "Hier siehst du detaillierte Daten dazu, wie deine Runs im aktuellen Prestige-Zyklus abschneiden.\n\n" +
                "Du kannst deinen höchsten Punktestand, die beste mediane Leistung, die durchschnittliche Run-Dauer und die Ergebnisse je Solver einsehen.\n\n" +
                "<b>Miss, wie ein neuer Algorithmus, eine Justierung oder eine andere Änderung deine Leistung beeinflusst.</b>",
            ["Here you can track your best results achieved throughout your playtime, along with a summary of your overall progress. You can also see which goals you have already completed.\n\n" +
                "<b>Some milestones grant permanent rewards or cosmetic unlocks.</b>"] =
                "Hier verfolgst du deine besten über die Spielzeit erreichten Ergebnisse samt einer Zusammenfassung deines Gesamtfortschritts. Du siehst auch, welche Ziele du bereits erreicht hast.\n\n" +
                "<b>Manche Meilensteine gewähren dauerhafte Belohnungen oder kosmetische Freischaltungen.</b>",

            // ---- Dynamically-composed labels + datacenter allocation bodies ----------------------
            ["reach Prestige"] = "erreiche Prestige",
            ["rack FLOPS"] = "Rack-FLOPS",
            ["TPU / Fabric"] = "TPU / Fabric",
            ["Effect"] = "Wirkung",
            ["Level"] = "Stufe",
            ["Completed goals"] = "Erfüllte Ziele",
            ["Best run"] = "Bester Run",
            ["moves"] = "Züge",
            ["manual"] = "manuell",
            ["Restart in"] = "Neustart in",
            ["Equipped Agents"] = "Ausgerüstete Agenten",
            ["Active Modifiers"] = "Aktive Modifikatoren",
            ["Buy all Facility Upgrades"] = "Kaufe alle Anlagen-Upgrades",
            ["Offline cap"] = "Offline-Cap",
            ["Offline efficiency"] = "Offline-Effizienz",
            ["New-high learning"] = "Höchstblock-Lernen",
            ["Survival shaping"] = "Überlebens-Formung",
            ["PPO Normal mode at"] = "PPO-Normalmodus bei",
            ["Start with"] = "Beginne mit",
            ["cycle frames"] = "Zyklus-Frames",
            ["frames retained"] = "Frames behalten",
            ["training: +0 chips"] = "Training: +0 Chips",
            ["Pickaxe"] = "Spitzhacke",
            ["Scrubbed"] = "Entfernt",
            ["Merge"] = "Merge",
            ["Combo"] = "Combo",
            ["Spent"] = "Ausgegeben",
            ["Passively trains PPO, which counts as Training Mode frames. <b>PPO learns permanently even when not in use.</b>"] =
                "Trainiert PPO passiv, was als Trainingsmodus-Frames zählt. <b>PPO lernt dauerhaft, auch wenn es nicht genutzt wird.</b>",
            ["Passively generates <sprite name=\"insight\" tint=1> at any stage of the game, so using PPO in Normal Mode is no longer required for that."] =
                "Erzeugt passiv <sprite name=\"insight\" tint=1> in jeder Spielphase, sodass PPO im Normalmodus dafür nicht mehr nötig ist.",
            ["It gives an income multiplier to everything that produces <sprite name=\"chips\" tint=1> in any form."] =
                "Es gibt allem, was in irgendeiner Form <sprite name=\"chips\" tint=1> erzeugt, einen Einkommens-Multiplikator.",
        };
    }
}
